### ISSUE TITLE
Malformed credentials passed by Nextcloud/Rainloop

### ISSUE THREAD

**Issue by omigeot** [pierre-alain-b/rainloop-nextcloud#1]
(oui, je te fais un bug report... ça t'apprendre à maintenir des applications cool et pratique, na!)

When opening the Rainloop app within Nextcloud, it re-asks me for credentials, even though Nextcloud already had them (and was supposed to pass them along).

In my mailserver's logs, I got the following error : 
```
dovecot: auth: ldap(4cb5dd82-b33d-1031-973b-3f7a18a10edf,::1,<3yrGlizdxAAAAAAAAAAAAAAAAAAAAAAB>): invalid credentials
```

And there everything became clear : Nextcloud/Rainloop (not sure which one) transmits my LDAP-generated username instead of something useful. If I'm correct, one arguably easy fix would be to (optionally) allow Nextcloud to send user's email address to Rainloop instead of user's login.

What do you think?

**Comment by omigeot** [comment]
Ok, it's even weirder - and might be an old problem specific to my instance. But for some reason, automatic Rainloop auth only works if I **untick** the "automatic login" checkbox.

**Comment by omigeot** [comment]
Ok, forget it, I somehow misread your code. It just works when unticked because, for some reason, I must have saved credentials in base (still looking for them as it is).

Still, the initial problem stands.

**Comment by pierre-alain-b** [comment]
Thank you for the bug report. I myself do not use LDAP auth and therefore cannot test very easily.

Would it be related to this in any way?
https://github.com/RainLoop/rainloop-webmail/issues/496
Beware, there seems to be a fix in the Expert section of the LDAP settings of ownCloud (version 8 when discussed) but be careful, it is a tough cookie apparently.

**Comment by omigeot** [comment]
Fixing LDAP first is probably the way to go. Let's close this.
