### ISSUE TITLE
Integrating contacts into rainloop

### ISSUE THREAD

**Issue by fgiorlando** [pierre-alain-b/rainloop-nextcloud#10]
Thanks for porting rainloop as a nextcloud plugin.
It would be great to integrate contacts if possible.

I have testes syncing CalDAV contacts in Rainloop and it works well.  However, there's no automatic integration of this feature in the plugin yet.

Would it be possible to have rainloop automatically enter the CardDAV URL for the user based on the login username? This should be predicatible if the email address=username.

![2017-04-17 05 23 44 pm](https://cloud.githubusercontent.com/assets/1149794/25082236/bf69f132-2392-11e7-9ec1-ed12090b2eef.png)

**Comment by pierre-alain-b** [comment]
Well, good point, but then this requires a change deep inside Rainloop which would make the maintenance of the plugin more complicated...
If you can submit a merge request for this, we will of course consider it for inclusion.
PAB

**Comment by DJCrashdummy** [comment]
an other point is the URL: it may be different from user to user... and "especially hard to guess" if the user has more than one. :-/

**Comment by pierre-alain-b** [comment]
what do you mean?

**Comment by DJCrashdummy** [comment]
@pierre-alain-b i just wanted to point out, that it is not that easy somebody may think:

1. the CardDAV-URL of the address book depends on the name of the user and the name of his address book.
i know, if digging deep enough into nextcloud this can be "guessed" and prefilled...

1. but then rainloop only supports one address book...
and if the user has more than one address book, you - or more precisely the code - must have clairvoyant skills to choose the right one.

**Comment by juliusstoerrle** [comment]
What about adding a default "company wide" addressbook for every user in the admin panel?

**Comment by DJCrashdummy** [comment]
@juliusstoerrle this would be awesome, but no idea if this is anyhow possible... :frowning_face:

**Comment by juliusstoerrle** [comment]
Just saw that there is already an issue open here: https://github.com/RainLoop/rainloop-webmail/issues/974
But it would still be great if we could get a auto sync with the nextcloud users contacts.
