### ISSUE TITLE
RainLoop doesn't open after update to 6.0.3

### ISSUE THREAD

**Issue by szaimen** [pierre-alain-b/rainloop-nextcloud#100]
### Steps to reproduce
1. Install RainLoop 6.0.3
2. Open the RainLoop App inside your Nextcloud

### Expected behaviour
3. Should open the rainloop-app

### Actual behaviour
3. the error message appears: "[105] Missing version directory"

## Server configuration detail

**Operating system:** Linux 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.26

**PHP version:** 

7.2.19
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Nextcloud-Snap

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - bookmarks: 1.0.8
 - calendar: 1.7.0
 - circles: 0.17.5
 - cloud_federation_api: 0.2.0
 - contacts: 3.1.3
 - cospend: 0.1.0
 - dav: 1.9.2
 - deck: 0.6.4
 - drawio: 0.9.3
 - event_update_notification: 0.3.4
 - external: 3.3.0
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_3d: 0.1.0
 - files_downloadactivity: 1.5.0
 - files_ebookreader: 0.0.1
 - files_external: 1.7.0
 - files_linkeditor: 1.0.10
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - guests: 1.1.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - keeweb: 0.5.1
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - music: 0.10.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.1
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.7.2
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quickaccesssorting: 1.0.1
 - radio: 0.6.5
 - rainloop: 6.0.3
 - ransomware_detection: 0.5.2
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - spreed: 6.0.3
 - suspicious_login: 1.0.0
 - tasks: 0.11.0
 - telephoneprovider: 1.0.2
 - text: 1.0.1
 - theming: 1.7.0
 - twofactor_admin: 0.4.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_nextcloud_notification: 1.1.2
 - twofactor_totp: 2.1.2
 - video_converter: 0.1.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - comments
 - encryption
 - federation
 - files_texteditor
 - sharebymail
 - sharerenamer
 - support
 - survey_client
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_smtpport": "465",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "trashbin_retention_obligation": "disabled",
    "loglevel": 2,
    "share_folder": "\/Shared",
    "preview_max_x": 1536,
    "preview_max_y": 1536,
    "preview_max_scale_factor": 1,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\HEIC",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\SVG"
    ],
    "app_install_overwrite": [
        "occweb"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** locally mounted smb-share over cifs-utils

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Operating system:** Windows 10 1903

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by pierre-alain-b** [comment]
Thanks for reporting. Could be a permission issue.
Could you try to do this:

cd /path/to/nextcloud/apps/folder/rainloop//app/rainloop/
find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;

Adapted from https://www.rainloop.net/docs/permissions/

**Comment by szaimen** [comment]
That unfortunately didn't work.
But I fixed it: I had do uninstall the app, delete it and reinstall it again. Now everything ist back to work.
I think it is not the best user experience if I have to do that each time from now on.

**Comment by pierre-alain-b** [comment]
I sure hope you will not have to do that everytime. I prepared the package as I usually did, I do not know why it behaved differently when deployed for some users.
