### ISSUE TITLE
Email compose contact suggestion confusion

### ISSUE THREAD

**Issue by ChiefPete** [pierre-alain-b/rainloop-nextcloud#101]
I'm confused on how to configure email address suggestions in the new message compose window.

We have NextCloud integrated with postgresql/dovecot users so each user has an alternate email address (personal email address) set in Nextcloud so they can self reset their password. But currently their alternate email  comes up as a suggestion. I would like the email address suggestion to only include contacts from the Nextcloud Contacts app.

I see in Issue #95 that there is a setting that can be changed in a configuration file. But then @Nutonic goes on to say:
"Thanks a lot, thats exactly what I was looking for. Sorry I had no idea that there was already an option in rainloop, I thought this was a feature of the plugin."

So, do I need to edit the configuration file or is there a setting in the admin panel, or...?

Also, in the admin panel > contacts there is an Enable contacts setting. What does that do?

Thanks for any assistance.

**Comment by pierre-alain-b** [comment]
This needs to be changed in the config file of Rainloop as stated in #95:
`owncloud_suggestions = On`
shall be changed into
`owncloud_suggestions = Off`
in /path/to/folder/owncloud/data/rainloop-storage/_data_/_default_/configs/application.ini

I hope this helps!

**Comment by ChiefPete** [comment]
@pierre-alain-b Thanks for the reply.

So, I made the change in application.ini but then I get no suggestions. That's not going to work with my non-technical users.
