### ISSUE TITLE
There is no Admin panel.

### ISSUE THREAD

**Issue by ploguus** [pierre-alain-b/rainloop-nextcloud#103]
At https://cloud.spryservers.net/settings/user/additional -- there is no "Go to RainLoop Webmail admin panel" link (see screenshot below). I did see [this issue](https://github.com/pierre-alain-b/rainloop-nextcloud/issues/97), but it does not help me. 

I tried https://cloud.spryservers.net/apps/rainloop/app/?admin -- not it.

![Annotation 2019-08-15 115226](https://user-images.githubusercontent.com/22798496/63115233-f67ba580-bf53-11e9-8d21-dfdb0b1ee0b7.jpg)

**Comment by pierre-alain-b** [comment]
The link to the admin panel is available in the general admin panel of Nextcloud, not in the user settings panel.

**Comment by ploguus** [comment]
And one accesses the general admin pan of Nextcloud.....how?

**Comment by pierre-alain-b** [comment]
Well, you have the administration settings for the user.
And if you are an admin of Nextcloud, you have the "Administration" tools just below:
![image](https://user-images.githubusercontent.com/386857/63145185-b4577000-bff6-11e9-9121-487171c8602c.png)

The link to the admin panel for Rainloop is available in the "Additionnal settings" of the "administration" part and not the "user settings" part.
