### ISSUE TITLE
Rainloop does not work on NC17.0.0.beta1

### ISSUE THREAD

**Issue by Larsene** [pierre-alain-b/rainloop-nextcloud#104]
Hi, after updating Nextcloud to NC17.0.0.beta1, Rainloop doesn't work anymore. Plus, if you activate it, it will lock access to the Nextcloud settings page...

**Comment by pierre-alain-b** [comment]
Well taken, I will test this!

**Comment by Valdnet** [comment]
@pierre-alain-b I want to switch to NC 17, have you checked if Rainloop will work with this version?

**Comment by zauguin** [comment]
@Valdnet Currently, on my fully updated instance (beta channel, Nextcloud 17.0.0 RC 1, Rainloop 6.0.3), the problem still persists: Rainloop doesn't work and breaks the settings page.

**Comment by Larsene** [comment]
same here on 17.0.0 RC1. I hope pierre-alain-b will have some time to take a look on it, as rainloop is an essential package for NextCloud !

**Comment by pierre-alain-b** [comment]
I have this in sight and will give it a try. Is the release date of NC 17 known already?

**Comment by Valdnet** [comment]
@pierre-alain-b The release date is unknown, but you can view the progress of the work [here](https://github.com/nextcloud/server/milestone/64).

**Comment by kxu1988** [comment]
Nextcloud 17
Feature freeze: 2019-08-09
Beta 1: 2019-08-15
Beta 2: 2019-08-22
Beta 3: 2019-08-29
Beta 4: 2019-09-05
RC 1: 2019-09-12
RC 2: 2019-09-19
**Release: 2019-09-26**

https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by gruessung** [comment]
+1
My NC log show:
``
Error: Call to undefined method OCP\App::checkAppEnabled()

    /var/www/html/lib/private/Route/Route.php - line 155:

    require_once()

    <<closure>>

    OC\Route\Route->OC\Route\{closure}("*** sensiti ... *")

    /var/www/html/lib/private/Route/Router.php - line 297:

    call_user_func(Closure {}, { _route: "rainloop_index"})

    /var/www/html/lib/base.php - line 1000:

    OC\Route\Router->match("/apps/rainloop/")

    /var/www/html/index.php - line 42:

    OC::handleRequest()
``

AND
`
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "mail.page.index" as such route does not exist.

    /var/www/html/lib/private/Route/Router.php - line 337:

    Symfony\Component\Routing\Generator\UrlGenerator->generate("mail.page.index", [], 1)

    /var/www/html/lib/private/Route/CachingRouter.php - line 60:

    OC\Route\Router->generate("mail.page.index", [], false)

    /var/www/html/lib/private/URLGenerator.php - line 79:

    OC\Route\CachingRouter->generate("mail.page.index", [])

    /var/www/html/custom_apps/mail/appinfo/app.php - line 42:

    OC\URLGenerator->linkToRoute("mail.page.index")

    /var/www/html/lib/private/legacy/app.php - line 260:

    require_once("/var/www/ht ... p")

    /var/www/html/lib/private/legacy/app.php - line 154:

    OC_App::requireAppFile("mail")

    /var/www/html/lib/private/legacy/app.php - line 957:

    OC_App::loadApp("mail")

    /var/www/html/lib/private/Installer.php - line 149:

    OC_App::executeRepairSteps("mail", { step: "OCA ... "})

    /var/www/html/settings/Controller/AppSettingsController.php - line 447:

    OC\Installer->installApp("mail")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OC\Settings\Controller\AppSettingsController->enableApps([ "mail"], [])

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "enableApps")

    /var/www/html/lib/private/AppFramework/App.php - line 126:

    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "enableApps")

    /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OC\\Setting ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})

    /var/www/html/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "s ... "})

    /var/www/html/lib/base.php - line 1000:

    OC\Route\Router->match("/settings/apps/enable")

    /var/www/html/index.php - line 42:

    OC::handleRequest()
`

**Comment by gruessung** [comment]
**Possible Workaround:**
Delete OCP\App::checkAppEnabled('rainloop'); in index.php and personal.php

After i did this rainloop works.

**Comment by zauguin** [comment]
To add some context to @gruessung's comment: `checkAppEnabled` has been deleted in [60894f4](https://github.com/nextcloud/server/commit/60894f4), after it was deprecated for about four years. Especially `checkAppEnabled` was an empty function since [a commit in 2015](https://github.com/nextcloud/server/commit/2f98f642415a041fa0c9820cda022f18c781a9e6), which was part of OwnCloud 9.0. So deleting the call to `checkAppEnabled` should be safe.

**Comment by gruessung** [comment]
I created #106 and #107

**Comment by pierre-alain-b** [comment]
Excellent, let me test it and then accept the merge requests and publish a new version!

**Comment by pierre-alain-b** [comment]
Hi there, thank you for all the people who reported the dysfunctioning Rainloop and proposed merge requests to fix this!
I've now released a version 6.0.4 that incorporates the latest merge requests (after review).
Rainloop 6.0.4 should be proposed soon in the updater.
Could you please give it a try and tell me if this works with NC17? Thank you!

**Comment by Larsene** [comment]
Fixed for me, many thanks :-)

**Comment by gruessung** [comment]
Thanks for accept my pull requests. Version 6.0.4 works fine for me. :)

**Comment by Valdnet** [comment]
Version 6.0.4 also works  fine for me.
Thanks.

**Comment by pierre-alain-b** [comment]
Thank you all for testing!
