### ISSUE TITLE
Two identical sent messages in the sent message

### ISSUE THREAD

**Issue by vincowl** [pierre-alain-b/rainloop-nextcloud#109]
After sending a message, there are two identical sent messages in the sent message
This occurs with :

- Nextcloud : 16.0.4
- Rainloop App : 6.0.4

I am using an outlook.fr domain. Trouble occurs everytime. These duplicated mails can be found in the outlook.fr's sentbox. Any idea ?

**Comment by pierre-alain-b** [comment]
Do you see that with other maiboxes or only outlook.fr mailboxes?

**Comment by vincowl** [comment]
I will test it with Gmail and report what happens. Maybe one important thing : only one mail is "really" sent : I mean only one mail is received by the receiver

**Comment by pierre-alain-b** [comment]
Does this strange behaviour is observed as well with Gmail accounts?

**Comment by vincowl** [comment]
I have just tested it with a gmail account : everything works like a charm. It seems to be only linked with the added domain _outlook.fr_. Strange... I am having a look at its configuration

**Comment by pierre-alain-b** [comment]
Couldn't it be that rainloop copies a copy of the sent email in the Sent box but then the Oulook server does it again? But if this is the case then it should be reported with all webmails. By the way, for duplicate mails, if you connect to the official outlook webmail, you also see the duplicates, right?

**Comment by vincowl** [comment]
![image](https://user-images.githubusercontent.com/16786457/65835832-5b644280-e2eb-11e9-9e36-2987feea8b81.png)
Here is the account configuration. Everything seems OK to me
EDIT : I realize that the screenshot config is in frenhc : I can resend the picture if needed

**Comment by vincowl** [comment]
Yes, duplicates emails also exist in the official outlook webmail. I have just connected an android webmail to this same account to check if this occurs with something else than rainloop. This duplication does not happen with android app.
One important thing : with this android app, today duplicate mails are not shown but I can older duplicates..... Every duplication is shown in rainloop

**Comment by vincowl** [comment]
To be clear : 
- duplication is created when mails are sent through rainloop only
- duplication appears in rainloop and official outlook webmail
- duplication doesn't exist when mails are sent from android app (gmail app) or from official webmail
- today emails sent with rainloop are not displayed as duplicate in android app but appears in rainloop and on official webmail.

I don't understand how this can happen and why so different behaviors exist... No trouble with other domains....

**Comment by pierre-alain-b** [comment]
Now the ultimate test would be to test the outlook account with another webmail such as the "mail" application for Rainloop. This would let us know if the issue is Rainloop-specific !

**Comment by vincowl** [comment]
I've just tested with "mail". Same behavior.... Duplication occurs too... Since it doesn't happen with gmail, I suppose it is due to outlook.fr. But while it doesn't happen with android apps or other webmails (outside of nextcloud), I don't know where I should begin my investigation... Any idea ?

**Comment by pierre-alain-b** [comment]
Which other webmail (outside of nextcloud) have you tested?

**Comment by vincowl** [comment]
I tested roundcube and Thunderbird on linux. As previously said, I also tested Gmail app on android. Everything works like a charm

**Comment by pierre-alain-b** [comment]
I find no explanation except the hypothesis that outlook server is copying all the messages sent through the SMTP server into the Sent folder. One way to test that would be to try the Outlook account in Rainloop but configure a SMTP that is not outlook (just for the test, better to revert to the initial setting afterwards to avoid SPF-related issues and the like). It would help us know if my hypothesis is correct or not.

**Comment by vincowl** [comment]
I cannot test with a different smtp server since then authentication fails. How can I manage this ? I cannot find a place to define the user/password for smtp and imap servers.

**Comment by vincowl** [comment]
I tried the php `mail()` function and the 'no authentication' params, but of course this fails

**Comment by pierre-alain-b** [comment]
I think this issue is Rainloop-specific and should be forwarded and treated by the Rainloop core team. I propose that you transfer the issue to https://github.com/RainLoop/rainloop-webmail/issues but I am afraid they are not very responsive!
