### ISSUE TITLE
autologin with user email

### ISSUE THREAD

**Issue by piti-diablotin** [pierre-alain-b/rainloop-nextcloud#11]
Hi,
First I would like thank you for your great work.
I would like to suggest a tiny modification for the autologin in the admin setting.
On my server, users have a username and an email that does not match username@domain. It can be something very different.
In your admin.php could you add an option to specify if the autologin is done with the username or with the email from the user profile (or if no email provided in the profile, the username then)
And thus modify you app.php so that 
`$sEmail = $sUser;`
can become
`$sEmail = OCP\Config::getUserValue($sUser, 'settings', 'email');`
and of course change accordingly
`$sDecodedPassword = OC_RainLoop_Helper::decodePassword($sEncodedPassword, md5($sUser));`
Thanks in advance

**Comment by pierre-alain-b** [comment]
I like it. Could you try to put this in a merge request maybe? After testing, I will merge it in the base code.
Best
PAB

**Comment by pierre-alain-b** [comment]
Closing but ready to see any merge request to bring this feature.

**Comment by JimmyKater** [comment]
idk if closing and hoping for a merge would be the right way to be successful...
so why not leaving it open? more ppl will have a look, then

**Comment by Der-Zohan** [comment]
Maybe someone else need it.

For me this is not working with NC 14
`$sEmail = OCP\Config::getUserValue($sUser, 'settings', 'email');`

changing to this does the trick for me
`$sEmail = \OC::$server->getConfig()->getUserValue($sUser, 'settings', 'email','');`

like above this must be set after the if else block 
`$sDecodedPassword = OC_RainLoop_Helper::decodePassword($sEncodedPassword, md5($sUser));`
