### ISSUE TITLE
Autologin failed

### ISSUE THREAD

**Issue by th-schwarz** [pierre-alain-b/rainloop-nextcloud#112]
NC 16.0.5
Plugin version: 6.0.4

Briefly: I've removed rainloop and installed it again. Since that moment, I didn’t have any ‘additional settings’ for rainloop.

I enabled the logging to verify why the autologin fails. I've found the following entries: 
[17:39:22.430][e212909d] REQUEST[NOTE]: [GET] https://mydomain.com/index.php/apps/rainloop/app/?OwnCloudAuth
[17:39:22.430][e212909d] LOGIN[DATA]: The email address "MyNCLogin" is not complete
[17:39:23.431][e212909d] INFO[NOTICE]: RainLoop\Exceptions\ClientException: InvalidInputArgument[903] in /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.13.0/app/libraries/RainLoop/Actions.php:2232
Stack trace:
#0 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.13.0/app/libraries/RainLoop/ServiceActions.php(269): RainLoop\Actions->LoginProcess('MyNCLogin', 'MyNCPassword')
#1 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceOwnCloudAuth('')

i was wondering why not the user's email is taken.

Did I forget to configure something? 

Thanks a lot for the nice plugin!
Thilo

**Comment by pierre-alain-b** [comment]
Are you sure you are looking at the "Administration" additional settings and not the "Personal" additional settings?

**Comment by th-schwarz** [comment]
I'm sure. And I verified it with a new test user.
Very strange, isn't it!

Just to clarify: at the "Administration" additional settings I've to enable 'Automatically login with Nextcloud user credentials' and at the "Personal" should be settings for rainloop, right? But there are not there!

**Comment by pierre-alain-b** [comment]
In fact no, if you select "Automatically login with Nextcloud user credentials" then the "additional settings" disappear because the user cannot select his/her own credentials. Can you try again after disabling this option?

**Comment by th-schwarz** [comment]
Shame on me!
I got it wrong!

Thanks as lot.
