### ISSUE TITLE
Merge this into /nextcloud?

### ISSUE THREAD

**Issue by enoch85** [pierre-alain-b/rainloop-nextcloud#113]
Hey! 

Thanks for a great app!

I read that you plan to abandon this app due to lack of time. That would be a shame. That got me thinking, why not merge it into the Nextcloud main repo to get a wider spread, and maybe someone that would take over maintaining?

Just a thought though...

**Comment by pierre-alain-b** [comment]
Hi Daniel. For now it is not abandoned as I find some free time to handle (the best I could) the changes and the releases (I am doing the minimum viable I guess). But I am certainly not opposed to it, especially as I have just been maintaining the app, taking into account the releases by the Rainloop team, but I was never involved in the development of neither Rainloop nor the initial plugin (initially for owncloud).
Is this an official offer from the Nextcloud team to incorporate the app?

**Comment by enoch85** [comment]
> Is this an official offer from the Nextcloud team to incorporate the app?

I'm not part of the core-team per say, so no. :)

> For now it is not abandoned

Ok, feel free to close this issue then.

**Comment by pierre-alain-b** [comment]
Well, maybe not closing immediately to read the comments of others?
