### ISSUE TITLE
Autologin Not Working

### ISSUE THREAD

**Issue by palmtown** [pierre-alain-b/rainloop-nextcloud#114]
Hello,

Although rainloop-autologin is enabled, it doesn't appear to be working.  After debugging, I found that the $sDecodedPassword assigned in app.php is empty.  Note that I am using a vanilla setup with user_sql (https://github.com/nextcloud/user_sql/) app enabled as well.

**Comment by pierre-alain-b** [comment]
I am wondering if the the Merge Request #111 will not fix this issue as well...
Would you mind trying @palmtown?

**Comment by pierre-alain-b** [comment]
I am closing in the absence of a reply but we will reactivate if you had the chance to give it a try.
