### ISSUE TITLE
too small framed window for PDF viewer in Chrome based browsers

### ISSUE THREAD

**Issue by nextgen-networks** [pierre-alain-b/rainloop-nextcloud#118]
Hello Users,
since a couple of weeks I face a annoying bug with my main browser:
PDF files attached to e-mail that are opened from within rainloop are shown in a way to small frame instead of the regular browser based near full sized window.

Any ideas why this happens? Or better: Ideas how to solve?
... my thoughts (without any deeper research): Rainloop uses browser detection and an own (faulty) pdf-renderer instead of the native one from the browser

Systems:
Google Chrome v77 & 78 is affected
MS Edge RTM is fine
MS Edge Chrome based beta v77 is affected
![2019-11-12 Rainloop-ChromePDFviewer-error](https://user-images.githubusercontent.com/21206978/68666596-7eb61a80-0544-11ea-88f5-1833c7494a5b.png)

**Comment by pierre-alain-b** [comment]
Certainly linked to a hack we had to do to resize the rainloop window to fit the whole nextcloud screen. Can you give me the steps to reproduce?

**Comment by nextgen-networks** [comment]
@pierre-alain-b to reproduce simply klick the PDF button on a attachment of any mail that has a pdf file attached.
(don't klick on the filename - because this downloads the pdf/attachment)
![image](https://user-images.githubusercontent.com/21206978/69064568-ab73a180-0a1e-11ea-9654-24694d21a4bf.png)

**Comment by ColinChargy** [comment]
Hi,
This seems to be an issue with Rainloop itself (see https://github.com/RainLoop/rainloop-webmail/issues/1733#issuecomment-555213484 ) not specific to this plugin.
Regards,
Colin Chargy

**Comment by pierre-alain-b** [comment]
I have just tried with Chromium 80 and I see no issue. Is this issue still active for latest Chrome/Chromium versions?

**Comment by ColinChargy** [comment]
Hi @pierre-alain-b 
Yes it is :
![image](https://user-images.githubusercontent.com/6624871/82034234-349e2500-969e-11ea-94b1-03f6c1680458.png)
Regards,
Colin Chargy

**Comment by nextgen-networks** [comment]
Hey @pierre-alain-b,
no issue with latest 6.1.2 release with Chrome 81.0.4044.138 (latest official build for Windows 64-Bit).
Greetings Ralf

**Comment by pierre-alain-b** [comment]
So Ralf and I see no issue
Colin sees an issue
Someone else?

**Comment by nextgen-networks** [comment]
@pierre-alain-b
I think this issue can be closed and marked as resolved.
Ich someone faces the issue again they may reopen it.
