### ISSUE TITLE
MIAB Plugin Functionality? 

### ISSUE THREAD

**Issue by Tom5421** [pierre-alain-b/rainloop-nextcloud#120]
Hi, is it possible that the following plugin is added to add support for MIAB users?

https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/mailinabox-change-password

Thanks.

**Comment by pierre-alain-b** [comment]
As far as I know you can add the plugins on your running instance, just go in Admin panel, plugins.
The plugin cannot be added as a default for all rainloop@nextcloud users though you will active it for your needs in no time.
