### ISSUE TITLE
After installing rainloop users cant open the settings page of nextcloud

### ISSUE THREAD

**Issue by Markus87** [pierre-alain-b/rainloop-nextcloud#121]
Nextcloud 17.0.1.1 / nginx / php-fpm

I just set up rainloop today and its really cool compared to the default mail app.
But I noticed that normal users no longer can access the settings page of nextcloud after installation.
Instead it just seems to redirect to "apps/files".
If I disable the app it works again. For the Administrator account it always works.

I did not find anything in the logs.
How can I help you to resolve this problem?

**Comment by pierre-alain-b** [comment]
I will test this - I see no reason for that.

**Comment by drm87** [comment]
I can confirm the same behaviour, but it only happens to certain users.
I can not determine the difference yet and can not see anything in the logs.

**Comment by mmetzmac** [comment]
same for me ... found out, that this only applies to users who are group admin.

**Comment by pierre-alain-b** [comment]
I cannot replicate - with Rainloop activated in NC17, all my users (incl. users in group admin) can still access the settings page.
Do you have anything specific in your nginx config? Any special redirect?

**Comment by mmetzmac** [comment]
it is not the admin user nor the normal user. Only Groupadmins are affected. So, install Groupfolders. Apply a special usergroup to it and make one user groupadmin of that usergroup. exactly this user is then not able to access the general setings page. Real Admins an users without being groupadmins are not affected. hope, this makes it a little bit clearer.

**Comment by pierre-alain-b** [comment]
I have done as you suggest:
- install "GroupFolders"
- create a "test" folder in GroupFolders and make it accessible to group "family" with "john" as admin for the folder
- open account of user "john" in group "family"
- go to settings
it works...
Did I miss something?

**Comment by mmetzmac** [comment]
is john the groupadministrator for family in the User settings? The field is named „Group admin for“

**Comment by pierre-alain-b** [comment]
But then it is not related with Groupfolders, is it? Or you should have both "GroupFolders" and the the user as group admin to see the issue?

**Comment by mmetzmac** [comment]
Sorry - you are right - the concern is with the group admin permission within the user settings screen and not with the group folders. See attached picture - only the red marked user is unable to use the setting screen if rainloop is installed (redirect to apps/files). If Rainloop is not installed, Settings screen works as expected.

![Bildschirmfoto 2019-11-24 um 18 06 34](https://user-images.githubusercontent.com/536857/69498244-d1e58100-0ee5-11ea-8c42-b7fdf8adf22c.png)

**Comment by mmetzmac** [comment]
have you had the chance, to look into this?

**Comment by pierre-alain-b** [comment]
Sorry, not yet

**Comment by linuxpete** [comment]
This is indeed a Rainloop problem. When I disable Rainloop my user can get to his settings again. So we have 2 workarounds: 
* remove the groupadmin-ship of this specific user
* or disable Rainloop

Further important to note is that the user switches to the default app, which is mostly Files but can be modified by the app-order app. In my case the user switches to Bookmarks which is the default app. This is the first app in the top-row.

See https://github.com/nextcloud/server/issues/18793

**Comment by WNYmathGuy** [comment]
My posting #18865 turned out to be this problem too. 

When I disabled the Rainloop app, the settings worked again. Right after reenabling it they stopped working again. 

Here's a piece that may help in the debug though... 
No user on my system apart from the real Admin and my account used Rainloop. That would indicate that something happens when any non-super-admin uses Rainloop that causes the redirection error.

**Comment by noci2012** [comment]
There might more at play here, as i didn't use rainloop and a group admin cannot access the settings.
Disabling group admin fixed that, otoh other applications might have a similar interaction with groupadmin.   At least this provides some testable environments.

**Comment by noci2012** [comment]
Also ocDownloader: https://github.com/nextcloud/server/issues/17899

**Comment by noci2012** [comment]
The checkAdminUser call redirects the settings page to de default /apps/files page.
Which is not desirable. (Nextcloud 17+ behaviour combined with groupadmin ).

Solution: Either disable the offending app or
See here for the solution:
nextcloud/server#18865

in this case: apps/rainloop/admin.php
```
+if (!OC_User::isAdminUser(OC_User::getUser())) {
+   return;
+}
-User::checkAdminUser();
```
t/y.

**Comment by WNYmathGuy** [comment]
For linking purposes, I had a similar thing. My details are here https://github.com/RainLoop/rainloop-webmail/issues/1985

**Comment by WNYmathGuy** [comment]
Gaaahhhh!!! I forgot to mention my counterexample of admins without trouble getting to the settings page.

On my cloud, I have two users with admin privileges, the one that represents me as a person, and the original admin made when the system was installed. The original admin can see settings, and all other users (basically my family), but the user that represents me cannot. 

The main difference is only the persona that represents me has used Rainloop, nobody else does eMail via the cloud interface.

**Comment by glOOmyART** [comment]
I can confirm this behaviour in NC 18.0.3 and Rainloop 6.1.0.
As soon as I make my user admin of any group I can't access my settings page.
When I remove my user as group admin, I can access my settings page.

**Comment by Schleichmichl** [comment]
Same Problem in NC 18.0.4.
Group admins not possible or I have to disable rainloop :-(
Please fix as soon as possible.

**Comment by pierre-alain-b** [comment]
If someone has a fix, any pull request will be promptly merged!

**Comment by noci2012** [comment]
maybe: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/121#issuecomment-596102879 ?

**Comment by pierre-alain-b** [comment]
I am trying.

**Comment by pierre-alain-b** [comment]
I've released version 6.1.1, with the fix proposed here https://github.com/pierre-alain-b/rainloop-nextcloud/issues/121#issuecomment-596102879. Could you let us know if this works better?

**Comment by Markus87** [comment]
@pierre-alain-b Thanks! Just tested it with v6.1.2 works now as expected for me.

**Comment by pierre-alain-b** [comment]
Excellent, I'm closing the issue then!
