### ISSUE TITLE
Can't reset admin password

### ISSUE THREAD

**Issue by expert-geeks** [pierre-alain-b/rainloop-nextcloud#122]
I'm trying to reset the admin password. admin/12345 is not working for me to log in to allow me to reset/change the password. Uninstalling and reinstalling the app doesn't reset the password. Other posts refer to editing application.ini []https://github.com/pierre-alain-b/rainloop-nextcloud/issues/94 but the data-storage folder does not appear to exist in this version ?

/var/www/nextcloud/data only has index.html & nextcloud.log

I tried creating

/var/www/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini

but this is ignored.

**Comment by pierre-alain-b** [comment]
Where is the data folder of the nextcloud instance?

**Comment by expert-geeks** [comment]
I didn't set in during installation so I presume it's the default;
/var/www/nextcloud/data

root@nextcloud:/var/www/nextcloud/data# find /var/www/nextcloud/ -name "*.ini"
/var/www/nextcloud/apps/rainloop/app/rainloop/v/1.13.0/app/domains/outlook.com.ini
/var/www/nextcloud/apps/rainloop/app/rainloop/v/1.13.0/app/domains/yahoo.com.ini
/var/www/nextcloud/apps/rainloop/app/rainloop/v/1.13.0/app/domains/qq.com.ini
/var/www/nextcloud/apps/rainloop/app/rainloop/v/1.13.0/app/domains/gmail.com.ini

there isn't an application.ini to be found...

**Comment by pierre-alain-b** [comment]
Do you see your users' folders in /var/www/nextcloud/data/ ?

**Comment by expert-geeks** [comment]
root@nextcloud:/var/www/nextcloud/data# ls
index.html  nextcloud.log

no, there's nothing in that folder apart from index.html and nextcloud.log :(

**Comment by pierre-alain-b** [comment]
so your data folder is not where you think :-) and when you will find your data folder, you will find the rainloop storage folder as well!

**Comment by pierre-alain-b** [comment]
I am therefore closing the issue which is not a Rainloop issue.

**Comment by expert-geeks** [comment]
THANK YOU!!! Apologies for the confusion :)

**Comment by expert-geeks** [comment]
You sir, are a star.

**Comment by pierre-alain-b** [comment]
Happy to have helped!
