### ISSUE TITLE
NC18 update

### ISSUE THREAD

**Issue by MartinSfromB** [pierre-alain-b/rainloop-nextcloud#125]
Is there a plan to update the app to work with nextcloud 18?

**Comment by nextgen-networks** [comment]
There is a PR already waiting for approval (https://github.com/pierre-alain-b/rainloop-nextcloud/pull/124) - so it's in pipeline and @pierre-alain-b will have a look at that for sure :-)

**Comment by pierre-alain-b** [comment]
Merged, a new release will be published soon
