### ISSUE TITLE
Ability to translate the name "Email"

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#133]
I suggest that you add the option to translate the name "Email". It is spelled differently in different languages.
Code:
https://github.com/pierre-alain-b/rainloop-nextcloud/blob/be43d3a34faa0533a427afe3fb9eeec2407befdc/rainloop/appinfo/app.php#L31

**Comment by Valdnet** [comment]
@pierre-alain-b Merge request: #137 and #138.
I have added the option to translate the app name for navigation in Nextcloud.

**Comment by pierre-alain-b** [comment]
thank you!
