### ISSUE TITLE
New Rainloop release 1.14

### ISSUE THREAD

**Issue by feutl** [pierre-alain-b/rainloop-nextcloud#135]
https://github.com/RainLoop/rainloop-webmail/releases/tag/v1.14.0

As far as I understand this things, just some small changes, but useful for GMAIL users, as it seems.
https://github.com/RainLoop/rainloop-webmail/compare/v1.13.0...v1.14.0

**Comment by pierre-alain-b** [comment]
Thank you for the info. Well noted.

**Comment by pierre-alain-b** [comment]
I am considering a new release soon!
