### ISSUE TITLE
Translation of information for "Save"

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#139]
I suggest adding the option to translate words in the information for "Save":

- Saved successfully
- Invalid Argument (s)

https://github.com/pierre-alain-b/rainloop-nextcloud/blob/72d765a0af4c02883ea59021b36d9a48a9a8e026/rainloop/ajax/admin.php#L31-L36
https://github.com/pierre-alain-b/rainloop-nextcloud/blob/72d765a0af4c02883ea59021b36d9a48a9a8e026/rainloop/ajax/personal.php#L40-L45

**Comment by pierre-alain-b** [comment]
Good idea!

**Comment by pierre-alain-b** [comment]
I suggest this is proposed as a PR if it was tested successfully. Note that the best would be to build this upon the PR of @nkinkade because there is a high chance we will build upon this for version 7.0 of the plugin

**Comment by nkinkade** [comment]
@pierre-alain-b is right. Assuming the App Framework PRs gets merged and put into production, both of those files will go away. But this doesn't invalidate your suggestions, @Valdnet, it just moves the [location for those translations to a different file](https://github.com/nkinkade/rainloop-nextcloud/blob/appframework-nc14/rainloop/lib/Controller/AjaxController.php).

**Comment by Valdnet** [comment]
@nkinkade Thanks :wink:.
In PR you should add the possibility to refer to the translated text in other languages.
```
<p>
	Enter an email and password to auto-login to RainLoop. <b>Please note</b> that this feature
	<a href="https://github.com/pierre-alain-b/rainloop-nextcloud/issues/87"
	style="color:blue; text-decoration:underline" target="_blank">may have some</a>
	<a href="https://github.com/RainLoop/rainloop-webmail/issues/1082"
	style="color:blue; text-decoration:underline" target="_blank">security considerations</a>.
</p>
```

**Comment by nkinkade** [comment]
I'll update my PR, @Valdnet. Thank you for the suggestion!

**Comment by Valdnet** [comment]
@nkinkade Currently, an error appears when saving settings in the NC administration panel.

![obraz](https://user-images.githubusercontent.com/47037905/82095565-92168e00-96ff-11ea-999b-a14aab1bf385.png)

**Comment by nkinkade** [comment]
@Valdnet: What version of the app are you using? My changes are not deployed to any available version of this app. Are you testing the code from my PRs? If so, the Nextcloud log (data/nextcloud.log) should have details.  Also, your comment seems completely unrelated to this issue, no?

**Comment by Valdnet** [comment]
@nkinkade I tested your branch and thought that the problem is only in it. Today I tested the @pierre-alain-b main branch and the problem is the same.

> Also, your comment seems completely unrelated to this issue, no?

The error itself is not about the topic, but the text to be translated.
It looks like the problem is in the master branch. I will write a new issue soon.

**Comment by pierre-alain-b** [comment]
The "save" issue is to be discussed in #159 
If the translation of the save button is good in @nkinkade PR, I propose to close this issue. Do you agree?

**Comment by Valdnet** [comment]
Well. You can close :wink:.

**Comment by Valdnet** [comment]
@pierre-alain-b In connection with taking translations from Transefix, I have to think about a new solution. Getting into the code, I have a dilemma whether this message is certainly displayed `Invalid argument(s)`.

**Comment by nkinkade** [comment]
@Valdnet: It is not likely to be displayed, but could _possibly_ be displayed:

https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Controller/AjaxController.php#L38

I also see that those XHR responses are not internationalized. I know very little about how i18n works in Nextcloud, and in what contexts one can use the `$l->t('<string>')` syntax. If that syntax can be used in any PHP code throughout the app, then we could just wrap those strings in that function and make sure they are added to the l10n files.

Or, I may be completely misunderstanding your comment, which wasn't direct at me anyway. :)

**Comment by Valdnet** [comment]
> Or, I may be completely misunderstanding your comment, which wasn't direct at me anyway. :)

@nkinkade You understood me well and thanks for the reply :wink:.

This line of https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/js/rainloop.js#L87 code can be changed to `oDesc.text(t('rainloop', 'Saved successfully'));`
provided that this text https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Controller/AjaxController.php#L38 will never be used. In this arrangement, Transefix will correctly add the text to be translated. What do you think?

Unless you have a different solution.

**Comment by nkinkade** [comment]
@Valdnet: is Transifex the tool you are personally using, or is it the official tool for this whole app. Can it only work with the javascript files and not the PHP files?

I'm not sure the solution you propose above is the best one because it removes the ability of the core PHP backend code to send the right message. I believe the PHP code should determine the message. The client (the javascript in this case), just reads the response from the server and prints it.

Would it not be possible to simply internationalize [the strings](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Controller/AjaxController.php#L44) in the PHP file instead, assuming one can internationalize strings non-template documents?

**Comment by Valdnet** [comment]
> is Transifex the tool you are personally using, or is it the official tool for this whole app. Can it only work with the javascript files and not the PHP files?

@nkinkade It can also work with PHP files.

> Would it not be possible to simply internationalize the strings in the PHP file instead

How would you do that? Can you put it in PR?

**Comment by Valdnet** [comment]
I did it in the `rainloop.js` file. PR: #194.

**Comment by nkinkade** [comment]
@Valdnet: I don't believe that the JS file is the right place for that. Any reason your PR couldn't be [modify the PHP file](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Controller/AjaxController.php#L44) insteaed? I just haven't had a free moment to do it.
