### ISSUE TITLE
Cannot sync carddav from Nextcloud

### ISSUE THREAD

**Issue by Nesousx** [pierre-alain-b/rainloop-nextcloud#14]
Hi,

First of all thanks for the great app! I really love it. I however, experience an issue. I can't synchronize my contacts books.

I did setup the contact book in the settings page (I have tried multiple URLs that works with other sync "clients"). The carddav comes from the same nextcloud instance that runs the rainloop.

Each time  I go to Address Book > Synchronization, I get an "Unknown error" message in my browser. In the meantime, I have the following error message in the rainloop logfile:

[04:00:58.323][8ac36a89] AJAX[DATA]: {"Action":"Contacts","Result":false,"ErrorCode":999,"ErrorMessage":"1045 - SQLSTATE[HY000] [1045] Access denied for user 'root'@'nesobkp' (using password: NO)","ErrorMessageAdditional":"","Time":78}

To give a little more info: nesobkp is the name of the jail (freenas) I am running my nexcloud info.
About my nextcloud install I am using mysql to store the data,  with nextcloud user (not root) and localhost as host (not nesobkp).

So I am not sure why it throws me an error about mysql while I try to connect to a webdav URL... but this is all I found in the logs.

I hope it helps debugging.

Thanks a lot in advance,

**Comment by pierre-alain-b** [comment]
Hello,
It does not seem to be a bug to me, rather a misconfiguration of Rainloop or the database.
Can you share how you set up the database in the "Contacts" section of the Rainloop admin settings?
PAB

**Comment by Nesousx** [comment]
Thanks for the fast answer.

I am currently using the following URL:

https://myserver.com/remote.php/dav

also tried:
http://myserver.com/.well-known/carddav (which works on Mac OS)
or:
https://myserver.com/remote.php/webdav (works in DAVdroid)
or even:
https://myserver.com/
and:
https://myserver.com/remote.php/dav/addressbooks/users/nesousx/contacts/ (from the Nexctloud contact app "show url" link).

Always got the same error with all those URLs.

The only settings I can set up in Rainloop Contacts admin section are: URL user and password.

**Comment by pierre-alain-b** [comment]
OK, I am not referring to this but the setting of the database for Rainloop.

Go to Nextcloud Admin, Additional Settings, Rainloop section, "Rainloop admin panel".
Then, in the Contacts section, "Storage (PDO)".

![screenshot_2017-05-11_08-17-16](https://cloud.githubusercontent.com/assets/386857/25935218/4fd7d51c-3622-11e7-80eb-ffd11f05b3d9.png)

**Comment by pierre-alain-b** [comment]
In my case above, you see sqlite. I expect that we shall see "mysql" in your case, with maybe "root" user that you need to set up accordingly.

**Comment by Nesousx** [comment]
Oh, I see. Totally forgot about that one!

Just to understand how it works, Is it getting my contacts from the carddav then "dumping" them in a new DB I have to create? Or do you I have to enter the already existing Nextcloud DB (in that case, what's the point setting up the carddav URL like I was trying?), or am I missing something else?

**Comment by pierre-alain-b** [comment]
You would rather have a separate database to store the addressbook of Rainloop. So it can (and shall presumably) be a different database than the Nextcloud one. Rainloop is *not* retrieving the info from Nextcloud database but is synchronizing through carddav and dumping in the database as you suggest.

As an explanation, Rainloop is first and foremost a standalone webmail and the integration within Nextcloud is not as deep as it could be (but this is then easier for maintainability of the plugin when Rainloop evolves).

Have a good day.
