### ISSUE TITLE
Notifications cannot be set

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#144]
You cannot enable notification of new messages in the mail settings.

![obraz](https://user-images.githubusercontent.com/47037905/74842642-08873800-532b-11ea-917e-500bc5d5e29f.png)

Rainloop Nextcloud: 6.1.0
Nextcloud: 18.0.1

**Comment by pierre-alain-b** [comment]
This issue shall be sent to the main Rainloop team I guess if it is a feature of Rainloop that is not working as expected. Unless you know it works with vanilla Rainloop but not with the Nextcloud-embedded version?

Of note, browsers have been restricting the capacity of web apps to send notifications (e.g. default behavior is now to _not_ display notifications in Firefox). Are you sure the notifications are not blocked by your web browser?

**Comment by Valdnet** [comment]
> Unless you know it works with vanilla Rainloop but not with the Nextcloud-embedded version?

I don't know that because I don't have this version installed.

> Are you sure the notifications are not blocked by your web browser?

The browser does not request notification.
The problem is that when selecting notifications in Rainloop in Firefox as if he wanted to select, but returns back to the empty window at the setting.

In Mozilla, when blocking notifications, the option is grayed out with the message about blocking notifications.

![obraz](https://user-images.githubusercontent.com/47037905/74920124-ef829380-53cb-11ea-8439-96328427d14b.png)

**Comment by DJCrashdummy** [comment]
i'm pretty sure this has to do with your browser settings... at my setup it works flawlessly!

if i block the notifications for my nextcloud domain, i also see it greyed out as in your last screenshot and can't check it.
- click on the symbols left beside `https://...` and disable the blocking of the notifications (and reload the site)!
- if this does not work, you have to go into the browser settings for "privacy & security" and "notifications"... and then at the window for notification settings, either enable them for your nextcloud domain manually or uncheck the disabling of new requests (if checked).

for sure you have to confirm the permission of notifications additionally via the "browser bubble" after requesting it via checking the box on the site.

**Comment by pierre-alain-b** [comment]
It works like a charm for me as well.

**Comment by Valdnet** [comment]
@pierre-alain-b In general, when the browser for the first time does not ask for permission to display a notification for a given page, which is associated with not giving permissions in:

![obraz](https://user-images.githubusercontent.com/47037905/82055350-a6876600-96c0-11ea-9ddc-ca9d77c091ea.png)

then the problem described by me appears.

If I add it manually and allow notifications, then the rainloop function works correctly.

In my opinion, if there is no page in the notification settings, there should be a message about blocking notifications in rainloop as for standard blocking.

![obraz](https://user-images.githubusercontent.com/47037905/82056119-bf444b80-96c1-11ea-9b76-d4f6f2141749.png)

@DJCrashdummy Thanks for the explanation. I know the subject 😉.

**Comment by pierre-alain-b** [comment]
Which browser are you using?

**Comment by Valdnet** [comment]
Browser:
Firefox 76.0.1

**Comment by pierre-alain-b** [comment]
I am using the same browser with no issue. Haven't you an extension or a specific setting that says that by default the notifications are not proposed?
If you have a few minutes, you could start Firefox with a blank profile to see if you have the same behaviour... I cannot replicate the issue you have for now.

**Comment by pierre-alain-b** [comment]
I am closing because I think this is specific to your setting. We will re-open of course if this is reported by others.

**Comment by DJCrashdummy** [comment]
@Valdnet a screenshot of the whole window *"Settings - Notification Permissions"* would have been interesting... perhaps you have *"Block new requests asking to allow notifications"* active, then it would be clear. it must look like this:
![image2](https://user-images.githubusercontent.com/26110463/82693099-2f724480-9c61-11ea-9386-81b45a24356c.png)

if it looks like this, it must be a different addon or some other setting in the `about:config`... in this case i would test it in a private window (if you have [disabled all addons at it](https://support.mozilla.org/en-US/kb/extensions-private-browsing#w_enabling-or-disabling-extensions-in-private-windows)), or resp. if nothing has changed, as pierre said, test it with a new temporary profile (https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles).

btw: do you get notifications from your nextcloud itself? (...which i doubt. - then it is rather an issue of nextcloud, as long as notification from other sites are shown nevertheless and it is not a messed up profile on your side.)

**Comment by Valdnet** [comment]
@DJCrashdummy Thanks for the tips. The "Block new requests asking to allow notifications" option you mention is not selected.
