### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#145]
When the "Use short login" option is enabled in the IMAP mail domain settings, an authorization error occurs when connecting a mail user.

![obraz](https://user-images.githubusercontent.com/47037905/74845924-f8258c00-532f-11ea-8e24-b54eb833f060.png)

Rainloop Nextcloud: 6.1.0
Nextcloud: 18.0.1

**Comment by pierre-alain-b** [comment]
Could you give more details?
Isn't it that the underlying IMAP server is waiting the full email as the login?

**Comment by Valdnet** [comment]
> Isn't it that the underlying IMAP server is waiting the full email as the login?

This is.

I thought he was adding the end of the email address from the default domain.

![obraz](https://user-images.githubusercontent.com/47037905/74918520-7eda7780-53c9-11ea-8128-aef47c6e358d.png)
If it is not an issue, it can be closed.
