### ISSUE TITLE
AdminPanel with Admin 12345, gives auth error

### ISSUE THREAD

**Issue by jansralf** [pierre-alain-b/rainloop-nextcloud#148]
Hi, 
i have just installed the rainloop app on nextcloud 17.0.3 with german language and found the link to the admin panel, but user: admin with pw:12345 does not work for me.

My user is admin, but is no group admin.
Is this a new error?
Please help.
best regards
Ralf

**Comment by pierre-alain-b** [comment]
Can you have a look at the file
/var/www/nextcloud/data/rainloop-storage/data/default/configs/application.ini
to potentially reset the password?

**Comment by jansralf** [comment]
The path is different in my installation: .../_data_/_default_/configs/application.ini
But setting the pw to 12345 worked.
Thank you :-)

**Comment by jansralf** [comment]
I have .../__data__/__default__/...

**Comment by jansralf** [comment]
The underscores in the path get lost here
