### ISSUE TITLE
new release for owncloud

### ISSUE THREAD

**Issue by jyjeret** [pierre-alain-b/rainloop-nextcloud#15]
Hi, there is a new release 5.0.0 for Owncloud.
Please, could you release it for Nextcloud?
It contains some important improvements for us.
Thanks in advance

**Comment by pierre-alain-b** [comment]
Thank you for the note, I will try to spend some time on it before the end of the week.

**Comment by pierre-alain-b** [comment]
Done! It's on the nextcloud app store!
