### ISSUE TITLE
Display bug nextcloud 19 beta 5 [fixed, to be incorporated in next release presumably]

### ISSUE THREAD

**Issue by Antoine26220** [pierre-alain-b/rainloop-nextcloud#151]
Hi,

![Sans titre](https://user-images.githubusercontent.com/64309327/80277684-ff329700-86f0-11ea-9983-528f8a9286e5.jpg)

I encounter problem since update nextcloud from 19b4 to 19b5.

If you have any idea...?

My config:
ubuntu 18.04 (up to date), nginx and php 7.4 fpm)

Thanks

**Comment by Anarch157a** [comment]
I'm having the same issue. I found that if I enter the URL `https://mydomain.com/nextcloud/app/`, it does open Rainloop, as a standalone application, without the Nextcloud header at the top.

In my case, it's registering itself as the root app "/", so whenever I login, I go directly to the broken app.

**Comment by Anarch157a** [comment]
@Antoine26220 I fixed it.

in the file `/rainloop/appinfo/routes.php`, you need to change the line

    $this->create('rainloop_index', '/')

to

    $this->create('rainloop_index', '/apps/rainloop/')

**Comment by Antoine26220** [comment]
> 
> 
> @Antoine26220 I fixed it.
> 
> in the file `/rainloop/appinfo/routes.php`, you need to change the line
> 
> ```
> $this->create('rainloop_index', '/')
> ```
> 
> to
> 
> ```
> $this->create('rainloop_index', '/apps/rainloop/')
> ```

This woks great!! Thanks a lot.

**Comment by pierre-alain-b** [comment]
Excellent, thank you to both of you, I will test this for prior versions of Nextcloud and distribute a patch for the app.

**Comment by Valdnet** [comment]
@pierre-alain-b After changing the routes.php file, Rainloop works well for me.

**Comment by Antoine26220** [comment]
The bug returns witn NC 19rc2 and rainloop 6.1.4!!

I applied Anarch157a modification and everythings works again.

**Comment by pierre-alain-b** [comment]
In fact 6.1.4 is not designed to work with NC19. For NC19, for now, I recommend to stick to 6.1.2 as indicated here:
https://apps.nextcloud.com/apps/rainloop
(I'm suprised the update is proposed - I guess the release candidates are not counted as NC19)

The fix indicated above was not good for NC <19 so we reverted it for NC up to 18. For NC19, there is a work in progress to use a new version of the plugin based on the new app framework. A 7.0 version is being prepared for this.

**Comment by pierre-alain-b** [comment]
I've just released a beta 1 for 7.0.0. I am currently running some tests on a test nextcloud nc19-rc2. Do not hesitate to test as well!
