### ISSUE TITLE
Avoid "false positive" security message for Nextcloud setups

### ISSUE THREAD

**Issue by guyfromouttaspace** [pierre-alain-b/rainloop-nextcloud#153]
Currently each new installation with Rainloop comes up with a security message which is potentially a "false positive" from what I evaluated.
Please provide a fix for the Nextcloud integration addressing this issue. Thank you!
![40278916-3c80408c-5c3a-11e8-9055-50720b87a2a5](https://user-images.githubusercontent.com/64775288/81487238-26de3f00-925b-11ea-9103-3389ab547d96.png)

**Comment by pierre-alain-b** [comment]
Already discussed in another topic. I am closing this one to keep the issues vaguely ordered!
