### ISSUE TITLE
Rainloop no longer loads for me

### ISSUE THREAD

**Issue by Luticus** [pierre-alain-b/rainloop-nextcloud#155]
Just noticed an odd issue where Rainloop just sits on a grey screen.  This happens on both the client and admin pages.  As a temporary solution, I've had to revert to the Nextcloud Mail app which is woefully under powered for what I need. Hoping someone can give me an idea for a fix.  
I'm running everything, client/servers on Debian 10 Buster, using the newest firefox browser.  
Nextcloud 18.0.4 and Rainloop 6.1.0
I'm on apache 2.4.38 and using php 7.3.14

I didn't see any relevant info in the apache or nextcloud log, but I did spot something in the firefox console:
TypeError: Date.prefs is undefined

not sure if that's got anything to do with it, but it's the only clue I have.

**Comment by Luticus** [comment]
I also tried rolling rainloop back to a prior version, no change though.

**Comment by pierre-alain-b** [comment]
What do you mean by "no longer loads": it was working and stopped working? Do you remember doing anything specific that you could link to the new behavior?

**Comment by Luticus** [comment]
Yea, it loaded just fine not too long ago, but I don't use the client everyday because I also check mail through my phone and thunderbird on the desktop.  Basically now when I try to go to rainloop it goes to a grey screen and sits there indefinitely.  I thought maybe an update caused it, but I'm skeptical because I rolled back to the version before 6.1.0 and no dice.

**Comment by pierre-alain-b** [comment]
And 6.1.0 has not been updated for quite some time so it is not an update of Rainloop. Can you share a screenshot of what you see? FF 76 you said?

**Comment by Luticus** [comment]
OH, well sorry to waste your time, seems it was conflicting with the Windscribe firefox plugin.

**Comment by pierre-alain-b** [comment]
OK glad you found the solution!

**Comment by Luticus** [comment]
As soon as I turn off the vpn client it started working again, so something there is cause the problem.  Whatever the case, that's not on you guys.  Thanks for the help!  I appreciate everything you guys do!
