### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated at /var/www/nextcloud/apps/rainloop/app/rainloop/...

### ISSUE THREAD

**Issue by chrissi55** [pierre-alain-b/rainloop-nextcloud#157]
As I wrote here the errors in PHP occur also after the update to the latest rainloop version 6.1.2

My system: ubuntu server 18.04.4
Database: PostgreSQL 12.3
PHP Version: 7.4.6 
PHP memory_limit: 1024M

My logs are containing PHP errors triggered by rainloop app.

When i switch to the login mask with a user, who has no credentials saved into the additional settings page then we see the following:

[PHP] Error: Array and string offset access syntax with curly braces is deprecated at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Base/Utils.php#2143

GET /logout?requesttoken=ktpTtnG7vQgoLyHkJICcZheuL7Hc7MUdCmx34aeZLFM%3D%3Ap7Yf8xPNxHAbTE6Sc7nwI33EYv2X3upweQE9hsDIWhg%3D
from local-ip at 2020-05-15T16:29:31+02:00

and 

[PHP] Error: Array and string offset access syntax with curly braces is deprecated at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/lessphp/lessc.inc.php#3071

GET /apps/rainloop/app/?/Css/0/User/-/Default/-/0f02fb6f9897aaf90b9e885d94f38646/Hash/-/
from local-ip by oca at 2020-05-15T09:55:34+02:00

Instead of a registered user account with saved credentials:

[PHP] Error: Array and string offset access syntax with curly braces is deprecated at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Mime/Email.php#105

POST /apps/rainloop/app/?/Ajax/&q[]=/_fQukx7WW_QguG6SFzoYxxV_vMpegfUphrKKPWzIJxY8gA0bWTxfU3ZR2w-1ewT9hyHHAAansoORlprCTbgquD-aNs7uoG1pNJCXe3ckVsX8BHD16G0P8868nJv-8SIi75sZYptGLrlxkU5oX-pdU0lEjL1sHtL32ueD8K0ezXxDKKnN3mMoLHg6pAGkA2W1osw7tI62s_fVYuWc1KXHMDcBajCt9Q2LPIgrJiCbG5YWqHo62Kv-a_UqSX3FL4j_4scbtQeRnHvCLpTvXW3AO9iNeE1SWwDIhVV5RsmgneWi4xXkHtZ-OXWACL5T737l_vYdJJ5f8I-RUcpM96PKhjVEEpyCsL8ZnJ8zkFA/

The errors exist since use of PHP 7.4.x in combination with Nextcloud 18.x and rainloop app 6.x

What is possible to do, to get rid of those PHP errors ?

Also compare these posts:
https://help.nextcloud.com/t/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated-at-var-www-nextcloud-apps-rainloop-app-rainloop-v-1-14-0-app-libraries-mailso-mime-email-php-105/80860

**Comment by ghost** [comment]
I am also having this issue. Same setup, after the update /apps/rainloop/ leads to Firefox thinking its not redirecting properly, if I go to /apps/rainloop/apps/rainloop/ it works fine.

**Comment by pierre-alain-b** [comment]
The /app/rainsloop/apps/rainloop has been proposed as a fix for the app not starting in 19. I increasingly think we shall:
- use 6.1.2 for NC up to 18
- use 7.0.0 based on @nkinkade work for 19 and upwards

**Comment by pierre-alain-b** [comment]
`[PHP] Error: Array and string offset access syntax with curly braces is deprecated at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Mime/Email.php#105`
is because this wriing was deprecated starting in PHP 7.4.

This has been fixed upstream, this is great!
https://github.com/RainLoop/rainloop-webmail/commit/a250d8402544d5d3d37a0501e3e5b0854fc80bba

I will incorporate the patch from upstream.

**Comment by pierre-alain-b** [comment]
This will be corrected in 6.1.3!

**Comment by pierre-alain-b** [comment]
This should be fixed in 6.1.4 for NC18
and 7.0.0-beta-1 for NC19

**Comment by chrissi55** [comment]
Thanks for the fix. :+1:
