### ISSUE TITLE
Error saving the settings of login method to the Administrator Panel

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#159]
Steps:

1. Enter the NC administrator settings.
2. Select additional settings.
3. Set the login method for the Administrator panel for Rainloop.
4. Save settings.

An error occurs while saving settings.

![obraz](https://user-images.githubusercontent.com/47037905/82095565-92168e00-96ff-11ea-999b-a14aab1bf385.png)

App:
Nextcloud 19.0.0 RC 2
Rainloop Nextcloud 6.1.2

**Comment by pierre-alain-b** [comment]
I do not have the issue with NC 18 (not yet using 19) which is a good point for existing users. Is this a bug that only affects NC 19?

![image](https://user-images.githubusercontent.com/386857/82121575-70181c80-978e-11ea-901e-50d240010c96.png)

**Comment by Valdnet** [comment]
> Is this a bug that only affects NC 19?

Yes. NC 19 only.

**Comment by pierre-alain-b** [comment]
Thanks, and have you also the issue with @nkinkade version under NC19 (in the hope that the migration to the new app framework may have magically solved the issue)? Otherwise we will need to investigate to find how to fix.

**Comment by Valdnet** [comment]
> Thanks, and have you also the issue with @nkinkade version under NC19

There is a problem with version  @nkinkade.

**Comment by pierre-alain-b** [comment]
I have just released a beta 1 for 7.0.0. To be tested!

**Comment by pierre-alain-b** [comment]
I cannot replicate the bug in my test instance of NC19

**Comment by Valdnet** [comment]
No message is displayed in the NC19 about success of the write. Is this intentional?

**Comment by pierre-alain-b** [comment]
No it is not - I agree I do not see such a message either. However, I see that the POST request receives a 200 "successful" reply.

**Comment by nkinkade** [comment]
I was not seeing this error either in my testing with NC 19 Beta2. However, I can verify that a "Saved successfully" message is not displayed, which _is_ a bug. I will figure out what is happening and submit a new PR to fix it.

@Valdnet: When you get that error, can you tell me what log message(s) you have in `data/nextcloud.log`? When I  was working on getting the Admin and Personal settings working last week, every time I got the "Error" message when trying to save, there was always a useful message in the NC log file. I'm hoping yours will also have something helpful for us.

**Comment by nkinkade** [comment]
@pierre-alain-b: https://github.com/pierre-alain-b/rainloop-nextcloud/pull/165

**Comment by Valdnet** [comment]
@nkinkade After a correction in PR, messages in NC19 are now displayed correctly. Thanks :wink:.
Now we are waiting for merging by @pierre-alain-b.
