### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Stibila** [pierre-alain-b/rainloop-nextcloud#16]
I see new version 5.0.0 is out. Where can I find changelog?

**Comment by pierre-alain-b** [comment]
Here: https://www.rainloop.net/changelog/

The plugin basically just embeds the latest rainloop webmail app. The most important changelog is the rainloop one.
Of note, this plugin follows the version numbering of the ownCloud plugin for the sake of clarification. I do not know how the ownCloud plugin versions are numbered but I stick to them. Maybe I lack originality :-)

**Comment by pascalBokBok** [comment]
what do you mean the owncloud plugin versions?
I'm running (nextcloud) 11 and rainloop is 1.11.1.
It just seemed to me that a version 5.0.0 would contain something different than a bugfix release.
I think Stibila was wondering the same

**Comment by pierre-alain-b** [comment]
The ownCloud plugin is here: https://apps.owncloud.com/content/show.php/RainLoop+Webmail?content=165254. A couple of weeks ago, they decided to bump the version number to 5.0.0 when upgrading the plugin with Rainloop 1.11.1.

As I have been following the same rhythm as them up to now, I did the same change in the version number. I stick to their numbering as I believe the plugins are still very similar and it is good to keep some coherence between both I think. 5.0.0 does not contain any more new stuff than Rainloop jumping 1.11.1 from 1.10.x. 

Sorry if you are disappointed to see so little in this major jump in version number.

Does this clarify?

**Comment by Stibila** [comment]
No disappointment here. I just wanted to know what changed, especially when version number invoked feeling, this is some major update.
Also I like to read changelog whenever I update something :) thanks for clarification.
