### ISSUE TITLE
Update 6.1.3 not working

### ISSUE THREAD

**Issue by agentlibre** [pierre-alain-b/rainloop-nextcloud#160]
The last release (direct web-based update on NextCloud) just did not work to say the least:

![image](https://user-images.githubusercontent.com/60295112/82130928-15071980-97d0-11ea-8fd6-ea274838620a.png)

I have checked on several other accounts (some already having an active rainloop account in Nextcloud, others hadn't configure anything) within the same environment and refresh many times; always the same message and cul-de-sac.

Error started on NextCloud 18.0.3, then lasted after the update to NextCloud 18.0.4 (I tried to see whether this was related to a general update problem).

Is there a simple way to downgrade to the previous version?

Thank you for your help 😓

**Comment by Pecadis** [comment]
Having the exact same issue here.

**Comment by spreeni151** [comment]
same error here, nc 18.4.
rainloop 6.1.2 was working correctly.

**Comment by olegchensky** [comment]
the same

**Comment by skynick11** [comment]
> Error started on NextCloud 18.0.3, then lasted after the update to NextCloud 18.0.4 (I tried to see whether this was related to a general update problem).

The same with NC 17, 6.1.0 works OK.
 
> Is there a simple way to downgrade to the previous version?

Download the required version from https://apps.nextcloud.com/apps/rainloop/releases to the server, unpack, see an owner and a group of the rainloop directory in your nextcloud/apps directory (ls -l <...>), chown _youruser_._yourgroup_ rainloop (the unpacked directory), (temporary) disable Rainloop in the "apps/your apps" Nextcloud webgui menu, replace the app/rainloop directory by the unpacked one, re-enable Rainloop in the "apps/your apps" menu.

**Comment by JazMTaz** [comment]
Same for me. Newly installed Nextcloud 18.0.4 on Ubuntu 20.04, Rainloop broken after it upgraded to 6.1.3

**Comment by pierre-alain-b** [comment]
Sorry for this. 6.1.3 deleted until the fix is available.

**Comment by JazMTaz** [comment]
Reverted to 6.1.2 for now. I have used your Rainloop app for some years, and appreciate immensely all of the hard work done maintaining. Don’t misinterpret reported issues as negative, you have a great app with superior feature set.

**Comment by pierre-alain-b** [comment]
No worries.
By the way, I found the culprit. Re-releasing a fixed 6.1.3. Sorry again for the disruption!

**Comment by pierre-alain-b** [comment]
6.1.4 is released. I decided to label it 6.1.4 (and not 6.1.3 again) to ease the corrective update for those stucked with 6.1.3. It shall be available soon in the Apps update menu. Let me know if this fixes the issue.

**Comment by pierre-alain-b** [comment]
I've just received the update on one of my instances. Error gone for me. Could you confirm by any chance?

**Comment by olegchensky** [comment]
6.1.4 works. Thankss!

**Comment by agentlibre** [comment]
Solved, it worked for me! Mistakes happen so many thanks for having promptly taken responsibility on it! Much appreciated. 🥰

**Comment by pierre-alain-b** [comment]
Thank your for the feedback (and the initial report of the issue!). Have all a great day.
