### ISSUE TITLE
About program

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#162]
In the "About" program, the Rainloop version should match the Rainloop version from NC. Currently, this is confusing to the user.
Also the date should change automatically so that it is still current.

![obraz](https://user-images.githubusercontent.com/47037905/82141852-c8a3f400-9838-11ea-9a11-1c3c5459b1b9.png)

**Comment by pierre-alain-b** [comment]
In fact this is the version of Rainloop, and not he version of the plugin. i assume that for end-users this is not an issue. I would rather not change this because we already have too many changes from Rainloop upstream :-)
