### ISSUE TITLE
Personal settings submits form twice to /ajax/personal.php

### ISSUE THREAD

**Issue by nkinkade** [pierre-alain-b/rainloop-nextcloud#166]
This is mostly a note for myself to fix, but if someone else can figure out quickly any help would be appreciated. While I was [debugging why messages were not being displayed to users](https://github.com/pierre-alain-b/rainloop-nextcloud/pull/165) when clicking "Save" in Admin and Personal settings I observed that the browser was making a duplicate request to `/ajax/personal.php` after clicking "Save". The issue is benign, because the duplicate request is effectively a no-op, but it should probably be resolved anyway.

**Comment by pierre-alain-b** [comment]
Could be because the JS scripts personal.js and rainloop.js are loaded twice.

**Comment by pierre-alain-b** [comment]
In fact it seems the full page is repeated twice for personal settings...

**Comment by pierre-alain-b** [comment]
Can you review my commit and tell me if it seems to indeed correct the issue in a proper way?

**Comment by nkinkade** [comment]
@pierre-alain-b: I don't think that was quite the right solution, or at least maybe not the best one. Turns out the solution was just adding a blank fourth argument to `TemplateResponse`:

https://github.com/pierre-alain-b/rainloop-nextcloud/pull/171
