### ISSUE TITLE
"application.ini" not present in Nextcloud installation

### ISSUE THREAD

**Issue by frederikdyrmose** [pierre-alain-b/rainloop-nextcloud#17]
## Problem description
I have forgotten the Rainloop admin password, due me having a corrupt password file, so I could read online that in the file application.ini I should be able to reset the password. On the page here on GitHub there stands that the file application.ini should be present at /path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini, however, the folder /path/to/nextcloud/data/rainloop-storage isn't present in my installation. What should I do to reset the admin password?

## What I've tried
I have tried searching for the application.ini file with `find . -name "*.ini"`, however, no application.ini is present in my whole Nextcloud installation. I only have the following .ini files:
```
./apps/rainloop/app/rainloop/v/1.11.1/app/domains/qq.com.ini
./apps/rainloop/app/rainloop/v/1.11.1/app/domains/yahoo.com.ini
./apps/rainloop/app/rainloop/v/1.11.1/app/domains/gmail.com.ini
```

I have also tried seaching for a place where the admin_password is given with 
`grep -rnw '/var/www/nextcloud/' -e 'admin_password'`, however, it,  says that the password is '12345', which is incorrect, when I try to login with admin and 12345. I got the following results:
```
/var/www/nextcloud/apps/rainloop/app/rainloop/v/1.11.1/app/libraries/RainLoop/Config/Application.php:102:	return $this->Set('security', 'admin_password', \md5(APP_SALT.$sPassword.APP_SALT));
/var/www/nextcloud/apps/rainloop/app/rainloop/v/1.11.1/app/libraries/RainLoop/Config/Application.php:113:	$sConfigPassword = (string) $this->Get('security', 'admin_password', '');
/var/www/nextcloud/apps/rainloop/app/rainloop/v/1.11.1/app/libraries/RainLoop/Config/Application.php:206:	'admin_password'			=> array('12345'),
```

## Help
I don't know what more to try or any solution to the problem, so any help would be greatly appreciated.

**Comment by pierre-alain-b** [comment]
Where is your nextcloud data stored?
In /var/www/nextcloud/data? If yes, do you have this folder "/var/www/nextcloud/data/rainloop-storage/data/default/configs/" and what is in it?

**Comment by frederikdyrmose** [comment]
Thank you for the reply.

Sorry for all of this. I use YunoHost and when I looked in the config I see that the data storage is placed another place, namely `/home/yunohost.app/nextcloud/data/rainloop-storage`. So now I can see the config.

Thank you for the help.
