### ISSUE TITLE
Change tab title and favicon when there is unread messages on the inbox.

### ISSUE THREAD

**Issue by rodrigoaguilera** [pierre-alain-b/rainloop-nextcloud#18]
Great piece of software!

I transitioned from hosting rainloop alone to do it inside nextcloud 12 but I miss the little notification on the browser tab.

I tried the nextcloud mail app and I've seen it has this.
Can that easily copied from there to the rainloop app?

**Comment by pierre-alain-b** [comment]
Hi, for my understanding, does the notification work with the standalone version of Rainloop?

**Comment by rodrigoaguilera** [comment]
Yes. You can see it in the demo https://mail.rainloop.net/

**Comment by hooger** [comment]
Hi,
is there any advancement with this feature? Is it on the roadmap?
Thank you in advance!

**Comment by nkinkade** [comment]
@pierre-alain-b: https://github.com/pierre-alain-b/rainloop-nextcloud/pull/175

I believe that PR  should resolve this issue. It was something I've wanted for a long time too.

**Comment by pierre-alain-b** [comment]
Thank you! Merged!
