### ISSUE TITLE
Adding rainloop-nextcloud to Nextcloud project at Transifex

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#180]
It is possible for translations from Rainloop to be sent to Nextcloud project at Transifex. This would allow translating the module for Nextcloud in many languages. There are preliminary arrangements with @rakekniven, which may allow you to add a project to Transifex.

@pierre-alain-b  can you agree to this and implement it on Githab?

**Comment by pierre-alain-b** [comment]
Dear @Valdnet and @rakekniven, I do not object to this and if this can ease the translation process, happy to do so. How should it be done?

**Comment by Valdnet** [comment]
@pierre-alain-b  I wrote a message to @rakekniven . We look forward to his instructions 😉.

**Comment by rakekniven** [comment]
Issue title is not precise. "Adding rainloop-nextcloud to Nextcloud project at Transifex" would be better.

**Comment by Valdnet** [comment]
@rakekniven You're right. Changed 😉.

**Comment by rakekniven** [comment]
See https://github.com/nextcloud/docker-ci/pull/219 as well

**Comment by Valdnet** [comment]
@rakekniven Thanks a lot 👍.

**Comment by Valdnet** [comment]
The translations have not yet appeared in Transifex, because we are still waiting for confirmation of PR by @MorrisJobke.

**Comment by MorrisJobke** [comment]
Should be there within the next minutes :)

**Comment by MorrisJobke** [comment]
just add an empty file `l10n/.gitkeep` and then the job doesn't produce false errors on our side (that reduces a bit the checks on our side as well). Otherwise it should work :)

**Comment by rakekniven** [comment]
@pierre-alain-b Added another PR. See #190

**Comment by MorrisJobke** [comment]
There it is: https://www.transifex.com/nextcloud/nextcloud/translate/#de/rainloop

**Comment by Valdnet** [comment]
@MorrisJobke @rakekniven Thanks a lot 😉.

**Comment by rakekniven** [comment]
@MorrisJobke 
The way GitHub -> TX is working.
When will the translations from TX appear on GitHub?
One sync a day? Or event based?

**Comment by Valdnet** [comment]
@rakekniven How to make these translations appear in Transifex?

https://github.com/pierre-alain-b/rainloop-nextcloud/blob/72d765a0af4c02883ea59021b36d9a48a9a8e026/rainloop/ajax/admin.php#L31-L36

They are not automatically downloaded because the translated text is replaced here:

https://github.com/pierre-alain-b/rainloop-nextcloud/blob/2e09457bdedb5fbd3b081ed74456ed3b1653e118/rainloop/js/rainloop.js#L87

Is it possible to add them manually to Transifex, or should they be changed in the code, which I would not want.

**Comment by rakekniven** [comment]
Manually adding is not possible, you have to adapt the code.

**Comment by Valdnet** [comment]
@rakekniven One more question 😉. The following words appeared in the translation:

- string
- size
- fore

which should not be.
This should also be corrected in the code?

**Comment by rakekniven** [comment]
Have seen them. You know the location inside the source of e. g. "fore".
Cannot find it with integrated source.

**Comment by Valdnet** [comment]
> You know the location inside the source of e. g. "fore".

In the file: `rainloop/app/rainloop/v/1.14.0/static/ckeditor/ckeditor.js`
In line: 724

I wonder why these values are being downloaded.

**Comment by Valdnet** [comment]
@pierre-alain-b These translations should not appear in Transifex:
- string
- fore
- family
- size
- filters
- concat
- subtract
- hashtag
- phone
- mention
- url 
- back
- error
- :
- add
- email

**Comment by rakekniven** [comment]
@pierre-alain-b Added another PR. See #191
We need to get rid of that unwanted strings.

**Comment by MorrisJobke** [comment]
> One sync a day? Or event based?

Once a day. And only if the nextcloud-bot can push to master, but I will ping you if there is more to do from your side.

**Comment by MorrisJobke** [comment]
I just noticed that you have a subdirectory for the app itself. That means the translation sync tool just doesn't find the correct folders, because it expects the `l10n` folder in the root - as well as the `appinfo` one. Is there a reason to put it in the subfolder? Because you could also remove the screenshots during build and don't have any problems then.

**Comment by pierre-alain-b** [comment]
There is no specific reason to have the app in a subfolder (except not to package the screenshots and README.md when packaging the app), and this can definitely be changed if it eases the overall process of localization.

**Comment by MorrisJobke** [comment]
> There is no specific reason to have the app in a subfolder (except no to package the screenshots and README.md when packaging the app), and this can definitely be changed if it eases the overall process of localization.

Yep - then I don't need to adjust the already quite complex transifex sync to your app. That would make my life easier :)

**Comment by pierre-alain-b** [comment]
> That would make my life easier :)

That's already a good reason. I will do so tomorrow!

**Comment by pierre-alain-b** [comment]
Done !

**Comment by MorrisJobke** [comment]
@pierre-alain-b Mind to add @nextcloud-bot as collaborator to this repository? Then the bot can push directly

**Comment by pierre-alain-b** [comment]
Done!

**Comment by MorrisJobke** [comment]
https://github.com/pierre-alain-b/rainloop-nextcloud/commit/2f00835862e8056eb8146659c1731a0d6a496107

**Comment by pierre-alain-b** [comment]
That's a lot of languages!! Thanks!

**Comment by Valdnet** [comment]
> That's a lot of languages!!

This is the power of Nextcloud in Transefix :sunglasses:.

**Comment by rakekniven** [comment]
That is the power of the Nextcloud translation community :-)

**Comment by rakekniven** [comment]
@MorrisJobke Are there any docs about the steps we did to hook in rainloop?
Otherwise I would write down some notes.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Are there any docs about the steps we did to hook in rainloop?
> Otherwise I would write down some notes.

Yep - already exists: https://docs.nextcloud.com/server/18/developer_manual/app/view/l10n.html#setup-of-the-transifex-sync

Feel free to proof read it.

**Comment by rakekniven** [comment]
Or dear, I could have used the document instead of trying to figure it all out :-) 

Will read it once more and add a section regarding `.l10nignore`.

**Comment by MorrisJobke** [comment]
> Will read it once more and add a section regarding ".l10nignore".

And maybe one with the `l10n/.gitkeep`

**Comment by rakekniven** [comment]
> And maybe one with the l10n/.gitkeep

It is there already :-)

**Comment by Valdnet** [comment]
@MorrisJobke @rakekniven Nextcloud-bot works fine. Translations arrive😎. Thanks again for your support 😉.
