### ISSUE TITLE
Additional administration panel with default login data accessible

### ISSUE THREAD

**Issue by Bloodsoul** [pierre-alain-b/rainloop-nextcloud#19]
Since there is a default RainLoop data directory present, it is possible to access another RainLoop administration panel with default credentials, when "index.php" is removed from the URL.

**Comment by pierre-alain-b** [comment]
Hi,
Can you precise the URL that you use to access this admin panel and precise why you think this is a bug?
I have not been able to replicate on my side by just calling the URL without the index.php
PAB

**Comment by Bloodsoul** [comment]
Given that the admin panel is available via https://address.tld/index.php/apps/rainloop/app/?admin
Another admin panel would be accessible via https://address.tld/apps/rainloop/app/?admin with its own configuration located in /nextcloud_path/apps/rainloop/data instead of /nextcloud_path/data/rainloop-storage

This empowers others to use this installation of RainLoop with their own configuration.

**Comment by pierre-alain-b** [comment]
I am still not sure I understand correctly.
Is this a feature request?
Or a bug that you see? (I cannot replicate, which is normal if in fact you propose a feature request)

**Comment by Bloodsoul** [comment]
It is an issue, not a feature request. I assume this could also be avoided by specific web server configuration. I'm using Apache 2.4 with allowed override using .htaccess
Maybe this does not apply with nginx or other.

**Comment by wallenium** [comment]
1. use the link in the admin area: https://address.tld/index.php/apps/rainloop/app/?admin

2. log in and use Admin:12345, change password. Test using 12345, is not working. The new password works fine

3. now remove index.php out of the URL: https://address.tld/apps/rainloop/app/?admin

4. you are able to log in with admin:12345 again, remember you changed the password in step 2

Hope it is now clearer ;)

**Comment by pierre-alain-b** [comment]
Thank you, I can now replicate.

**Comment by pierre-alain-b** [comment]
A quick fix is to make the folder `/nextcloud_path/apps/rainloop/app`non writable by the user executing the web server.
As I am myself not the author of the original routing of the plugin, I will need a little more time to go deeper and fix more thoroughly the issue. Any ideas welcome!

**Comment by pierre-alain-b** [comment]
Dear All,

Because of the lack of time and as I was never the developer of Rainloop or of this plugin, I have decided to cease maintaining the plugin.
I cannot guarantee the security of the plugin and I cannot update it to work with NC 14 that is coming.

If one of you is willing to fork the project and take the lead, I will assist the best I can.

Best regards
Pierre-Alain

**Comment by pierre-alain-b** [comment]
I think this is fixed in v7
