### ISSUE TITLE
Loss of pior data after upgrade to v7.0 with NC19

### ISSUE THREAD

**Issue by Luticus** [pierre-alain-b/rainloop-nextcloud#199]
Since I upgraded to Nextcloud 19, when users click on rainloop it no longer authenticates.  When users enter their password manually it still doesn't authenticate.

In my nextcloud log I see this item on login attempt:  "message":"preg_replace(): Delimiter must not be alphanumeric or backslash at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Utils.php#568"

**Comment by Tsunami2056** [comment]
Having the exact same issue on my NC 19 instance.

**Comment by pierre-alain-b** [comment]
Do you have domain settings still available in the admin settings?

**Comment by pierre-alain-b** [comment]
@nkinkade  it makes me think of the strange behavior we had a couple of times with data loss when uograding to the app with the new framework.

**Comment by Luticus** [comment]
If you're referring to the rainloop admin panel, I can't seem to authenticate there either.

**Comment by nextgen-networks** [comment]
> @nkinkade it makes me think of the strange behavior we had a couple of times with data loss when uograding to the app with the new framework.

I had the auth and data/config loss also as i upgraded my nc18.04 to nc19.00.

Solution for the auth problem was deleting the saved password in admin section, press "save" and re-enter the admin password and press save.

Neverthless the config of all users was gone and every alias, contact connection as well as additional account had to be configured again :-/

**Comment by pierre-alain-b** [comment]
OK damn, this is serious.

**Comment by pierre-alain-b** [comment]
If you have a backup, you can certainly put back the rainloop-storage folder which is:
`/path/to/nextcloud/data/rainloop-storage/_data_/_default_/` but this is a bad solution

**Comment by pierre-alain-b** [comment]
I am investigating what could provoke this. We have not touched directly Rainloop mechanism in charge of creating the data folder but I suspect something changed with the new framework and that provoked a re-init of the data folder.

**Comment by nextgen-networks** [comment]
@pierre-alain-b I thought it was intentional ... ;-)
... because of the changes the password is stored used since v7.0.0

**Comment by pierre-alain-b** [comment]
I suspect everything happens in this file: https://github.com/pierre-alain-b/rainloop-nextcloud/blob/2eb6fb4fe96e9be6be87a11fb6e5d789a2c60faa/app/rainloop/v/1.14.0/include.php#L143
This is where the data folders are created when rainloop initializes for the first time.

**Comment by pierre-alain-b** [comment]
> @pierre-alain-b I thought it was intentional ... ;-)
> ... because of the changes the password is stored used since v7.0.0

Well no it is not intentional. The change of the way the password is stored shall not erase the existing config of the domains and the stuff like that...

**Comment by Luticus** [comment]
So you think the rainloop configs were either not being read in or are removed somehow?

**Comment by pierre-alain-b** [comment]
This is my assumption but I do not understand why...

**Comment by RobinR1** [comment]
I seem to have the same problem. user authentication no longer works, so no user can currently log in and also authentication as admin on the admin panel does not work. I see the same errors in the nextcloud log as reported by Luticus.

When I check `nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini` or `nextcloud/data/rainloop-storage/_data_/_default_/storage/cfg/*` all config files look ok to me and have modification dates from before the upgrade.. So it does not look to me as if configurations are removed.

**Comment by Luticus** [comment]
Is there an easy way to reinitialize rainloop then? It might not be the best solution but the emails are all stored on the email server itself, so it's not a total loss.

**Comment by pierre-alain-b** [comment]
Well in this situation it is like if Rainloop is already reinitialized - just reconnect to the admin panel with the default login/password and you can re-configure what needs to be reconfigured.

**Comment by pierre-alain-b** [comment]
> In my nextcloud log I see this item on login attempt: "message":"preg_replace(): Delimiter must not be alphanumeric or backslash at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Utils.php#568"

This does not seem to be related to the current issue. This is for routing inside Rainloop:
```
$sAppPath = \OC::$server->getURLGenerator()->linkToRoute('rainloop.page.appGet');
			// TODO: Fix this ugly hack. Is there a "modern" way to return
			// a URL that doesn't include index.php, which breaks things?
			$sAppPath = preg_replace('index\.php\/', '', $sAppPath);
```

**Comment by pierre-alain-b** [comment]
> When I check `nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini` or `nextcloud/data/rainloop-storage/_data_/_default_/storage/cfg/*` all config files look ok to me and have modification dates from before the upgrade.. So it does not look to me as if configurations are removed.

@RobinR1 This is really interesting. Do you see any other folder that would look like another rainloop config? Maybe you could test where you can find INSTALLED files (Rainloop creates an INSTALLED file with the Rainloop version number):

```
cd /path/to/nextcloud/data
find . -name "INSTALLED"
```

**Comment by pierre-alain-b** [comment]
oh, I think I see something strange on my test instance: would it be possible that with the new version, the config folder was moved to /path/to/nextcloud/apps/rainloop/app/data/_data_/_default_ ?

**Comment by pierre-alain-b** [comment]
OK I think i have a start of a likely explanation.

Rainloop for nextcloud shall define a custom path to store the data folder:

```
	public static function regRainLoopDataFunction()
	{
		if (!@function_exists('__get_custom_data_full_path'))
		{
			$_ENV['RAINLOOP_OWNCLOUD'] = true;

			function __get_custom_data_full_path()
			{
				$sData = rtrim(trim(OC::$server->getSystemConfig()->getValue('datadirectory', '')), '\\/').'/';
				return @is_dir($sData) ? $sData.'rainloop-storage' : '';
			}
		}
	}
```

and this function is called by Rainloop when initializing to choose where to put the data folder:

```
			$sCustomDataPath = function_exists('__get_custom_data_full_path') ? rtrim(trim(__get_custom_data_full_path()), '\\/') : $sCustomDataPath;
			define('APP_DATA_FOLDER_PATH', 0 === strlen($sCustomDataPath) ? APP_INDEX_ROOT_PATH.'data/' : $sCustomDataPath.'/');
```

If somehow the custom path is not set, then it reverts to the classical behavior which is to set up the application in the application folder and *not* the data folder of Nextcloud.

**Comment by pierre-alain-b** [comment]
OK I understood that the function was never appropriately executed. I have made a quick hack to correct this but we will have to find a more beautiful way, @nkinkade if you can help me I will greatly appreciate.

**Comment by pierre-alain-b** [comment]
7.0.1 has been published - can you check if tthis works as expected now?

**Comment by RobinR1** [comment]
All seems to work as expected again now!

**Comment by pierre-alain-b** [comment]
Thank you for reporting after test! This is reassuring! And I am glad we apparently fixed this for all future users that will migrate to NC 19 !

**Comment by pierre-alain-b** [comment]
> In my nextcloud log I see this item on login attempt: "message":"preg_replace(): Delimiter must not be alphanumeric or backslash at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Utils.php#568"

By the way, I also fixed the syntax that caused this warning to appear.

**Comment by Luticus** [comment]
Yea, that fixed it and in my case my Rainloop didn't need to be reinitialized. Only thing I can't seem to get right now is the auto login capability. I can log in manually though.

**Comment by pierre-alain-b** [comment]
@Luticus OK excellent!
The auto-login is supposed to work as it did in the past (and even better we hope). What do you want to do that you cannot achieve?

**Comment by Luticus** [comment]
Well, when i click the rainloop icon in nextcloud it is supposed to just log in, instead i'm greeting with the login page and am prompted for a password again. I'll try a few things and see if i can get it to work, but so far, no dice.

**Comment by Luticus** [comment]
Ok, it seems I just needed to log out of nextcloud and log back in. I think it's ok now.

**Comment by RobinR1** [comment]
> 
> By the way, I also fixed the syntax that caused this warning to appear.

those errors indeed also seem to be gone! Good job! Thanks!

**Comment by nextgen-networks** [comment]
Hey @pierre-alain-b
Fanastic! All settings are restored by magic™ :-)
Thanks to you and all involved! This was pretty fast!

**Comment by Luticus** [comment]
Yes, thank you very much.  I'd be sad without my Rainloop. :)

**Comment by nkinkade** [comment]
@pierre-alain-b: I'm sorry for this very late reply. I often don't even turn on my computer on the weekends. I'm just now seeing this full thread. I'm glad you quickly found a workaround. Just looking at the code, I suspect a more elegant fix would be to add a line like:

```
$app->registerCustomDataPath();
```

... to the file `appinfo/app.php`. And then to create a new function like the following in `lib/AppInfo/Application.php`:

```
        public function registerCustomDataPath() {
                RainLoopHelper::regRainLoopDataFunction();
        }
```

I haven't tested this and am just making this up on-the-fly as I look over the code.

I'll try to give this a test today and submit a PR. Is there anything else I'm missing from this issue that needs addressing?

**Comment by pierre-alain-b** [comment]
Thanks @nkinkade, yes I had to make this ugly fix but I was in a hurry to find a solution and I also didn't want the bug to ruin my week-end :-) so I settled for the quick and dirty hack waiting for good ideas from you :-) If you find a few minutes to test, and submit a PR, I will test as well and ship a cleaner 7.0.2 :-)

**Comment by nkinkade** [comment]
Looking at this more closely, I don't think my proposed solution above will work. Indeed, the new App Framework code was *trying* to register that function:

https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Controller/PageController.php#L72

... but it was not working. I suspect that this may have something to do with the fact that [everything](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Controller/PageController.php#L3) is [namespaced](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Util/RainLoopHelper.php#L3), but that the RainLoop code is expecting to find the function `__get_custom_data_full_path()` in the global namespace. Moving the function declaration to index.php may be working because that PHP file does not declare any sort of namespace, thus declaring it in the global namespace where RainLoop can find it.

It may be that the solution you implemented is the only one possible short of modifying the RainLoop code in some way. :/
