### ISSUE TITLE
Default Authentication Not Working - Nextcloud 12

### ISSUE THREAD

**Issue by xcellardoor** [pierre-alain-b/rainloop-nextcloud#20]
Thanks very much for making what looks like (from the Try Me on your website) an excellent IMAP frontend.

My only problem is that after installing the RainLoop Nextcloud Plugin, I try to login with 'admin' and '12345' as explained in the App's description, but the authentication always fails.

I've had a Google-around but nothing is coming up, everything says admin:12345 which is what I am using, shown below (although it doesn't reveal anything...)

![image](https://user-images.githubusercontent.com/3308601/27540009-82b7ecb0-5a76-11e7-8b31-72f95f4c9ea0.png)

Many thanks in advance!

**Comment by pierre-alain-b** [comment]
This seems to be an instance-specific issue unfortunately. Are you sure Rainloop was not installed in the past and you have former configuration files in place that would prevent the correct login? On a new and fresh install, the admin user:password is admin:12345.

**Comment by pierre-alain-b** [comment]
Please double check the password, just in case...

**Comment by xcellardoor** [comment]
Ta, do you know where does the config file usually lives in the Nextcloud plugin deployment?

**Comment by pierre-alain-b** [comment]
Normally the config is in
/path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs

**Comment by xcellardoor** [comment]
Found the data, wiped it and all good! I must have installed it some time in the past and forgotten about it :| sorry!

**Comment by pierre-alain-b** [comment]
Excellent!

**Comment by NodokaMurmevent** [comment]
i have the same problem with nextcloud 11, erase application.ini don't help me, it's a fresh install.

edit : try to change in config to test/test. not work

**Comment by pierre-alain-b** [comment]
Hi, can you give more details on the steps you did?
Are you sure you are trying to use the admin login for the admin page and not the webmail page?

**Comment by NodokaMurmevent** [comment]
... ok problem resolve i have clean opcache, restart apache and php7.0-fpm, clean browser cache + cookie. sorry for the false problem.

**Comment by JimmyKater** [comment]
errr...
as i am still a beginner with all of this i can't follow all advices here.
i am running raincloud as an app (5.0.1) in nextcloud (12.0.2). apparently i have installed it sometime earlier, once and set a password there (for admin user) which i completely forgot about.
so now i try to login with admin:12345 (as it ist still set in application.ini) but that doesn't work. "authentification wrong".
what do i need to do to (more or less step by step) to be able to log in...

sorry for asking these newbie questions as for all others it seem to be clear what to do from the hints above :(

**Comment by JimmyKater** [comment]
using https://mydomain.tld/index.php/apps/rainloop/app/?admin did the trick! 
i changed it directly in the browser and then could enter the default-password
