### ISSUE TITLE
Blank Screen with NC 19.0 and Rainloop 7.0.1

### ISSUE THREAD

**Issue by Pecadis** [pierre-alain-b/rainloop-nextcloud#201]
Hi Alain,

first, i would like to thank you for your work. I am using Rainloop since Years and really appreciate your doing.
I have lately upgraded to 19.0 by accident and have seen that Rainloop just started showing a blank Screen when opening the App. Do you have an idea where this could come from?

I have seen that the Browser Console is refusing to execute some scripts because the Mime Type doesn't match.

![image](https://user-images.githubusercontent.com/5543829/83984667-8e5cdc80-a936-11ea-9f25-d49a7d08ab70.png)

However, even if i disable the header "X-Content-Type-Options" in nginx, it still doesn't work.
The Logs in RL itself seems to be fine and connecting to the Mailserver Properly as it should.

How can i support you to solve this issue?

Best Regards

**Comment by pierre-alain-b** [comment]
Which browser are you using?
Could you share a screenshot of what you see with Rainloop?
i understand that you say that you say that despite not being visible Rainloop is connecting appropriately to the mail server, right?

**Comment by twieskot** [comment]
The same for me, im using Firefox 77.0.1 (64-bit)

![failure](https://user-images.githubusercontent.com/33521600/84003697-b9f9ba00-a96a-11ea-9065-66d7f3a72e22.jpg)

**Comment by Pecadis** [comment]
I am using the Brave Browser(V1.9.76) but have also checked it with Firefox (77.0.1 (64-Bit) ) and Chrome (83.0.4103.97)

I am basically just seeing the following:
![image](https://user-images.githubusercontent.com/5543829/84004440-d9451700-a96b-11ea-8daf-79bce5911a6f.png)

and yes, Rainloop seems to connect to the Mailserver in the Background (seen in the Logs) but is not displaying it in the Browser.

**Comment by fracarvic** [comment]
Same here. Tested with latest versions of Edge Chromium and Firefox.

Problem since upgrade to Nextcloud 19. I'm using official nextcloud docker image.

**Comment by nextgen-networks** [comment]
@fracarvic 
I've tested it couple of moments ago on my installed Edge (Chrome base 83.0.478.45) and Rainloop works without a hassle.
Very strange.
... do you have any extension installed and advanced/custom rules applied (uBlock Origin, ...)?

**Comment by twieskot** [comment]
uBlock origin (but disabling it doesn't have any effect)

**Comment by pierre-alain-b** [comment]
No issue here with ublock and FF 77d 64 bits. No warning either. Are you all serving Nextcloud with Nginx?

**Comment by Pecadis** [comment]
Yes, i am using nginx.

________________________________
Von: Pierre-Alain Bandinelli <notifications@github.com>
Gesendet: Montag, 8. Juni 2020 13:07
An: pierre-alain-b/rainloop-nextcloud
Cc: Pecadis; Author
Betreff: Re: [pierre-alain-b/rainloop-nextcloud] Blank Screen with NC 19.0 and Rainloop 7.0.1 (#201) 

No issue here with ublock and FF 77d 64 bits. No warning either. Are you all serving Nextcloud with Nginx?

**Comment by pierre-alain-b** [comment]
Can you check the MIME type of the file polyfill.js returned by the server?
![image](https://user-images.githubusercontent.com/386857/84024035-6d71a700-a989-11ea-8b86-2d97326e0314.png)

**Comment by pierre-alain-b** [comment]
Anything special in your nginx config? Any change in the MIME type of some files?

**Comment by pierre-alain-b** [comment]
Also can you check if mime.types get loaded properly (check nginx logs) or if you get configuration errors (nginx -t)?

**Comment by Pecadis** [comment]
Polyfills list listed as text/html

nginx conf is working fine:
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

I am using the default Nextcloud configuration. This is the Block which should affect the it

```
 # Adding the cache control header for js and css files
 # Make sure it is BELOW the PHP block
 location ~ \.(?:css|js|woff|svg|gif)$ {
   try_files $uri /index.php$uri$is_args$args;
   add_header Cache-Control "public, max-age=15778463";
   # Add headers to serve security related headers (It is intended to
   # have those duplicated to the ones above)
   # Before enabling Strict-Transport-Security headers please read into
   # this topic first.
   # add_header Strict-Transport-Security "max-age=15768000;           
   #  includeSubDomains; preload;";
   #
   # WARNING: Only add the preload option once you read about          
   # the consequences in https://hstspreload.org/. This option
   # will add the domain to a hardcoded list that is shipped
   # in all major browsers and getting removed from this list
   # could take several months.
   add_header X-Content-Type-Options nosniff;
   add_header X-XSS-Protection "1; mode=block";
   add_header X-Robots-Tag none;
   add_header X-Download-Options noopen;
   add_header X-Permitted-Cross-Domain-Policies none;
   # Optional: Don't log access to assets
   access_log off;
}

```

**Comment by fracarvic** [comment]
I'm using apache (with official nextcloud docker image) with default configuration, behind a nginx proxy (nginx-ingress, i'm using kubernetes) only with this config:

```
nginx.ingress.kubernetes.io/proxy-body-size: 512m 
nginx.ingress.kubernetes.io/configuration-snippet: |
  rewrite ^/.well-known/carddav https://$host/remote.php/dav/ redirect;
  rewrite ^/.well-known/caldav https://$host/remote.php/dav/ redirect;
  location /apps/rainloop/app/data { deny all; } 

```
Working perfectly with nextcloud 18 official docker image.

**Comment by fracarvic** [comment]
I'm not using any extensions on browser. Tested on my mobile (chrome for android) and same problem, white screen.

**Comment by pierre-alain-b** [comment]
OK so I think it is quite clear that the issue comes from the hosting. I have the feeling that all people impacted have the Nexctloud 19 official docker image. Correct?

**Comment by Pecadis** [comment]
Nope, i am not hosting it with docker. I am using php7.3 and nginx the traditional way.

**Comment by pierre-alain-b** [comment]
OK so maybe Nginx is the smallest common factor here...

**Comment by Pecadis** [comment]
That seems to be strange. What has been changed before with nc 18.x and now?

**Comment by twieskot** [comment]
i'm also working on a installation with docker+nginx

**Comment by samsalway** [comment]
docker + traefik, experiencing same problem, same browser logs about script mime type.

**Comment by twieskot** [comment]
> 
> 
> Can you check the MIME type of the file polyfill.js returned by the server?
> ![image](https://user-images.githubusercontent.com/386857/84024035-6d71a700-a989-11ea-8b86-2d97326e0314.png)

![image](https://user-images.githubusercontent.com/33521600/84141573-ac6c2f00-aa53-11ea-96d4-04e347257835.png)

**Comment by pierre-alain-b** [comment]
So we need to understand why the server Nginx is sending this weird mime/type for js files! Do you have anything around mime types in your respective Nginx configs?

**Comment by Pecadis** [comment]
Looking around, there is nothing else than i have already posted in regards to nginx and mime type. Even in the default /etc/nginx/mime.types File, the JS files are referenced correctly

```
types {
    text/html                                        html htm shtml;
    text/css                                         css;
    text/xml                                         xml;
    image/gif                                        gif;
    image/jpeg                                       jpeg jpg;
    application/javascript                           js;
    application/atom+xml                             atom;
    application/rss+xml                              rss;
```

**Comment by pierre-alain-b** [comment]
and yet the server is serving them as text/html...

**Comment by fracarvic** [comment]
I think the key here is the response code 302, a temporary redirection.

polifills.min.js returns a 302 redirection to /apps/files, and this response seems generated by nextcloud php, not apache or nginx.

More info, I'm using SSO with keycloak SAML.

**Comment by pierre-alain-b** [comment]
Indeed this is strange - we have something to follow!
Can you look at the detailed reponse of the packet and share what you see?
Clealry app/files shall be text/html so if there is a redirect by nextcoud to app/files then it is normal that this fails...

**Comment by pierre-alain-b** [comment]
Has anyone a public isntance where I could test the behavior as I cannot replicate it on my test and production instances?

**Comment by fracarvic** [comment]
ok, i think i find the problem. 

I have two app folders, one for included apps and anoother for custom apps. In config.php:

```
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
```

Rainloop is installed in custom_apps and if I move to apps rainloop starts working perfectly.

**Comment by fracarvic** [comment]
Seems there are a confusion in paths, 
rainloop.js is loaded from custom_apps and is loading ok

https://xxxxxxx/custom_apps/rainloop/js/rainloop.js?v=680146ec-0

but polifill is requested in apps

https://XXXXX/apps/rainloop/app/rainloop/v/1.14.0/static/js/min/polyfills.min.js?community

and return 302 to default app (files) like any unexisting URL.

but if i try to load polifill from custom_apps is returned correctly

https://XXXX/custom_apps/rainloop/app/rainloop/v/1.14.0/static/js/min/polyfills.min.js?community

**Comment by pierre-alain-b** [comment]
It's because Rainloop app was not aware it could be installed in a custom apps folder! Could this be an explanation for all those impacted?

**Comment by pierre-alain-b** [comment]
@twieskot @Pecadis are you in a similar situation?

**Comment by Pecadis** [comment]
@pierre-alain-b indeed, i am using rainloop in a custom apps folder.
i am trying to replicate that on a different machine currently.

**Comment by waltherjj** [comment]
> @twieskot @Pecadis are you in a similar situation?

hi, just wanted to chime in on this: i experience the same problem and i'm using rainloop in a custom apps folder as well. it seems to me that all assets using the `staticPath` function in `RainLoop/Service` are not served correctly. That function traces to function `WebPath` in RainLoop/Utils which seems to hardcode the app path. Sadly i'm not familiar enough with the code base to propose a fix on the right level. Hope this helps a bit either way!

**Comment by pierre-alain-b** [comment]
I confirm I was not aware apps could be installed in custom folders - so indeed the path is currently hardcoded. We will try to fix this.

**Comment by twieskot** [comment]
> 
> 
> > @twieskot @Pecadis are you in a similar situation?
> 
> hi, just wanted to chime in on this: i experience the same problem and i'm using rainloop in a custom apps folder as well. it seems to me that all assets using the `staticPath` function in `RainLoop/Service` are not served correctly. That function traces to function `WebPath` in RainLoop/Utils which seems to hardcode the app path. Sadly i'm not familiar enough with the code base to propose a fix on the right level. Hope this helps a bit either way!

no, rainloop is in the default apps folder here:
https://XXXXXXXXXXXXXX/apps/rainloop/

**Comment by Pecadis** [comment]
@twieskot just to be sure that we are on the same page and avoid misunderstandings. We are not talking about what is being displayed on the Browser like https://domain.example/apps/rainloop/ but rather how it has been setup in the config.php.

My relevant section here is this where Rainloop is indeed in my custom apps folder even if the URL part is indicating otherwise.
```
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/customapps',
      'url' => '/customapps',
      'writable' => true,
    ),
  ),
```

**Comment by twieskot** [comment]
> 
> 
> @twieskot just to be sure that we are on the same page and avoid misunderstandings. We are not talking about what is being displayed on the Browser like https://domain.example/apps/rainloop/ but rather how it has been setup in the config.php.
> 
> My relevant section here is this where Rainloop is indeed in my custom apps folder even if the URL part is indicating otherwise.
> 
> ```
>   'apps_paths' =>
>   array (
>     0 =>
>     array (
>       'path' => '/var/www/apps',
>       'url' => '/apps',
>       'writable' => false,
>     ),
>     1 =>
>     array (
>       'path' => '/var/www/customapps',
>       'url' => '/customapps',
>       'writable' => true,
>     ),
>   ),
> ```

Sorry, yes my fault. Same for me:

'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),

**Comment by pierre-alain-b** [comment]
I agree with this last comment: the URL is showing "/apps/" irrespective of the back-end path. So you should check the config.

I was able to replicate the bug on a test instance with the custom_apps folder. I would propose a hack that could temporarily fix the issue for those impacted (waiting for a better long term solution)

**Comment by waltherjj** [comment]
> I agree with this last comment: the URL is showing "/apps/" irrespective of the back-end path. So you should check the config.
> 
> I was able to replicate the bug on a test instance with the custom_apps folder. I would propose a hack that could temporarily fix the issue for those impacted (waiting for a better long term solution)

this would be very much appreciated!

**Comment by pierre-alain-b** [comment]
Dirty hack for those in a hurry to re-establish access:

in /path/to/nextcloud/custom_apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Utils.php

change
```
			if (empty($sAppPath))
			{
				$sUrl = \MailSo\Base\Http::SingletonInstance()->GetUrl();
				if ($sUrl && \preg_match('/\/index\.php\/apps\/rainloop/', $sUrl))
				{
					$sAppPath = \preg_replace('/\/index\.php\/apps\/rainloop.+$/',
						'/apps/rainloop/app/', $sUrl);
				}
			}
```
into
```
			if (true)
			{
				$sUrl = \MailSo\Base\Http::SingletonInstance()->GetUrl();
				if ($sUrl && \preg_match('/\/index\.php\/apps\/rainloop/', $sUrl))
				{
					$sAppPath = \preg_replace('/\/index\.php\/apps\/rainloop.+$/',
						'/custom_apps/rainloop/app/', $sUrl);
				}
			}
```

of course custom_apps shall be changed for the appropriate path!

**Comment by fracarvic** [comment]
> Dirty hack for those in a hurry to re-establish access:
> 
> in /path/to/nextcloud/custom_apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Utils.php
> 
> change
> 
> ```
> 			if (empty($sAppPath))
> 			{
> 				$sUrl = \MailSo\Base\Http::SingletonInstance()->GetUrl();
> 				if ($sUrl && \preg_match('/\/index\.php\/apps\/rainloop/', $sUrl))
> 				{
> 					$sAppPath = \preg_replace('/\/index\.php\/apps\/rainloop.+$/',
> 						'/apps/rainloop/app/', $sUrl);
> 				}
> 			}
> ```
> 
> into
> 
> ```
> 			if (true)
> 			{
> 				$sUrl = \MailSo\Base\Http::SingletonInstance()->GetUrl();
> 				if ($sUrl && \preg_match('/\/index\.php\/apps\/rainloop/', $sUrl))
> 				{
> 					$sAppPath = \preg_replace('/\/index\.php\/apps\/rainloop.+$/',
> 						'/custom_apps/rainloop/app/', $sUrl);
> 				}
> 			}
> ```
> 
> of course custom_apps shall be changed for the appropriate path!

changed code and working now !!!!

Thanks.

**Comment by waltherjj** [comment]
> Dirty hack for those in a hurry to re-establish access:
> 
> in /path/to/nextcloud/custom_apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Utils.php
> 
> change
> 
> ```
> 			if (empty($sAppPath))
> 			{
> 				$sUrl = \MailSo\Base\Http::SingletonInstance()->GetUrl();
> 				if ($sUrl && \preg_match('/\/index\.php\/apps\/rainloop/', $sUrl))
> 				{
> 					$sAppPath = \preg_replace('/\/index\.php\/apps\/rainloop.+$/',
> 						'/apps/rainloop/app/', $sUrl);
> 				}
> 			}
> ```
> 
> into
> 
> ```
> 			if (true)
> 			{
> 				$sUrl = \MailSo\Base\Http::SingletonInstance()->GetUrl();
> 				if ($sUrl && \preg_match('/\/index\.php\/apps\/rainloop/', $sUrl))
> 				{
> 					$sAppPath = \preg_replace('/\/index\.php\/apps\/rainloop.+$/',
> 						'/custom_apps/rainloop/app/', $sUrl);
> 				}
> 			}
> ```
> 
> of course custom_apps shall be changed for the appropriate path!

the proposed fix did not work for me as some of the assets still loaded from the wrong route. for others running into the same problem, another possible hack (that makes this work for me) is leaving the conditional block as is, but replacing the string in the return value, e.g.:

```
public static function WebPath()                                                                 
        {                                                                                                
                $sAppPath = '';                                                                          
                if (\RainLoop\Utils::IsOwnCloud())                                                       
                {                                                                                        
                        $sAppPath = \OC::$server->getURLGenerator()->linkToRoute('rainloop.page.appGet');
                        // TODO: Fix this ugly hack. Is there a "modern" way to return                   
                        // a URL that doesn't include index.php, which breaks things?                    
                        $sAppPath = preg_replace('/index\.php\//', '', $sAppPath);                       
                                                                                                         
                        if (empty($sAppPath))                                                            
                        {                                                                                
                                $sUrl = \MailSo\Base\Http::SingletonInstance()->GetUrl();                
                                if ($sUrl && \preg_match('/\/index\.php\/apps\/rainloop/', $sUrl))       
                                {                                                                        
                                        $sAppPath = \preg_replace('/\/index\.php\/apps\/rainloop.+$/',   
                                                '/apps/rainloop/app/', $sUrl);                           
                                }                                                                        
                        }                                                                                
                }                                                                                        
                return str_replace('/apps/rainloop/app', '/custom_apps/rainloop/app', $sAppPath); 
```

as mentioned above, replace custom_apps with your custom app folder.

**Comment by matze0301** [comment]
Had the same Problem with white screen and only the second fix from @waltherjj  worked for me.
(NC/RL on Docker behind nginx Reverse Proxy)
Thank you all :-)

**Comment by conspacer** [comment]
@waltherjj tmp solution worked. Tx
NC 19 (official Docker) / Rainloop 7.0.1 / Nginx ReverseProxy with LE SSL

**Comment by shankari** [comment]
Just to confirm that it is not related to nginx in any way, my setup is:

- NC 19 (official docker `apache` image, sha: `6375cff75f7b`)
- Rainloop 7.0.1
- Apache reverse proxy with LE SSL
- rainloop installed in `custom-apps`

@pierre-alain-b's hack did not work
@waltherjj's hack worked

**Comment by SebastianThuesen** [comment]
I am running Nextcloud with snap on Ubuntu 20.04 LTS and Apache2 with reverse proxy module on another machine.
RainLoop does work with 18.0.6snap1 with rainloop version  6.1.4 based on 1.14.0
RainLoop does not work with 19.0.0snap1 with rainloop version  7.0.1 based on 1.14.0

@waltherjj hack works. 

To get the hack to work with NextCloud snap:
outcomment this in the **public static function WebPath()**:
`return $sAppPath; `
**and paste this in right above the out-commented code:**
`return str_replace('/apps/rainloop/app', '/extra-apps/rainloop/app', $sAppPath);`
**in the Utils.php file located at:**
`/var/snap/nextcloud/current/nextcloud/extra-apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/`

Rainloop will work after this for 19.0.0snap1

**Comment by SebastianThuesen** [comment]
I am running **Nextcloud with snap** on **Ubuntu 20.04 LTS** and **Apache2 with reverse proxy module** on another machine.
RainLoop does **work** with **18.0.6snap1** with **rainloop version 6.1.4 based on 1.14.0**
RainLoop does **not work** with **19.0.0snap1** with **rainloop version 7.0.1 based on 1.14.0**

**@waltherjj hack works.**

To get the hack to work with **NextCloud snap**:
**outcomment** this in the **public static function WebPath()**:
`return $sAppPath;`
and paste this in right above the out-commented code:
`return str_replace('/apps/rainloop/app', '/extra-apps/rainloop/app', $sAppPath);`
in the **Utils.php** file located at:
`/var/snap/nextcloud/current/nextcloud/extra-apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/`

Rainloop **will work** after this for **19.0.0snap1**

Another solution is just to revert from 19 to 18 trough the `sudo snap revert nextcloud` command

**Comment by bsherwoodofdaptiv** [comment]
Yeah. I hit this too. I am hosted in AWS Lightsail. Something upgraded my dam* install to 19.x behind my back. Turned off several 'untested' apps, and broke this. I really need to spin up a replacement server and hard install (not SNAP) Nextcloud, so things like this don't break.

**Comment by bsherwoodofdaptiv** [comment]
@SebastianThuesen -- thank you for how to do this with a SNAP setup. It helps all of us stuck with this auto-upgraded problem with SNAP.

**Comment by relikd** [comment]
Haven't read through the whole topic but wanted to create an issue for the same bug.
My problem was (and still is) that I could not open the admin interface.

I figured the problem in my case. The generated html has links to static files that are not present on the server (404). But the URL is just slightly wrong. `/apps/...` instead of `/extra-apps/...`  
Maybe its relevant that I have nextcloud installed via snap.

The `WebStaticPath` function seems to produce a wrong URL:
https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/app/rainloop/v/1.14.0/app/libraries/RainLoop/Utils.php#L596

It produces:

```
/apps/rainloop/app/rainloop/v/1.14.0/static/js/min/boot.min.js?community
```

instead of:

```
/extra-apps/rainloop/app/rainloop/v/1.14.0/static/js/min/boot.min.js?community
```

I have no idea whether other parts may have wrong URLs too, but fixing this single line above at least shows the admin interface.

**Comment by kyrofa** [comment]
@bsherwoodofdaptiv FYI you don't need to be following the stable channel if you don't want to automatically update across major versions. Use `sudo snap refresh nextcloud --channel=18` instead and you'll stay on v18 (minor version updates only) until you're ready to upgrade. See the snap [release strategy](https://github.com/nextcloud/nextcloud-snap/wiki/Release-strategy) page for more details. Also see [what do I do if an update breaks Nextcloud](https://github.com/nextcloud/nextcloud-snap/wiki/What-do-I-do-if-an-update-breaks-Nextcloud%3F).

**Comment by Griefed** [comment]
@waltherjj's Hack worked for me, too. Thank you very much!
Running Nextcloud with a docker-compose composed of NGINX and Let's Encrypt auto-certification

**Comment by Pit-Storm** [comment]
I have the same problem but not able to edit such files, because using a hosted instance on hetzners storage-share.
A few days ago it worked fine but since today it's only showing a blank screen.

Nextcloud 19.0.1
rainloop: 7.0.1

Is it possible that there will be a patch on appstore soon?

**Comment by Pit-Storm** [comment]
I have the same problem but not able to edit such files, because using a hosted instance on hetzners storage-share.
A few days ago it worked fine but since today it's only showing a blank screen.

Nextcloud 19.0.1
rainloop: 7.0.1

Is it possible that there will be a patch on appstore soon?

**Comment by pierre-alain-b** [comment]
Well, unfortunately for now, there is no simple hack identified (unless I missed something) that would work both for classical deploments and a custom apps path. Am I misunderstanding the situation here?

**Comment by ghost** [comment]
I have the same issue at Hetzner, cannot edit files because it is a managed instance.
Running on:
Nextcloud 19.0.1
rainloop: 7.0.1

I would be very good if you could adress the issue on the Nextcloud Marketplace for usage within the NC platform.

Kind regards!

**Comment by ghost** [comment]
Hi Pierre

Can you please change the compatibility in the NC Store to not compatible with NC19 then? Do you intend to release a working update or is the plugin for NC19 obsolete now?

Kind regards!

**Comment by pierre-alain-b** [comment]
In fact Rainloop is compatible with NC19, I have hundreds of users using it without issue. The issue only appears when one chooses to use a custom path for the apps folder.
It is not yet clear for me in which situation apps are deployed this way rather than the standard way. A clue anyone? Is this the standard behavior from now on?

**Comment by cvandesande** [comment]
> It is not yet clear for me in which situation apps are deployed this way rather than the standard way

It's pretty standard if you are using the official Nextcloud docker image: https://github.com/nextcloud/docker which I suspect most of the "managed" Nextcloud providers are using in order to automate their upgrades and rollbacks.

The custom_apps setup is describe in the README.md towards the end

**Comment by Pecadis** [comment]
Yes, as far as i can see, the Custom apps folder makes sense, if you want to avoid problems when updating your NC instance and separate between the Official and Custom ones.

https://docs.nextcloud.com/server/19/admin_manual/apps_management.html#using-custom-app-directories

Wouldn't it make sense to throw away the conditional if and replace the path with the variables from the Documentation?
Something like this (Pseudocode)

```
get scriptpath // to know where rainloop is located
read the "app_paths" array and find the matching one
return the path with the appropriate url of the array.
```

Because with the current workaround, we are basically doing this step manually by replacing the default path "/apps/rainloop/app" with the custom one "/customapps/rainloop/app" which basically just overrides everything in the condition.

**Comment by ghost** [comment]
Hi Pierre

Can we expect a resolution for people with hosted instances who are not able to correct the code in the files directly? 
The original app for mail is really poor compared to yours. However, on Hetzner and likely other magaged hosters, your plugin is rendered useless right now.

Do you have any intention to fix this? Because currently it does not look like it. This is marked as a bug for two months and nothing happens?

Why is there no reply to Pecadis' message? Custom App directories are common, well documented and compatible with pretty much every plugin - **except yours**!

**Comment by Pecadis** [comment]
@bungyguy no need to be personal on him. He is doing this by himself without any payback, so be kind or do something contructive

**Comment by pierre-alain-b** [comment]
@pecadis and @cvandesande thank you for pointing out the context in which custom_apps are used, I understand now why the apps are placed in the custom folder.  Your pseudocode makes absolute sense. 

@bungyguy yes clearly your message is not helping, every minute I spend on this plugin is taken from:
- paid activities
- free time with my children

If you put forward a pull request to fix this, this would be of tremendous help and I pledge to review and accept it in very little time.   That would be a better way forward and smarter than your message.

**Comment by ghost** [comment]
Hi Pierre

I did not want to be rude, sorry if thats the case. I really just wanted to know if a fix is coming or if the plugin is now obsolete on some hosted environments. A solution was proposed by Pecadis and others, but no reaction.

I am not a developer, so I cannot help with a pull request. However, I am more than happy to support the project financially, so let me know your paypal address and I will do whatever I can towards the project.

Anyways, thanks a lot for your work on the application!

**Comment by pierre-alain-b** [comment]
I have a fix to propose. I will publish 7.0.2 on the app store and you will tell me if this works. Then maybe we will be able to cheer and close this issue.

**Comment by pierre-alain-b** [comment]
And @bungyguy if it works and if you want to pay me a coffee or a beer, here you can go https://paypal.me/pierrealainb

**Comment by ghost** [comment]
Hi Pierre

Thank you so much for your efford on fixing this. I can confirm everything is smooth on Hetzner NC19 and RL 7.0.2.
Enjoy a few beer and coffee. ;-) Maybe you can put the paypal link on your website for others too?

Have a nice Weekend!

**Comment by eloo** [comment]
Looks also good with hoellen/nextcloud 👍 
Beer incoming!

Thanks

**Comment by Pecadis** [comment]
@pierre-alain-b it works on my instance as well. That seems to have solved the issue =)

**Comment by samsalway** [comment]
Working in Docker 👍

**Comment by pierre-alain-b** [comment]
Thank you everyone for helping understand the conditions in which the bug occurred, for reporting about it and for your patience!
And thanks to all who sent some support/beer/coffee/candies through Paypal, much appreciated!
