### ISSUE TITLE
Rainloop in Nextcloud in myApp

### ISSUE THREAD

**Issue by mmallejac** [pierre-alain-b/rainloop-nextcloud#203]
Hello !

We've successfully included Nextcloud within our web app, by tweaking `/var/www/html/lib/public/AppFramework/Http/ContentSecurityPolicy.php`, it works just fine, except for Rainloop which is itself included within an iFrame in Nextcloud.

We would like to call directly the Rainloop frame from our web app, or at a minimum call Rainloop from within Nextcloud (within our app). For both, we get blocked by X-Frame-Options Policy.

I had some success in the past tweaking the `data/rainloop-storage/_data_/_default_/configs/application.ini` file with the `content_security_policy` parameter, with a value of `"frame-ancestors https://ourapp"` but : 

- the application.ini file is no longer present ? i saw [this](https://github.com/RainLoop/rainloop-webmail/issues/1685)
- adding it manually does not work either

Any direction would be much appreciated !
Many thanks

**Comment by pierre-alain-b** [comment]
CSP are also set for the Rainloop app in the lib/Controller/PageController.php.
Maybe you also have to tweak something here?

**Comment by mmallejac** [comment]
Thanks for pointing this ! I've tried but no luck so far...

**Comment by pierre-alain-b** [comment]
application.ini is supposed to still be there, are you sure you are looking in the right folder?
