### ISSUE TITLE
Feature request: Option to disable user settings override

### ISSUE THREAD

**Issue by relikd** [pierre-alain-b/rainloop-nextcloud#204]
Hi there, I am trying to setup a small collaboration space for a selected number of users.
I'd like to use rainloop to have a single email account shared by multiple users.
Something where more than one user can read and reply to emails.

But I would rather not have the people store the password in their user settings.
Can we have an additional setting to disable automatic user login override.
A very quick fix could be to immediately return from `personal_settings.php`.

Or to take this idea further. 
I would prefer to set a single email account for all users.
Maybe even a list of accounts the user can choose from a drop-down field.

Either with or without a pre-set password. One could even hide the real password behind an unrelated one.

**Comment by pierre-alain-b** [comment]
Well, this is indeed pretty specific and you will not be able to prevent users from creating multiple accounts within Rainloop unless you also change significantly Rainloop app... So this seems to be a lot of work for that use case.

**Comment by szaimen** [comment]
@relikd You could maybe at least hide that section with custom_css app for Nextcloud and adding the foolowing code to it:
```css
form#mail-rainloop-personal-form { display: none; }
```

**Comment by relikd** [comment]
Maybe something that is (rather easy?) realisible with rainloop: can we have configurable fake accounts? So I could set account FakeA for user A, which has the emails A, B, and C configured. Then another FakeB account for user B which has only B and C emails, etc. Cause right now if I preset email A for two users they will see the same additionally added email accounts. E.g., if user A adds email B, then user B will also see the emails for email B (without configuring himself/herself). A fake account would also hide the real password in the user settings so one would not be able to just open dev tools and look up the password.

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
