### ISSUE TITLE
Rainloop auto-login no longer works in NC19

### ISSUE THREAD

**Issue by chagwood** [pierre-alain-b/rainloop-nextcloud#206]
Even though my e-mail credentials are the same as my nextcloud and I have the setting marked to attempt to login with nextcloud username and password, it just takes me to the rainloop login screen.

**Comment by pierre-alain-b** [comment]
It is likely your Rainloop is not well configured to derive the email account to use based on Nextcloud username. Could you tell us if you have set a default domain and share more info on your rainloop settings?

**Comment by chagwood** [comment]
I have tried both options - deriving from username and from nextcloud e-mail. Both just take you to the rainloop login screen. I haven't touched a rainloop setting since setting it up months ago. It used to work perfectly and log you right into rainloop. The only thing that has changed was I upgraded to NC19.

If you need me to get any log files, just let me know where they are and I will gladly oblige

**Comment by pierre-alain-b** [comment]
There had been some major changes in the version of Rainloop for NC19. Are you sure there are no user-defined credentials that would interfere?

"Attempt to automatically login users with their Nextcloud username and password, *or user-defined credentials*, if set. "

**Comment by chagwood** [comment]
I'm closing this because it all seems to work fine now. I didn't change anything though so I'm still stumped as to why it auto-logs me in when a few days ago it would not. Thanks for the quick responses!
