### ISSUE TITLE
NC20 - Will Rainloop support dashboard?

### ISSUE THREAD

**Issue by Shen** [pierre-alain-b/rainloop-nextcloud#208]
Are there any plans to support the new dashboard-feature, which comes with NC20?
https://github.com/nextcloud/server/issues/20930

**Comment by pierre-alain-b** [comment]
There is no direct plan for this as for now. This may not be extremely easy as the Rainloop plugin is incorporating the Rainloop app within Nextcloud but there is limited internal discussions between NC and Rainloop and I assume that we would need to call Rainloop, get the latest emails and display them in the Dashboard.
I see that the job was done for the Mail app.
If someone wants to inspect the code change and see if this could be translated to Rainloop, any Merge Request would be reviewed with care and certainly accepted!

**Comment by Shen** [comment]
Maybe a helpful link to inspect the code change for mail app:
https://github.com/nextcloud/mail/pull/4124/commits/a77aed871a75f625bc2830206ca88176f163c791

**Comment by pierre-alain-b** [comment]
Stalled issue - there is much plan forward to implement this for Rainloop for Nextcloud.
