### ISSUE TITLE
PDF attachment preview does not open in Chrome

### ISSUE THREAD

**Issue by mopawa** [pierre-alain-b/rainloop-nextcloud#21]
Hello,

Using Chrome 59, it is impossible to preview a pdf attachment. The console gives further info on the issue: 

> Refused to load plugin data because it violates the following Content Security Policy directive: "object-src 'none'"

Nextcloud is setting the "Content-Security-Policy" header with object-src set to 'none' where it should be set to 'self' to allow loading the pdf preview in the browser.

I have seen that it is possible to modify the headers sent by Nextcloud directly in the plugin.

An example is given here:
[https://github.com/owncloudarchive/jsxc.chat/blob/master/appinfo/app.php](url)

What do you think?

**Comment by pierre-alain-b** [comment]
Hi,
Interesting, thank you for raising this!

In FF, I cannot see how you attempt to preview the PDF in the browser. Can you tell more precisely the actions you undertake to try and preview the PDF? It would be interesting so that I could replicate the bug and help further.

If you can test on your end, does it fix something if you add:

```
if(class_exists('\\OCP\\AppFramework\\Http\\EmptyContentSecurityPolicy')) {
	$manager = \OC::$server->getContentSecurityPolicyManager();
	$policy = new \OCP\AppFramework\Http\EmptyContentSecurityPolicy();
	$policy->addAllowedStyleDomain('\'self\'');
	$policy->addAllowedImageDomain('\'self\'');
	$policy->addAllowedMediaDomain('\'self\'');
	$policy->addAllowedChildSrcDomain('\'self\'');
	$policy->addAllowedConnectDomain('\'self\'');
	$manager->addDefaultPolicy($policy);
}
```
in your app.php file?

**Comment by mopawa** [comment]
Hi Pierre,

As far as I know, the pdf preview is a Chrome feature so it is not available in Firefox. To preview the pdf in Chrome, you just hover your mouse on the attachment and the "pdf" indication turns into an "eye" icon.

I already tried to add the code in app.php but it does nothing, the Nextcloud headers are not modified. I think this only works when the plugin uses Nextcloud's app framework. Can you confirm whether your plugin does?

**Comment by pierre-alain-b** [comment]
Would you be able to share a couple of screenshots to understand better the behavior that is expected?

**Comment by mopawa** [comment]
Here is the normal display of the attachment:
![2017-08-09 16_30_57-email - airtechs cloud](https://user-images.githubusercontent.com/4270199/29142745-df9011de-7d20-11e7-8799-a5cb6be18011.png)

And when you hover:
![2017-08-09 16_31_17-email - airtechs cloud](https://user-images.githubusercontent.com/4270199/29142770-f43ae186-7d20-11e7-8f29-0de5f167650d.png)

When clicked, it opens a new tab that displays the PDF file.

**Comment by 8sol** [comment]
Hi all.
I have the same issue with Nextcloud 12.0.0 and Rainloop 5.0 app. If I try to open the attached PDF in Chrome a new tab opens but the PDF is not showing. If I check with F12 I can see the following error:

`Refused to load plugin data from https://.......cloud/apps/rainloop/app/?/Raw/&q[]=/_4pXWviXqzv7X..... because it violates the following Content Security Policy directive: "object-src 'none'".`

Same check with Firefox, the option to preview the PDF is not given here I can only download the PDF without the preview function. 

The cloud is running on a Ubuntu 14.04 LTS with PHP-FPM and PHP 7. Couple of weeks before this has been works fine

Screenshot PDF preview
![pdf_preview](https://user-images.githubusercontent.com/29546376/29240247-66416cea-7f61-11e7-8692-d0870d9331fe.JPG)

Thanks in advanced

**Comment by pierre-alain-b** [comment]
Thank you for all this.
Where do you see the error message?
I've just tried with Chromium, and If I do fail displaying the PDF directly in the browser, I see no error message in the Dev Console of Chromium. Is this a Chrome-only feature? I installed PDFViewer Chrome extension in Chromium with no change...

Sorry I've a hard time replicating... complicated to fix without replicating. I am not saying the bug does not exist, only that my Chromium instance is just downloading the PDF when I click on the "eye" icon that appears when hovering on the link.

**Comment by 8sol** [comment]
confirmed, chrome itself shows only the attached screenshot with my last message in case i click on the eye button. By clicking on the pdf name itself, chrome is downloading the PDF file (in my case to my desktop). I think 'Chromium' and 'Chrome' should be have the same features. Please find attached a screenshot showing the chrome dev console inlcuding the error message. If this not helps, I can create a demo account for you on my cloud instance

Chrome Dev Console: 
![error_message_chrome_console](https://user-images.githubusercontent.com/29546376/29253677-415879fe-8084-11e7-93f7-60ca585c384b.JPG)
. 

Thank you again for your help

**Comment by mopawa** [comment]
Pierre Alain,

In fact, as I said in my first post, we know where the issue comes from: it's because Nextcloud is adding the header "Content-Security-Policy" with "object-src" set to 'none' instead of 'self'.

It is possible to fix the issue by modifying Nextcloud source (lib/private/legacy/response.php) but of course this is a dirty fix. (ref: [https://help.nextcloud.com/t/content-security-policy-in-nextcloud/5288](url) )

Unless you can find a way in your plugin to change this header by using Nextcloud's AppFramework, I think it will be difficult to fix this bug.

**Comment by pierre-alain-b** [comment]
I know we know the origin of the problem. But it is more complicated to develop and test if I cannot see myself reliably the issue.
Don't hesitate to submit a pull request if ever you have a fix for the problem, i will make sure to have it accepted very quickly.

**Comment by pfy** [comment]
It won't work with contentSecurityManager, because rainloop nextcloud goes through the legacy response system (lib/private/legacy/response.php). 
There is a hardcoded policy set before the request so we have to overwrite the header. :(

Not a nice solution but it works.

**Comment by pierre-alain-b** [comment]
Thank you very much @pfy!

@mopawa and @8sol, can you try the fix that pfy has proposed? If it works for you, I will accept the merge request and release a new version of the Rainloop plugin.

**Comment by mopawa** [comment]
Hi Pierre-Alain,

It works! Thanks a lot @pfy

**Comment by pierre-alain-b** [comment]
The v5.0.1 of the plugin with the fix has just been published in the Nextcloud app store!
Enjoy.
PAB
