### ISSUE TITLE
[Help requested] App path still detecting wrong in NC 19.0.3 and Rainloop 7.0.2

### ISSUE THREAD

**Issue by XenDeKhra** [pierre-alain-b/rainloop-nextcloud#210]
After reading through this issue (https://github.com/pierre-alain-b/rainloop-nextcloud/issues/201) to understand the main issue, I seem to have come across a related issue that I don't have the php skills to fix.  

In my installation (rpm install from Fedora), the app store app path is, by default, in `/var/lib/nextcloud/apps` with the url path of `/apps-appstore`.  From the method of detecting that is currently being used, my path is still determined as `apps/rainloop/app` instead of `apps-appstore/rainloop/app`.  

I think the better solution to this issue would be to, instead of matching the string from wherever the __FILE__ is, pull the `apps_paths.1.url` variable (I might have that array construction wrong but I think it is understandable) from the NextCloud config.php.  That should always have the correct path (even if it doesn't match the local folder name), so far as I could tell from the NextCloud docs on custom app directories.

**Comment by pierre-alain-b** [comment]
Ok I see the issue. But then the issue to know which app path shall be selected... so in fact we should look where the file is and then find the URL path in the config for that path... correct?

**Comment by XenDeKhra** [comment]
Ah, yes, that would probably be the best way to ensure that the right path is chosen.

**Comment by gymnae** [comment]
Issues still exists in NC 20.0.1

**Comment by pierre-alain-b** [comment]
This issue must still be relevant for the latest version. Any PR welcome to address this! Alternatively, we could collect a little bit of funding for it and find a freelance dev to take it, I think 1 or 2 hours would be suffficient to address the issue.

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
