### ISSUE TITLE
Undefined variable: sPasswordSalt

### ISSUE THREAD

**Issue by aleadco** [pierre-alain-b/rainloop-nextcloud#211]
Any idea why I get this error, could it be that a user is entering their credentials wrong ???

`Undefined variable: sPasswordSalt at /var/www/nextcloud/apps/rainloop/lib/Controller/PageController.php#99`

**Comment by pierre-alain-b** [comment]
No I don't think so.
Is it a blocking error?

**Comment by aleadco** [comment]
Hello, I already found out the time when the error occurs.
The rainloop / settings / admin / additional configuration I have set `Users must register manually, or define credentials in their personal settings for automatic registration. `
Now the error occurs when a user who has not yet defined her credentials by default in personal settings and makes use of the application.
In other words, your data has not been saved in your personal settings and you prefer to enter them every time you open the rainloop application.
@pierre-alain-b  It's not a block like you ask me at least I think so.
Regards

**Comment by JordanDIG** [comment]
This is a little bit annoying this error, can't you do something to hide it? @pierre-alain-b

**Comment by pierre-alain-b** [comment]
Dear Jordan,
could you try this to implement this new line in the lib/Controller/PageController.php and tell me if you still have the error message?

```
diff --git a/lib/Controller/PageController.php b/lib/Controller/PageController.php
index 27224f4..97ea3fc 100644
--- a/lib/Controller/PageController.php
+++ b/lib/Controller/PageController.php
@@ -74,6 +74,7 @@ class PageController extends Controller {
                if (isset($_GET['OwnCloudAuth'])) {
                        $sEmail = '';
                        $sEncodedPassword = '';
+                       $sPasswordSalt = '';
 
                        $sUser = \OC::$server->getUserSession()->getUser()->getUID();
```

If this fixes it, then I will have it added in the next release!

**Comment by JordanDIG** [comment]
> Dear Jordan, could you try this to implement this new line in the lib/Controller/PageController.php and tell me if you still have the error message?
> 
> ```
> diff --git a/lib/Controller/PageController.php b/lib/Controller/PageController.php
> index 27224f4..97ea3fc 100644
> --- a/lib/Controller/PageController.php
> +++ b/lib/Controller/PageController.php
> @@ -74,6 +74,7 @@ class PageController extends Controller {
>                 if (isset($_GET['OwnCloudAuth'])) {
>                         $sEmail = '';
>                         $sEncodedPassword = '';
> +                       $sPasswordSalt = '';
>  
>                         $sUser = \OC::$server->getUserSession()->getUser()->getUID();
> ```
> 
> If this fixes it, then I will have it added in the next release!

In which part of the file should I put this and on which lines?

**Comment by JordanDIG** [comment]
because I don't know where to put it in the file...

**Comment by pierre-alain-b** [comment]
In fact I copy pasted the diff.

The line
`$sPasswordSalt = '';`
shall be added 
at line 76 here:
![image](https://user-images.githubusercontent.com/386857/159864130-76256513-53bc-4c54-bee6-fc6414d37483.png)

**Comment by JordanDIG** [comment]
It doesn't matter: this is my file:
[https://haste.jordand.fr/ataboxuger.php](https://haste.jordand.fr/ataboxuger.php)

**Comment by JordanDIG** [comment]
https://haste.matthieul.dev/ohraw.php

**Comment by pierre-alain-b** [comment]
You mean there is no change and the error message is still there, correct?

**Comment by JordanDIG** [comment]
Yes, but I don't know if the modification has been done... can you check?

**Comment by pierre-alain-b** [comment]
Yes the change has been done correctly in https://haste.matthieul.dev/ohraw.php

**Comment by JordanDIG** [comment]
So yes now I don't have the error

**Comment by pierre-alain-b** [comment]
Ah OK, so change made and error gone! This seems to be fixed then! If you agree, I let you close the ticket and I will have the change incorporated in the next version.

**Comment by JordanDIG** [comment]
Yes good luck

**Comment by pierre-alain-b** [comment]
it's work rather than luck hopefully in this case :-)

**Comment by JordanDIG** [comment]
I cannot close the exit, I am not its creator @pierre-alain-b
