### ISSUE TITLE
Access to the admin login page by non-admin users.

### ISSUE THREAD

**Issue by AltiUP** [pierre-alain-b/rainloop-nextcloud#212]
Normal users can access the admin login page of RainLoop on NC20.

Is this normal behavior?

Thank you ;)
Chris

**Comment by pierre-alain-b** [comment]
Is this only in NC20?
A priori it does not seem a major flaw and normal users will not know the password to access the admin page. Correct?

**Comment by AltiUP** [comment]
> Is this only in NC20?
> A priori it does not seem a major flaw and normal users will not know the password to access the admin page. Correct?

I didn't try it on NC19 .

Yes indeed it is not very important, if they do not know the password.
