### ISSUE TITLE
Autologin not working

### ISSUE THREAD

**Issue by cdidier** [pierre-alain-b/rainloop-nextcloud#213]
Since this commit https://github.com/nextcloud/server/commit/ac8b40b8b12d4bf85bdd6b7ab038f0605c8651d9 in Nextcloud 20.0.0 a new parameter was added to the postLogin hook which breaks the parameter order of the callback in https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/lib/Util/RainLoopHelper.php#L25.

**Comment by loxK** [comment]
I can confirm the issue. Since 20.0.0 autologin is broken.

**Comment by dl-lim** [comment]
Confirmed, on 20.0.0, 20.0.2, 20.0.3

**Comment by LukaszSellmann** [comment]
Confirmed, still doesn't work on 20.0.X

**Comment by rchavik** [comment]
I managed to fix this by this patch:

```diff
--- RainLoopHelper.bak.php	2021-01-06 04:38:03.070264206 +0000
+++ RainLoopHelper.php	2021-01-06 04:37:35.173843704 +0000
@@ -22,8 +22,8 @@
 	}
 
 	public function registerHooks() {
-		$this->userSession->listen('\OC\User', 'postLogin', function($user, $password) {
-			$this->login($user, $password, $this->config, $this->session);
+		$this->userSession->listen('\OC\User', 'postLogin', function($user, $loginName, $password) {
+			$this->login($user, $loginName, $password, $this->config, $this->session);
 		});
 
 		$this->userSession->listen('\OC\User', 'logout', function() {
@@ -212,7 +212,7 @@
 	 * @return boolean
 	 * @UseSession
 	 */
-	public static function login($user, $password, $config, &$session)
+	public static function login($user, $loginName, $password, $config, &$session)
 	{
 		$sUser = $user->getUID();
 ```

Above seems to work for me, because I'm using external user (IMAP).

However, the above patch is not 100% correct, because it seems now `postLogin` event expects different arguments: https://github.com/nextcloud/server/blob/3a30ac495bd9663ef8233aacc8ce5b21a8adce67/lib/private/Server.php#L570.

**Comment by ogmkp** [comment]
Hi. Same issue here.

**Comment by dl-lim** [comment]
Hey, not sure if it's just me.. I updated the rainloop app, but it's still not auto-logging in. I was using 20.0.3 then. I just upgraded to 20.0.8, and it seems it's still not auto-logging in.

Happy to provide details. Let me know
