### ISSUE TITLE
Update to v1.15.0

### ISSUE THREAD

**Issue by szaimen** [pierre-alain-b/rainloop-nextcloud#217]
Hey, I wonder if you could update Rainloop to v1.15.0?
https://github.com/RainLoop/rainloop-webmail/releases/tag/v1.15.0
https://www.rainloop.net/changelog/

**Comment by pierre-alain-b** [comment]
It is a longer process than usual because a number of changes had to be made inside Rainloop in last versions of plugin. This needs to be ported to 1.15.

**Comment by Aquariu** [comment]
At some point it will be necessary as php7.x support will be dropped eventually by NC (and Rainloop 1.15 is the first to support php8).
Probably no rush though. From the NC changelog and/or the NC's system requirement page :
- php7.2 support as **added** in NC13
- 6.x support dropped in NC14
- 7.3 added in NC15
- php7.0 support was **dropped** in NC15
- 7.1 support dropped in NC18
- php7.2 is apparently still supported in NC19
- php7.3 and 7.4 are the only supported version in NC20
- Announcement says that NC21 supports php8 and php7.4, although the admin manual doesn't reflect that yet.

So we're probably safe for a couple versions more of NC before they drop php7.4 support.

**Comment by szaimen** [comment]
Actually, php7.2 is still supported in NC20 but no longer in NC21

**Comment by ghost** [comment]
Hello Pierre-Alain,
Do you know when you can make this update?

**Comment by pierre-alain-b** [comment]
Work in progress

**Comment by pierre-alain-b** [comment]
Time to test: https://apps.nextcloud.com/apps/rainloop/releases?platform=21#21

**Comment by pierre-alain-b** [comment]
The tests look good on my side.

**Comment by ghost** [comment]
Bjr,
Vue le prénom j'écris en français :)
Un grand merci à toi !!! Je te fais un retour après 2/3 jours d'utilisation.

Merci encore

Christophe
