### ISSUE TITLE
Resetting the Admin Password?

### ISSUE THREAD

**Issue by closewall** [pierre-alain-b/rainloop-nextcloud#219]
I'm running Nextcloud on Unraid, and wasn't thinking when I first reset the admin password.

I am looking to reset it, but have no idea how. I found an older issue regarding this, but it no longer works. I cannot find application.ini anywhere, not in the appdata folder, not in the nextcloud app folder, nowhere.

Where am I supposed to find it?

**Comment by pierre-alain-b** [comment]
You have to find your application.ini. It should be somewhere otherwise the application cannot work.
https://github.com/pierre-alain-b/rainloop-nextcloud#how-to-activate-rainloop-logging-and-then-find-logs
Double check your data folder.

**Comment by doublemultiply** [comment]
> You have to find your application.ini. It should be somewhere otherwise the application cannot work.
> https://github.com/pierre-alain-b/rainloop-nextcloud#how-to-activate-rainloop-logging-and-then-find-logs
> Double check your data folder.

Which data folder? There are several.

https://i.imgur.com/SSljzVC.png

Keep in mind I have deleted both Rainloop directories twice, but I still get the same problem.

**Comment by pierre-alain-b** [comment]
Not the data folder of the plugin, the data folder of Nextcloud. The folder where Nextcloud puts all the users' files and so on.
`/path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini`

**Comment by doublemultiply** [comment]
> No the data folder of the plugin, the data folder of Nextcloud. The folder where Nextcloud puts all the users' files and so on.
> `/path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini`

Thanks. I did check that directory but must've somehow missed it. Sorry for the noob trouble.

**Comment by doublemultiply** [comment]
> No the data folder of the plugin, the data folder of Nextcloud. The folder where Nextcloud puts all the users' files and so on.
> `/path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini`

On second thought, I'm still having a problem:

https://imgur.com/a/HmgEJUb

Even the password inside the application.ini file is not working. The original didn't work, so I changed it to "password", saved, restarted the container, and it still doesn't work.

I am also definitely on the admin login page, which the URL displays.

**Comment by pierre-alain-b** [comment]
I guess this is not the good application.ini file. Are you absolutely sure you have no other application.ini file in the whole storage?

**Comment by doublemultiply** [comment]
> I guess this is not the good application.ini file. Are you absolutely sure you have no other application.ini file in the whole storage?

The path for this one was: \nextcloud\rainloop-storage\_data_\_default_\configs
So I can't imagine it would be any others.

I fixed the issue by uninstalling Rainloop and deleting the entire rainloop-storage folder as root, then upon reinstalling, the password went back to 12345.
Not sure why entering the password at application.ini didn't work for me.

**Comment by pierre-alain-b** [comment]
perfect, thank you for the feedback

**Comment by doublemultiply** [comment]
> perfect, thank you for the feedback

Also I checked the application.ini file for my fresh installation; it's another randomly generated 20+character password like the one from my previous installation.
I just changed my password inside the admin panel to something I will remember, but the application.ini file still has the generated one. Hope that helps.
