### ISSUE TITLE
stream_socket_client() error

### ISSUE THREAD

**Issue by angarod** [pierre-alain-b/rainloop-nextcloud#22]
With a fresh install of Nextcloud 12, i installed Rainloop as a application from the official apps store, Rainloop show me this error with gmail default conf : : unable to connect to tcp://smtp.gmail.com:587 (Connection timed out)

The related log is : [12:27:00.031][500e0e34] AJAX[DATA]: {"Action":"AdminDomainTest","Result":{"Imap":true,"Smtp":"stream_socket_client(): unable to connect to tcp:\/\/smtp.gmail.com:587 (Connection timed out)","Sieve":true},"Time":5065}
I'm new in the Nextcloud universe, you may help me ! 
Thanks

**Comment by pierre-alain-b** [comment]
It does not seem to be an issue with Rainloop@nextcloud, but apparently an issue with your settings for Gmail.

I recommend to:
* Check if your server has correct DNS (to resolve smtp.gmail.com)
* Check if your server can reach external IPs
* Check if the settings for Gmail SMTP are correct (you use port 587, have you activated tls?)

**Comment by angarod** [comment]
my bad : my nextcloud instance is hosted on scaleway and the "security group" was blocking all smtp traffic
https://community.online.net/t/solved-smtp-connection-blocked/2262 if it can help
