### ISSUE TITLE
Unable to send messages: "Can't send message"

### ISSUE THREAD

**Issue by elhananjair** [pierre-alain-b/rainloop-nextcloud#220]
Hello there I was trying rainloop on nextcloud recently, I liked how fast it is when it loads, but I couldn't send a new message. It shows "Can't send message", there is no error shown in log file. I turned on "Allow low secured apps" in gmail setting and after that I could logged in to my account. Sometimes it shows an error but its already sent, and now its not sending any messages.  

I am using the latest stable  Nextcloud version [20.0.7]

Thanks 
![Rainloop](https://user-images.githubusercontent.com/69236638/107208552-d460c780-6a12-11eb-9d75-536a7582e362.png)

**Comment by elhananjair** [comment]
> Hello there I was trying rainloop on nextcloud recently, I liked how fast it is when it loads, but I couldn't send a new message. It shows "Can't send message", there is no error shown in log file. I turned on "Allow low secured apps" in gmail setting and after that I could logged in to my account. Sometimes it shows an error but its already sent, and now its not sending any messages.
> 
> I am using the latest stable Nextcloud version [20.0.7]
> 
> Thanks
> ![Rainloop](https://user-images.githubusercontent.com/69236638/107208552-d460c780-6a12-11eb-9d75-536a7582e362.png)

Here is log files that I found now.

[04:47:30.930][90d3c528] AJAX[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":301,"ErrorMessage":"","ErrorMessageAdditional":"","Time":257443}
[04:47:30.932][90d3c528] IMAP[ERROR]: MailSo\Net\Exceptions\SocketUnreadBufferException: MailSo-Net-Exceptions-SocketUnreadBufferException (NetClient.php ~ 434) in /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Net/NetClient.php:434
Stack trace:
#0 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(1792): MailSo\Net\NetClient->sendRaw()
#1 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(1832): MailSo\Imap\ImapClient->SendRequest()
#2 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(395): MailSo\Imap\ImapClient->SendRequestWithCheck()
#3 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Mail/MailClient.php(119): MailSo\Imap\ImapClient->Logout()
#4 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/MailSo/Mail/MailClient.php(141): MailSo\Mail\MailClient->Logout()
#5 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(400): MailSo\Mail\MailClient->LogoutAndDisconnect()
#6 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(264): RainLoop\Actions->BootEnd()
#7 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#8 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#9 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/app/handle.php(94): RainLoop\Service::Handle()
#10 /var/www/html/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/include.php(228): include('/var/www/html/n...')
#11 /var/www/html/nextcloud/apps/rainloop/app/index.php(23): include('/var/www/html/n...')
#12 /var/www/html/nextcloud/apps/rainloop/lib/Controller/PageController.php(105): include('/var/www/html/n...')
#13 /var/www/html/nextcloud/apps/rainloop/lib/Controller/PageController.php(67): OCA\RainLoop\Controller\PageController->app()
#14 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(169): OCA\RainLoop\Controller\PageController->appPost()
#15 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(100): OC\AppFramework\Http\Dispatcher->executeController()
#16 /var/www/html/nextcloud/lib/private/AppFramework/App.php(152): OC\AppFramework\Http\Dispatcher->dispatch()
#17 /var/www/html/nextcloud/lib/private/Route/Router.php(309): OC\AppFramework\App::main()
#18 /var/www/html/nextcloud/lib/base.php(1008): OC\Route\Router->match()
#19 /var/www/html/nextcloud/index.php(37): OC::handleRequest()
#20 {main}

**Comment by pierre-alain-b** [comment]
Please refer to https://github.com/RainLoop/rainloop-webmail/issues/1304  as this seems to be a bug in Rainloop itself

**Comment by elhananjair** [comment]
> Please refer to [RainLoop/rainloop-webmail#1304](https://github.com/RainLoop/rainloop-webmail/issues/1304) as this seems to be a bug in Rainloop itself

that issue opened like 4 years ago and didn't get fixed yet... if sending message is not working what's really working?
