### ISSUE TITLE
[Feature request] Rainloop icon in "Applications" menu

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#224]
I propose to add the Rainloop icon for the list of installed applications. Currently, the icon is the default for NC:

![obraz](https://user-images.githubusercontent.com/47037905/110208195-f1f54580-7e87-11eb-8868-34bcc9eb1d98.png)

**Comment by pierre-alain-b** [comment]
Good idea, any PR would be welcome on this :-)

**Comment by pierre-alain-b** [comment]
I think we can use this icon: https://www.rainloop.net/static/img/logo-16x16.png

**Comment by Valdnet** [comment]
The icon must be white and no shadow in svg format 😉.

**Comment by pierre-alain-b** [comment]
And where should it go?

**Comment by Valdnet** [comment]
@pierre-alain-b I will do the PR 😉.

**Comment by Valdnet** [comment]
@pierre-alain-b See PR: #225. Please merge.

**Comment by pierre-alain-b** [comment]
Done
