### ISSUE TITLE
App crashes after the new rainloop update 7.1.1

### ISSUE THREAD

**Issue by elhananjair** [pierre-alain-b/rainloop-nextcloud#226]
Hello there I couldn't log out from nextcloud after I updated rainloop to the latest version 7.1.1. When I click on mail app its shows [105] Missing version directory error. 

Is there any way to fix this?

**Comment by pierre-alain-b** [comment]
What is your nextcloud version?

**Comment by pierre-alain-b** [comment]
Can you try to uninstall the app and reinstall it? Does it change something?

**Comment by elhananjair** [comment]
> What is your nextcloud version?

my nextcloud version is 20.0.8

**Comment by elhananjair** [comment]
> Can you try to uninstall the app and reinstall it? Does it change something?

okay let me try that

**Comment by elhananjair** [comment]
> > Can you try to uninstall the app and reinstall it? Does it change something?
> 
> okay let me try that

![rainloop](https://user-images.githubusercontent.com/69236638/110291544-16bef980-7ffd-11eb-8492-c938f783bdcb.png)

Still nothing changed...

This is the log 


[05:06:36.870][83e1637b] INFO[DATA]: [DATE:08.03.21][OFFSET:-00][RL:1.14.0][PHP:7.4.14][IP:192.168.100.16][PID:453751][Apache/2.4.46 (Fedora) OpenSSL/1.1.1i][fpm-fcgi]
[05:06:36.870][83e1637b] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:pgsql,sqlite][cloud:true][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[05:06:36.870][83e1637b] REQUEST[NOTE]: [GET] https://nextacso.com/logout?requesttoken=6S3iyzE0MJot6Dv4Plqs6Nbd%2BMDUo77GYM6IZjrF3f4%3D%3Au26j%2F30BXexqmUipVhjD0eKR15O34c2AOvujNEO9mZ0%3D
[05:06:37.061][83e1637b] INFO[MEMORY]: Memory peak usage: 2MB
[05:06:37.062][83e1637b] INFO[TIME]: Time delta: 0.21023011207581

**Comment by pierre-alain-b** [comment]
I cannot replicate as of now. Can you check file access rights on the rainloop app folder and its subfolders?

**Comment by elhananjair** [comment]
> I cannot replicate as of now. Can you check file access rights on the rainloop app folder and its subfolders?

Actually I didn't changed anything, I just did occ command from cli to update it. But I will check it out.

**Comment by elhananjair** [comment]
![rainloop](https://user-images.githubusercontent.com/69236638/110423113-8db5ca00-80b1-11eb-9b12-71efa6aa5866.png)
![rainloop2](https://user-images.githubusercontent.com/69236638/110423116-8e4e6080-80b1-11eb-940b-b8ebe7cf9b32.png)


@pierre-alain-b  the owner of the folder is apache user just like other app folders, I dont see any other difference from other apps regarding rights to write and read.

**Comment by pierre-alain-b** [comment]
Could you try this:
```
cd /path/to/nextcloud/apps
chown -R apache:apache rainloop
```

This error kicks in when this code fails:

```
if (!defined('APP_VERSION'))
{
	define('APP_VERSION', '1.15.0');
	define('APP_VERSION_TYPE', 'community');
	define('APP_INDEX_ROOT_FILE', __FILE__);
	define('APP_INDEX_ROOT_PATH', str_replace('\\', '/', rtrim(dirname(__FILE__), '\\/').'/'));
}

if (file_exists(APP_INDEX_ROOT_PATH.'rainloop/v/'.APP_VERSION.'/include.php'))
{
	include APP_INDEX_ROOT_PATH.'rainloop/v/'.APP_VERSION.'/include.php';
}
else
{
	echo '[105] Missing version directory';
	exit(105);
}
```

Could you confirm the file `/path/to/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/include.php` does exist and is readble for user apache?

**Comment by elhananjair** [comment]
> Could you try this:
> 
> ```
> cd /path/to/nextcloud/apps
> chown -R apache:apache rainloop
> ```
> 
> This error kicks in when this code fails:
> 
> ```
> if (!defined('APP_VERSION'))
> {
> 	define('APP_VERSION', '1.15.0');
> 	define('APP_VERSION_TYPE', 'community');
> 	define('APP_INDEX_ROOT_FILE', __FILE__);
> 	define('APP_INDEX_ROOT_PATH', str_replace('\\', '/', rtrim(dirname(__FILE__), '\\/').'/'));
> }
> 
> if (file_exists(APP_INDEX_ROOT_PATH.'rainloop/v/'.APP_VERSION.'/include.php'))
> {
> 	include APP_INDEX_ROOT_PATH.'rainloop/v/'.APP_VERSION.'/include.php';
> }
> else
> {
> 	echo '[105] Missing version directory';
> 	exit(105);
> }
> ```
> 
> Could you confirm the file `/path/to/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/include.php` does exist and is readble for user apache?
![index](https://user-images.githubusercontent.com/69236638/110582099-b8208980-817c-11eb-9b7f-07799317b099.png)

Include.php file does exist and apache user can read it. 

2hours ago I have installed the one you updated and now it totally blocks me from using my NC server.
![error](https://user-images.githubusercontent.com/69236638/110582252-fddd5200-817c-11eb-8b2c-b549ff149aa5.png)

**Comment by pierre-alain-b** [comment]
7.1.2 works fine on my instance

What does the apache log say? We need to find out what the internal server error is...

**Comment by elhananjair** [comment]
> 7.1.2 works fine on my instance
> 
> What does the apache log say? We need to find out what the internal server error is...

This really odd, apache error_log file doesnt say anything regarding this issue, the access_log actually doesn't matter and no odd thing found. 

And this is from nextcloud.log, 

_"reqId":"YEhcviBUmhfMU4u9ZhcYvAAAgRQ","level":3,"time":"2021-03-10T05:44:30+00:00","remoteAddr":"192.168.100.16","user":"Amanuel Kumera","app":"core","method":"GET","url":"/apps/dashboard/","message":{"Exception":"RuntimeException","Message":"image not found: image:mail.png webroot: serverroot:/var/www/html/nextcloud","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/rainloop/lib/AppInfo/Application.php","line":76,"function":"imagePath","class":"OC\\URLGenerator","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/NavigationManager.php","line":110,"function":"OCA\\RainLoop\\AppInfo\\{closure}","class":"OCA\\RainLoop\\AppInfo\\Ap>_

**Comment by pierre-alain-b** [comment]
@Valdnet this seems to be related with the image change: "image not found: image:mail.png". Wouldn't it make sense to add again the mail.png image just in case?

**Comment by Valdnet** [comment]
@pierre-alain-b There is no link to the `mail.png` file in the code. So most likely something went wrong during the upgrade and old files remained.

@elhananjair I suggest uninstalling the application. Check if the `rainloop` directory has been deleted, clear the cache and reinstall it.

**Comment by pierre-alain-b** [comment]
@Valdnet and yet we removed mail.png here:
https://github.com/pierre-alain-b/rainloop-nextcloud/commit/1c11288f0ec4e0dfdbaf6b0b09b02da190d421d4

**Comment by pierre-alain-b** [comment]
@elhananjair maybe you can download the mail.png file here: https://raw.githubusercontent.com/pierre-alain-b/rainloop-nextcloud/7.1.1/img/mail.png
and copy it in the img folder so that it will be found again.
But I agree there seems to be strange issues as under the new version mail.png is not referred anymore in the code.
Are you sure the upgrade was made fully?

**Comment by pierre-alain-b** [comment]
Like @Valdnet  I recommend that you fully delete the rainloop app (check serverside that it is fully deleted) and then reinstall

**Comment by elhananjair** [comment]
> @elhananjair maybe you can download the mail.png file here: https://raw.githubusercontent.com/pierre-alain-b/rainloop-nextcloud/7.1.1/img/mail.png
> and copy it in the img folder so that it will be found again.
> But I agree there seems to be strange issues as under the new version mail.png is not referred anymore in the code.
> Are you sure the upgrade was made fully?

@pierre-alain-b  The upgrade of what? nextcloud? yes 20.0.8, and rainloop, yes I have just uninstalled it and then installed the current one. 
I will try to download the image you have said and try once again

**Comment by Valdnet** [comment]
> and yet we removed mail.png here:

@pierre-alain-b Yes. The file has been removed because no code is referencing it anymore. So the file is redundant 😉.

**Comment by Valdnet** [comment]
> 
> 
> @Valdnet and yet we removed mail.png here:
> [1c11288](https://github.com/pierre-alain-b/rainloop-nextcloud/commit/1c11288f0ec4e0dfdbaf6b0b09b02da190d421d4)
@pierre-alain-b Yes. The file has been removed because no code is referencing it anymore 😉.

**Comment by elhananjair** [comment]
> > and yet we removed mail.png here:
> 
> @pierre-alain-b Yes. The file has been removed because no code is referencing it anymore. So the file is redundant 😉.

@Valdnet but my nextcloud.log shows like that file is still being accessed.

BTW i didnt touched the database, does that cause errors too? I have created a database user that rainloop uses and didn't touched it.

**Comment by Valdnet** [comment]
@elhananjair Have you deleted files from the cache?
Path: `/data/rainloop-storage/_data_/_default_/cache`

**Comment by elhananjair** [comment]
> @elhananjair maybe you can download the mail.png file here: https://raw.githubusercontent.com/pierre-alain-b/rainloop-nextcloud/7.1.1/img/mail.png
> and copy it in the img folder so that it will be found again.
> But I agree there seems to be strange issues as under the new version mail.png is not referred anymore in the code.
> Are you sure the upgrade was made fully?

_{"reqId":"YEiaTlzC-m@7GIHXDh29@wAAAFM","level":3,"time":"2021-03-10T10:07:10+00:00","remoteAddr":"192.168.15.34","user":"Anteneh Kebere","app":"no app in context","method":"GET","url":"/ocs/v2.php/core/navigation/apps?absolute=true&format=json","message":{"Exception":"RuntimeException","Message":"image not found: image:mail.png webroot: serverroot:/var/www/html/nextcloud","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/rainloop/lib/AppInfo/Application.php","line":76,"function":"imagePath","class":"OC\\URLGenerator","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/NavigationManager.php","line":110,"function":"OCA\\RainLoop\\AppInfo\\{closure}","class":"OCA\\RainLoop\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/core/Controller/NavigationController.php","line":56,"function":"getAll","class":"OC\\NavigationManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getAppsNavigation","class":"OC\\Core\\Controller\\NavigationController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/ocs/v2.php","line":24,"args":["/var/www/html/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/private/URLGenerator.php","Line":236,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.0.2stable-Win64 (build 20200924) (Nextcloud)","version":"20.0.8.1","id":"60489a76331f0"}_


The same log

**Comment by elhananjair** [comment]
> @elhananjair Have you deleted files from the cache?
> Path: `/data/rainloop-storage/_data_/_default_/cache`

@Valdnet Am sorry I didn't let me delete it.

**Comment by elhananjair** [comment]
> @elhananjair Have you deleted files from the cache?
> Path: `/data/rainloop-storage/_data_/_default_/cache`

@Valdnet I deleted everything inside cache folder and tried installing rainloop, and still the same error. 

![rainloop error](https://user-images.githubusercontent.com/69236638/110614286-3abc3f80-81a3-11eb-8420-98ac11e3c94c.png)

**Comment by Valdnet** [comment]
@elhananjair Have you done this:
> maybe you can download the mail.png file here: https://raw.githubusercontent.com/pierre-alain-b/rainloop-nextcloud/7.1.1/img/mail.png
> and copy it in the img folder so that it will be found again.

Copy the file [mail.png](https://raw.githubusercontent.com/pierre-alain-b/rainloop-nextcloud/7.1.1/img/mail.png) to `/apps/rainloop/img`.

You may find that you have an old `Application.php` file before making these changes to 1c11288.


If the application works correctly, check if you have the appropriate icon file name in this line in the file on the server:
https://github.com/pierre-alain-b/rainloop-nextcloud/blob/0c3177eb1af938cd65be313bcce7ff342d11ffc5/lib/AppInfo/Application.php#L76

**Comment by elhananjair** [comment]
> @elhananjair Have you done this:
> 
> > maybe you can download the mail.png file here: https://raw.githubusercontent.com/pierre-alain-b/rainloop-nextcloud/7.1.1/img/mail.png
> > and copy it in the img folder so that it will be found again.
> 
> Copy the file [mail.png](https://raw.githubusercontent.com/pierre-alain-b/rainloop-nextcloud/7.1.1/img/mail.png) to `/apps/rainloop/img`.
> 
> You may find that you have an old `Application.php` file before making these changes to [1c11288](https://github.com/pierre-alain-b/rainloop-nextcloud/commit/1c11288f0ec4e0dfdbaf6b0b09b02da190d421d4).
> 
> If the application works correctly, check if you have the appropriate icon file name in this line in the file on the server:
> https://github.com/pierre-alain-b/rainloop-nextcloud/blob/0c3177eb1af938cd65be313bcce7ff342d11ffc5/lib/AppInfo/Application.php#L76

Thank you @pierre-alain-b @Valdnet I really don't know today I tried installing it and it worked no errors. 
Thank you so much. Just as suggestions can you guys write changes made on nextcloud apps site whenever new versions are out.
