### ISSUE TITLE
Rainloop doesn't load after upgrade to Nextcloud 21

### ISSUE THREAD

**Issue by tmlmt** [pierre-alain-b/rainloop-nextcloud#230]
Hi !

Rainloop v7.1.2 doesn't load (blank page) after upgrading to Nextcloud 21.

I find this in my `error.log`:
```
2021/03/16 21:33:45 [error] 399711#399711: *15985 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /var/www/nextcloud/apps/rainloop/app/index.php:8
Stack trace:
#0 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/include.php(57): __get_custom_data_full_path()
#1 /var/www/nextcloud/apps/rainloop/app/index.php(23): include('/var/www/...')
#2 {main}
  thrown in /var/www/nextcloud/apps/rainloop/app/index.php on line 8" while reading response header from upstream, client: ::1, server: cloud.mydomain.com, request: "GET /apps/rainloop/app/?OwnCloudAuth HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "cloud.mydomain.com"
```

**Comment by mixim-mixim** [comment]
... same here ... RainLopp v7.1.2, NC21, PHP v8.0.3

**Comment by sepo83** [comment]
I am running nextcloud 21.0.0 in a container from linuxserver.io (https://github.com/linuxserver/docker-nextcloud/releases/tag/21.0.0-ls129) and had the same issue after nginx config (`nginx/site-confs/default`) was updated according to official nextcloud documentation. 
For me the following workaraound fixed it: https://github.com/nextcloud/documentation/pull/2197#issuecomment-721432337

**Comment by tmlmt** [comment]
Thank you @sepo83 ! It worked for me to. It is then an issue with the new default nginx config of NC21, and not of rainloop-nextcloud itself. I am closing this issue :)

**Comment by mixim-mixim** [comment]
A BIG Thx 4 sepo83, works for me too also ... :+1:  :)
