### ISSUE TITLE
Couldn't constantly connect to IMAP and SMTP ports of Mail Server

### ISSUE THREAD

**Issue by elhananjair** [pierre-alain-b/rainloop-nextcloud#231]
Hello there, before writing anything I want to thank everyone contributing to this wonderful module for nextcloud. Its working for me fine and I like it a lot, but unfortunately its fine and best for Gmail and Yahoo mails. Currently am trying connecting to my mail which I got from mail providers. And when I try testing it connects once and disconnect in other test within a second. It says **connection refused** and on next click of test it will connect fine. I want to know whether this is rainloop problem or my mail service provider. Thanks 

https://user-images.githubusercontent.com/69236638/113412213-5b517100-93c0-11eb-8a4b-ec78957fd081.mp4

**Comment by pierre-alain-b** [comment]
This is certainly coming from the mail provider. The error message you see is the one returned by the mail provider.
