### ISSUE TITLE
Enable the nextcloud functionality to activate app "per user groups"

### ISSUE THREAD

**Issue by beankylla** [pierre-alain-b/rainloop-nextcloud#232]
It would be nice to be able to disable the app for some user groups.

This is possible if the Nextcloud functionality is implemented. (it is available for some apps)

Can't manage to find the documentation relative to that though.

Can gladly help to test if needed :)

**Comment by pierre-alain-b** [comment]
It's a good idea but I've not found either the documentation about this.

**Comment by beankylla** [comment]
my bad!
it's already possible but not via settings just via the store
And that's another functionality for Rainloop ;)

![Screenshot from 2021-06-04 21-40-22](https://user-images.githubusercontent.com/13024650/120854669-c44e9400-c57d-11eb-85de-3ed01d5f41c1.png)
