### ISSUE TITLE
Dashboard widget for unread emails

### ISSUE THREAD

**Issue by diemelone** [pierre-alain-b/rainloop-nextcloud#233]
Since NC20 uses a dashboard, a widget to display unread emails would be great. 
The NC mail app has such a widget but the rest of the app is not really nice to use.
![grafik](https://user-images.githubusercontent.com/46229652/115389170-0cd40d00-a1dd-11eb-8421-e3974869797e.png)

**Comment by pierre-alain-b** [comment]
Unfortunately this seems complicated to do with Rainloop!
