### ISSUE TITLE
Use Nextcloud viewer to open attachments

### ISSUE THREAD

**Issue by pemocarlo** [pierre-alain-b/rainloop-nextcloud#235]
Hi,
How feasible would it be to use the viewer application in Nextcloud to have a preview of the attachments?

BTW, which viewer is being used right now for the images? Was it developed for Rainloop specifically?

Thank you,
Carlos

**Comment by pierre-alain-b** [comment]
Hi there,
Not easy to do as we incorporate Rainloop standalone and all instances cannot be assumed to have NC as a backend!
