### ISSUE TITLE
rainloop see all nextcloud users when creating a new mail

### ISSUE THREAD

**Issue by fab-kaz** [pierre-alain-b/rainloop-nextcloud#238]
Hello all,

In a recent nextcloud instance, i have some nextcloud groups "GROUP1", "GROUP2" 
I belong to GROUP1. When i start a new mail with rainloop, i'd like to see only emails from GROUP1's users. However, i see users from GROUP1 and GROUP2. Is there anything to parameter or is a new feature that doesn't exist yet ?

By the way, thank you for this  awesome work ;)

regards,

Fabrice

**Comment by pierre-alain-b** [comment]
If I remember well, there is a config option named "owncloud_suggestions'. If set to false, the nextcloud users will not be proposed. That said, this does not help to respect the groups.

**Comment by fab-kaz** [comment]
alas, "owncloud_suggestions" set to false didn't do the job. All emails from the instance can be seen when i start a new mail. 
Is it the same parameter i can see in the rainloop admin panel ? 
![Capture d’écran_2021-08-10_12-01-38](https://user-images.githubusercontent.com/12799446/128851136-5d131152-53a0-4541-a5be-c3ec44ac7646.png)

**Comment by pierre-alain-b** [comment]
The "activer les contacts" option is rather the possibility to enable or not the contacts book in Rainloop. But in fact it seems the good option should be "off" and not false, sorry for the mistake. See here: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/95#issuecomment-502429870

Can you try and tell me if is better?

**Comment by fab-kaz** [comment]
thank you @pierre-alain-b for for help ;)

> Can you try and tell me if is better?

nope. but wait... i need to change this file, right ?
`rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Config/Application.php`
I wrote ` 'owncloud_suggestions' => array('off')`but without succes.

Btw, it seems this ticket is the same as #95 , no ?

**Comment by fab-kaz** [comment]
Ooops, shame on me.

I need to change the /path/to/nextcloud/data/rainloop-storage/_data_/_default_/configs/application.ini file and not the rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Config/Application.php file.

This is a bit confusing because owncloud_suggestions can be found in both files.
So, `owncloud_suggestions = Off` prevent me for seeing all emails account in rainloop. 

Now, I'd like rainloop can see NC group users email but i guess this won't be done in futur, considering #95. What do you think ? may be the official NC email plugin is able to do so ?

regards,

**Comment by pierre-alain-b** [comment]
The official email app is indeed much better integrated so yes they probably respect the groups much better (as it is done in the core apps of Nextcloud). There is no plan to extend this to Rainloop but always open to receive contributions if someone feels up to the task to do it!

It is not a need for me so I cannot devote time to it myself (and as I am not a Rainloop developer, it would potentially be difficult)!
