### ISSUE TITLE
Sieve filters not working

### ISSUE THREAD

**Issue by MrEgenius** [pierre-alain-b/rainloop-nextcloud#24]
Hello!

Currently I use mail server with postfix+cyrus-imap+roundcubemail. 
It work fine and a can manage sieve rules via roundcubemail web console.
I installed rainloop app in nextcloud and see that sieve filters not working.
I can't see my current sieve rules and can't create new rules.

Nextcloud version- 12.0.2
Rainloop app version - 5.0.1

Please. fix this issue.

**Comment by pierre-alain-b** [comment]
Hi,
Have you had a look here: https://github.com/RainLoop/rainloop-webmail/issues/419?
Does this feature correspond to what you are looking for?
Best
Pierre-Alain

**Comment by MrEgenius** [comment]
I read this thread, but it discusses a full-fledged application. I use rainloop as an add-on to nextcloud and it does not work in it.

**Comment by pierre-alain-b** [comment]
Hi,
There is the Sieve function in the Administration / Domains / Sieve configuration of the Rainloop standalone app (see above thread) and as a consequence this is also present in the Rainloop plugin for Nextcloud. The Rainloop plugin is a copy of the Rainloop standalone app but packaged to fit in Nextcloud.
Unless you experience a bug in the Sieve function, I consider that this ticket is closed.

**Comment by MrEgenius** [comment]
Well, I'll write about the problems in that thread.

**Comment by pierre-alain-b** [comment]
Yes I think this is more appropriate as the functionality comes from the Rainloop standalone app. Here we just handle the integration of Rainloop within Nextcloud.
Best
PAB
