### ISSUE TITLE
[Help Request] Order email

### ISSUE THREAD

**Issue by salsimatia** [pierre-alain-b/rainloop-nextcloud#241]
Hello,
I use rainloop ver. 7.1.2 in NextCloud (Ver. 20.00.10).
The sorting of emails has changed for a few weeks.
From decreasing chronological order (the most recent emails at the top) to ascending (the oldest at the top).

Is it possible to change the order?

Thank you

**Comment by pierre-alain-b** [comment]
This is weird as it has not changed. So I guess this is instance-specific.
Here you can find some info on the code handling the sort in Rainloop: https://github.com/RainLoop/rainloop-webmail/issues/1817
But if the question is revolving around Rainloop itself, I suggest to ask the question to Rainloop people here: https://github.com/RainLoop
