### ISSUE TITLE
How to replace the rainloop library with a fork?

### ISSUE THREAD

**Issue by pemocarlo** [pierre-alain-b/rainloop-nextcloud#242]
Hi,
I would like to use this app with a fork of the rainloop-webmail.
I built it, created the zip file and then extracted it and replaced the contents of the `app` folder with it.

Unfortunately, I get the following error in Nextcloud.
`[202] Data folder permissions error [is_writable]`

I guess I am missing steps to replace the Rainloop library. Could you please give me some hints about how to correctly do it?

Thanks in advance.

**Comment by beankylla** [comment]
i think this is linked to https://github.com/pierre-alain-b/rainloop-nextcloud/issues/246
