### ISSUE TITLE
Rainloop Update to 1.16.0

### ISSUE THREAD

**Issue by ghost** [pierre-alain-b/rainloop-nextcloud#243]
New version is 1.16. About how long do updates take to get pushed?

**Comment by beankylla** [comment]
based on the free time / work of a non payed volunteer. Updates can be pushed tomorrow if you make them :)

**Comment by pierre-alain-b** [comment]
Thank you for the info, in fact I've not noticed 1.16 was out. The process if more complicated than it was because we had to make some changes in the core of Rainloop to accommodate some changes in NC 20 and 21. So now we have to backport these changes to Rainloop 1.16 before shipping. I will try to have a look at it!

**Comment by ghost** [comment]
Thanks @pierre-alain-b , I know this is not a full time project, so my question was just that, not a rush :)

I appreciate the hard work you do on this project!

**Comment by hydrian** [comment]
Anything we can do to help roll out the update with the RainLoop 1.16.0 release? I'm waiting on the #263 also. I'm a PHP dev, if there any thing I can do to help, let me know.

**Comment by pierre-alain-b** [comment]
Well the point is that I remember some changes were made by contributors to the Rainloop files themselves when embedded into the plugin but this was not tracked in due details so it's painful to decide what needs to be done on 1.16. I have just pushed a "fool attempt": just replacing 1.15 with 1.16. See the release section - I will try it on my NC, maybe you can do the same before we push it officially as an update if it seems to work?

**Comment by pierre-alain-b** [comment]
Could you give a try to https://github.com/pierre-alain-b/rainloop-nextcloud/releases/tag/7.2.0 and let me know if it works? It seems to work on my NC instance but my setting is also pretty simple so it is definitely not testing all use cases !!

**Comment by pierre-alain-b** [comment]
See #267 as well

**Comment by pierre-alain-b** [comment]
I will wait for a couple of days and I will then officially release the update.

**Comment by JordanDIG** [comment]
> I will wait for a couple of days and I will then officially release the update.

Thanks :)

**Comment by expert-geeks** [comment]
Upgrade seems to have worked OK and rainloop is working. However since I installed the beta, I'm getting the error;
Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the [documentation](https://docs.nextcloud.com/server/20/go.php?to=admin-code-integrity). ([List of invalid files…]

The file is core/js/mimetypelist.js, I've tried regenerating it as recommended with;

To regenerate this file run ./occ maintenance:mimetype:update-js

but it's still coming up as failing integrity.

**Comment by hydrian** [comment]
@expert-geeks That isn't uncommon when you update things outside of the occ upgrade or via the webinterface. NC keeps checksums of the last know versions of the file. As beta tester, you often download and install outside the normal means. 

I think there was an occ command to update it. take a look at 
`occ integrity:sign-app`

**Comment by expert-geeks** [comment]
Apologies, hydrian I deleted my original post. As you've replied, here's the error I'm getting on the integrity check. Is mimetypelist.js affected by the beta rainloop upgrade ? Might be completely unrelated as there are other reports of similar errors.

            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 23a3fa45757b26795f5cf8f94d9e5bce76fc916288a6458679311b312c167adcf4158ccb2c5c3db791fa0b87703b6c5863afb6c9d790b8cbac5ab3ae8c3418fb
                            [current] => 248b1c46827f16075a92457d368b5f8c1c6d39c8dc8569e248b35443ac035501b86b8f46785cc6fb3f12fc8445284829c1e27aa82097a53d2688040b1de7da26

With regards to your suggestion, I'm not sure it's something I can fix myself as I'd need the key and the cert? 

`This command requires the --path, --privateKey and --certificate.
Example: ./occ integrity:sign-app --path="/Users/lukasreschke/Programming/myapp/" --privateKey="/Users/lukasreschke/private/myapp.key" --certificate="/Users/lukasreschke/public/mycert.crt"
 For more information please consult the documentation: https://docs.nextcloud.com/server/20/go.php?to=developer-code-integrity`

I'll hang on until the official update is released by Pierre-Alain in that case & see if it resolves.

**Comment by pierre-alain-b** [comment]
Official update released!
