### ISSUE TITLE
Compatibility releases for new Nextcloud versions

### ISSUE THREAD

**Issue by Aquariu** [pierre-alain-b/rainloop-nextcloud#244]
Dear all,
NC21 has been released a couple of monthe ago, NC22 is just around the corner.
Is there any plan to test the compability of the existing app to release a NC22-compatible version with minimal efforts?

Kind regards,

Olivier

**Comment by Valdnet** [comment]
I have installed Rainloop version 7.1.2 on an NC22 RC2 instance and it works for me 😉.

**Comment by pierre-alain-b** [comment]
I confirm this should work with NC22 already
