### ISSUE TITLE
Missing config

### ISSUE THREAD

**Issue by siruscool** [pierre-alain-b/rainloop-nextcloud#245]
Hello all,

i have an issue regarding the Nextcloud RainLoop plugin.

I have installed them and i dont can login into the admin panel with admin and pw 12345.

I have cheked this location root@b428bf61c7ec:/data/rainloop-storage/_data_/_default_/configs#  for the application.ini but this folder is empty.

I have create an application.ini file with the following content:

allow_admin_panel on
Username: admin
Password: 12345

but it does not work for me.

After that i have removed the plugin from my nextcloud instances and then i have reinstall the plugin but the situation is the same.

The plugin does not create the application.ini file.

Is it possible to send me template?

Or is there a other way what can i do to solve the issue with no login into the admin panel.

**Comment by pierre-alain-b** [comment]
Hi there, I guess you need to check again your data folder. If I remember well the application.ini is created after a first call to the application. Have you managed to open the application a first time?
Or are you in this case? https://github.com/RainLoop/rainloop-webmail/issues/1685

I have no template of the application.ini but it is close to this one:
https://github.com/gyxuehu/EwoMail/blob/master/rainloop/data/_data_/_default_/configs/application.ini
