### ISSUE TITLE
Snappy fork ?

### ISSUE THREAD

**Issue by Mer0me** [pierre-alain-b/rainloop-nextcloud#246]
There is a fork of rainloop name SnappyMail : https://github.com/the-djmaze/snappymail
It seems to be very fast and modern compared to rainloop.
What about a SnappyMail nextcloud integration ?

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/issues/96

**Comment by beankylla** [comment]
+1 :) 
Ca devrait pas être trop dur pour vous Pierre-Alain si? :)

**Comment by pierre-alain-b** [comment]
Well I've seen they have made a lot of changes in this fork. I am not sure this will so easy but I have not (yet ?) given it a try. Quite time-constrained for the moment. And I am not the original author of the Rainloop plugin for nextcloud, I am maintaining it on my spare time but with limited knowledge of the core Rainloop code.

**Comment by pierre-alain-b** [comment]
Anyway, this would be a different project - so I will close this issue but I invite everyone trying to report here on any progress!
