### ISSUE TITLE
Unable to sync contacts

### ISSUE THREAD

**Issue by localweights** [pierre-alain-b/rainloop-nextcloud#247]
Using NC22

When trying to sync contacts using CardDAV to my nextcloud instance, I get the below error

![Screenshot 2021-07-21 at 11 13 52](https://user-images.githubusercontent.com/22432139/126472849-fe77760e-0bc6-47e5-bc2a-51450c13b0cb.png)

I've configured the backend against MySQL and confirmed that Rainloop has created tables in the database (rainloop_ab_contacts, rainloop_ap_properties, rainloop_system and rainloop_users), so permissions are fine.

I've tried the below URLs,

In Nginx I see the below access logs. It looks like /nextcloud/remote.php/dav is giving an HTTP 401, but my password is definitely correct in the contact sync config. I'm using 2FA, I have tried with my user password and a generated App password

```
127.0.0.1 - - [21/Jul/2021:10:17:12 +0000] "PROPFIND /.well-known/carddav HTTP/2.0" 301 162 "-" "RainLoop DAV Client"
127.0.0.1 - - [21/Jul/2021:10:17:13 +0000] "PROPFIND /nextcloud/remote.php/dav HTTP/2.0" 401 450 "-" "RainLoop DAV Client"
```

CardDAV is working fine on my Mac and phone

**Comment by pierre-alain-b** [comment]
Please check in the NC log why it is returning 401... but clearly it seems the NC server is saying "unauthorized access"... so the issue seems to be on the username/password or authorization on the NC server side
