### ISSUE TITLE
Nextcloud Snap & Rainloop Contacts Database

### ISSUE THREAD

**Issue by KvoiceOxford** [pierre-alain-b/rainloop-nextcloud#248]
I cannot find a way to link to the MySQL database for Rainloop Contacts in my default Nextcloud Snap. I'm looking at the Rainloop admin setup for Contacts including the line: 'mysql:host=127.0.0.1;port=3306;dbname=rainloop'. I'm also looking at the prompts for database user and database password. Are these these the MySQL credentials for the Nextcloud database? I'm sorry, but I'm really lost about how to get my Contacts included in Rainloop. Can you help me by telling me precisely what these settings ought to be within a standard default instance of the Nextcloud Snap instance? Thank you.

**Comment by pierre-alain-b** [comment]
No you are taking the wrong way.
The database is to store the Rainloop contact - not to access the Nextcloud database. In fact, Rainloop is an independent tool and comes with its own sqlite database (but other databases can be set up).
To import/sync contacts from Nextcloud, each user needs to use the CardDav sync protocol here in the Rainloop personal settings > Contacts tab:

![image](https://user-images.githubusercontent.com/386857/129878031-07c3c342-f330-4c0d-b3e8-4545c1e29058.png)
