### ISSUE TITLE
Google integration does not work

### ISSUE THREAD

**Issue by jiriks74** [pierre-alain-b/rainloop-nextcloud#249]
Hi,
I tried to integrate my rainloop with gmail. If I use the urls that are in the integration settings I get redirected to nextcloud dashboard not to rainloop. If I manually modify the url to one that is the nextcloud/index.php/apps/rainloop/?SocialGoogle it's just stuck at the loading animation.

I'm probably setting it up wrong, but I couldn't find any information about setting it up with nextcloud rainloop client on the internet.

Can you help? Thanks

**Comment by pierre-alain-b** [comment]
I am not sure I understand what you have tried. Could you give more details please?

**Comment by jiriks74** [comment]
I tried to setup google integration according to the [official guide](https://www.rainloop.net/docs/social/). So if you run rainloop normally you're supposed to authorized redirect url like `http://domain.com/?SocialGoogle` (as in guide). 

But if you do `nextcloud.example.com/?SocialGoogle` you logically get redirected to nextcloud dashboard once you log in with google. 
So I tried `https://nextcloud.example.com/index.php/apps/rainloop/app/?SocialGoogle` but that gives me an error that I have wrong redirect url: `https://nextcloud.exampla.com/?SocialGoogle` and we know what that one does.

So one does not work and the other redirects me to the dashborad.

**Comment by pierre-alain-b** [comment]
When integrated into nextcloud, I am not sure this integration can work.

**Comment by jiriks74** [comment]
Would it be possible to set the redirect url to somethin else in the nextcloud version? If you access `https://nextcloud.example.com/index.php/apps/rainloop/app/?SocialGoogle` it redirects you to the login and everything looks working. It looks like there's something that is made to take the base url (`rainloop.example.com` - in this case `nextcloud.example.com`) and do just `/?SocialGoogle`. If that's the case, changing it to `/index.php/apps/rainloop/app/?SocialGoogle` would probably easily resolve the issue. But idk how rainloop works internally.

**Comment by jiriks74** [comment]
@pierre-alain-b 
I don't know php, but I found something related to social in [/app/rainloop/v/1.15..0/app/libraries/Rainloop/Social.php](https://github.com/pierre-alain-b/rainloop-nextcloud/blob/master/app/rainloop/v/1.15.0/app/libraries/RainLoop/Social.php) on line 229. Maybe that could be it?

**Comment by jiriks74** [comment]
Changing the line from `index.php/apps/rainloop/app/?SocialGoogle` to `index.php/apps/rainloop/app/?SocialGoogle` redirects me to the correct site (with the big g with loading animation) but it's stuck there

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
