### ISSUE TITLE
sieve filters problem 

### ISSUE THREAD

**Issue by Germwalker** [pierre-alain-b/rainloop-nextcloud#250]
Hello, 

I had a working rainloop - nextcloud setup but since some weeks, the sieve filter implementation isn't working anymore. My previous rules are working on the server but i cannot setup new rules. The error i got in options -> filter is "Impossible d'obtenir les filtres - Impossible to obtain filters". 

My mail server is located at gandis.net and their sieve configuration did not change. 
The nextcloud version is 22.1.1.

Here is the configuration i use for gandis.net mail servers, it do not pass the test : 
![image](https://user-images.githubusercontent.com/56682696/135299566-41e5081b-bc3a-4d30-82d1-7ba44f472812.png)

Here is the nextcloud.log trace : 

`{"reqId":"loUZXLcM3ZmJrS33ddff","level":3,"time":"2021-09-29T15:02:16+00:00","remoteAddr":"xx.xx.xx.xx","user":"xxx","app":"PHP","method":"POST","url":"/apps/rainloop/app/?/Ajax/&q[]=/_Y5BPUqSBpx2QBQmKBWmKK326OBW1UlbJ8QwLAVLLOp-FdOzQ5giuDdS0i1Ydea5xhCvZIO1iZF8PYgJp7L8h_X1dVVONsXx4WmbG7tMNs2465JT_kcfDRDjjA1xLSANZjtdTwzlUalmh8T4v6piUbg2ggXaquJwPyrKMHqx22fIGdiFtrXnI8Ko9IkdV6yJZ8BXJImfMHObj5hN1_ggJBFnu-kJj-dGZVnnpu3yV4YEEg8oSIY7wZO_PQV0Bm-pWujpUtC5HNkJkwKP_kMKIlomauJGOpzWxAtMkjvKF8S_QpYla3whlG0KRu8Q4rtReFosQpc74BsXSRopPB2-mBeeAzKuuHfLFp9aUtNDDsBndBjmzQhHk2t7pHgF8l91y/","message":"Declaration of MailSo\\Sieve\\ManageSieveClient::Connect($sServerName, $iPort, $iSecurityType = MailSo\\Net\\Enumerations\\ConnectionSecurityType::AUTO_DETECT, $bVerifySsl = false, $bAllowSelfSigned = true) must be compatible with MailSo\\Net\\NetClient::Connect($sServerName, $iPort, $iSecurityType = MailSo\\Net\\Enumerations\\ConnectionSecurityType::AUTO_DETECT, $bVerifySsl = false, $bAllowSelfSigned = true, $sClientCert = '') at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/app/libraries/MailSo/Sieve/ManageSieveClient.php#114","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"22.1.1.2"}`

Best regards

**Comment by tormodvolden** [comment]
Try applying this patch:
```
--- /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/app/libraries/MailSo/Sieve/ManageSieveClient.php.orig	2021-04-12 19:28:12.259143838 +0200
+++ /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/app/libraries/MailSo/Sieve/ManageSieveClient.php	2021-10-03 10:53:26.983914369 +0200
@@ -113,11 +113,11 @@ class ManageSieveClient extends \MailSo\
 	 */
 	public function Connect($sServerName, $iPort,
 		$iSecurityType = \MailSo\Net\Enumerations\ConnectionSecurityType::AUTO_DETECT,
-		$bVerifySsl = false, $bAllowSelfSigned = true)
+		$bVerifySsl = false, $bAllowSelfSigned = true, $sClientCert = '')
 	{
 		$this->iRequestTime = \microtime(true);
 
-		parent::Connect($sServerName, $iPort, $iSecurityType, $bVerifySsl, $bAllowSelfSigned);
+		parent::Connect($sServerName, $iPort, $iSecurityType, $bVerifySsl, $bAllowSelfSigned, $sClientCert = '');
 
 		$mResponse = $this->parseResponse();
 		$this->validateResponse($mResponse);
```

**Comment by Germwalker** [comment]
Heya,

It's now working ! Thanks alot for the quick fix. 

Best regards

**Comment by pierre-alain-b** [comment]
Thank you for the fix!

**Comment by pierre-alain-b** [comment]
I have checked in Rainloop v1.16 and only the first change seems to be there. I assume it might be enough to fix?
If yes, I will close the issue and refer to the issue requesting version update #243.

**Comment by Germwalker** [comment]
I can confirm tormodvolden's fix is working on Nexcloud 23.
