### ISSUE TITLE
Rainloop app doesn't work when front_controller_active is enabled

### ISSUE THREAD

**Issue by msva** [pierre-alain-b/rainloop-nextcloud#252]
Hi there!
I just found that if I enable `front_controller_active` option (as environment variable for PHP backend), which makes NextCloud to use "pretty urls" (without `/index.php`), RainLoop stops working and starts to behave like this:

![image](https://user-images.githubusercontent.com/268102/139660908-1a107260-92fc-4bcc-9161-d77bc8cea4b1.png)

(it's frame loads copy of the default NextCloud app instead of RainLoop interface)

Disabling `front_controller_active` makes it work again.

**Comment by pierre-alain-b** [comment]
Rainloop for nextcloud cannot work when tampering with the URLs!

**Comment by msva** [comment]
> Rainloop for nextcloud cannot work when tampering with the URLs!

Well, actually, that environment variable is enabled by default on NextCloud installatons using Apache as web-server.

I know it because I took it from NC's default `.htaccess` file.

So, do you mean `rainloop-nextcloud` doesn't work for all the apache users? O_o

**Comment by pierre-alain-b** [comment]
Well I have never had any issue on my side neither with nginx or apache... but I haven't tried a fresh install for a long time!
