### ISSUE TITLE
Error: Undefined variable $sPasswordSalt

### ISSUE THREAD

**Issue by Emporea** [pierre-alain-b/rainloop-nextcloud#253]
NC: 22.2
Rainloop-DB: sqlite
Rainloop: latest

When opening Rainloop its sometimes stuck at the login page, even though I checked "Remember me".
After a minute or so it logs successfully into the account, without changing any login details.

But the log shows these

```
[PHP] Error: Undefined variable $sPasswordSalt at /var/www/html/custom_apps/rainloop/lib/Controller/PageController.php#99

GET /apps/rainloop/app/?OwnCloudAuth
from x.x.x.x by emporea at 2021-11-03T16:56:39+00:00
```

`{"reqId":"t1yvJx8Np3Pu2iTyIjrQ","level":3,"time":"2021-11-03T16:56:39+00:00","remoteAddr":"x.x.x.x","user":"emporea","app":"PHP","method":"GET","url":"/apps/rainloop/app/?OwnCloudAuth","message":"Undefined variable $sPasswordSalt at /var/www/html/custom_apps/rainloop/lib/Controller/PageController.php#99","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"22.2.0.2","exception":{"Exception":"Error","Message":"Undefined variable $sPasswordSalt at /var/www/html/custom_apps/rainloop/lib/Controller/PageController.php#99","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/rainloop/lib/Controller/PageController.php","line":99,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined variable $sPasswordSalt","/var/www/html/custom_apps/rainloop/lib/Controller/PageController.php",99]},{"file":"/var/www/html/custom_apps/rainloop/lib/Controller/PageController.php","line":59,"function":"app","class":"OCA\\RainLoop\\Controller\\PageController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"appGet","class":"OCA\\RainLoop\\Controller\\PageController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\RainLoop\\Controller\\PageController"},"appGet"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\RainLoop\\Controller\\PageController"},"appGet"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["PageController","appGet",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"rainloop.page.appGet"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/rainloop/app/"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6182bfb1d83a2"}`

```
[PHP] Error: RainLoop\Actions::RainLoop\{closure}(): Argument #1 ($sUid) must be passed by reference, value given at /var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php#7241

POST /apps/rainloop/app/?/Ajax/&q[]=/_3I_n7rJEwu0RSHlY-STEFQhiXm_vTo2LAInVeyBfK4tI3PgzJPei8fRSNs87Ph4yI25OwLU4Hqux7K4n1pjq7aeAp-TWNwXEm41nzE1nEfGIS1DaO61zNvOl4AJtqxB_y_9FqnYF_7VkvewqcqGURBhzG1AIJIXEhv6w1vapyE288c0pgsCP7aEOddcS8Ctxktj3a9zOabkpLlYX_TBXiNFOVX6tHoI21TLe8wX3PwueSdHicBt6v8pkF6DQMijem5NzlpK_kETYJ8z3fNutp4UIUVZj_ua8D3ruNVisH5SPg5wXsZtJTMPbasQ5AEw8apjnS-rRJs6o42-0bamoY9Mi7AN5H9A9-ukBZROWUrP57py3Gbwm6qL1jSXUpYysqBgOf3StcnGZmP_MAX4wGQ/
from x.x.x.x by emporea at 2021-11-03T16:56:13+00:00
```

`{"reqId":"QTPtmqt3fHNL2Ao6OK7M","level":3,"time":"2021-11-03T16:56:13+00:00","remoteAddr":"x.x.x.x","user":"emporea","app":"PHP","method":"POST","url":"/apps/rainloop/app/?/Ajax/&q[]=/_3I_n7rJEwu0RSHlY-STEFQhiXm_vTo2LAInVeyBfK4tI3PgzJPei8fRSNs87Ph4yI25OwLU4Hqux7K4n1pjq7aeAp-TWNwXEm41nzE1nEfGIS1DaO61zNvOl4AJtqxB_y_9FqnYF_7VkvewqcqGURBhzG1AIJIXEhv6w1vapyE288c0pgsCP7aEOddcS8Ctxktj3a9zOabkpLlYX_TBXiNFOVX6tHoI21TLe8wX3PwueSdHicBt6v8pkF6DQMijem5NzlpK_kETYJ8z3fNutp4UIUVZj_ua8D3ruNVisH5SPg5wXsZtJTMPbasQ5AEw8apjnS-rRJs6o42-0bamoY9Mi7AN5H9A9-ukBZROWUrP57py3Gbwm6qL1jSXUpYysqBgOf3StcnGZmP_MAX4wGQ/","message":"RainLoop\\Actions::RainLoop\\{closure}(): Argument #1 ($sUid) must be passed by reference, value given at /var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php#7241","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"22.2.0.2","exception":{"Exception":"Error","Message":"RainLoop\\Actions::RainLoop\\{closure}(): Argument #1 ($sUid) must be passed by reference, value given at /var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php#7241","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"RainLoop\\Actions::RainLoop\\{closure}(): Argument #1 ($sUid) must be passed by reference, value given","/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php",7241]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php","line":7241,"function":"array_filter","args":[["3114"],{"__class__":"Closure"}]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php","line":7260,"function":"messageSetFlag","class":"RainLoop\\Actions","type":"->","args":["MessageSetSeen","DoMessageSetSeen"]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/ServiceActions.php","line":174,"function":"DoMessageSetSeen","class":"RainLoop\\Actions","type":"->","args":[]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php","line":150,"function":"ServiceAjax","class":"RainLoop\\ServiceActions","type":"->","args":[""]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php","line":62,"function":"localHandle","class":"RainLoop\\Service","type":"->","args":[]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php","line":85,"function":"__construct","class":"RainLoop\\Service","type":"->","args":[]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/handle.php","line":94,"function":"Handle","class":"RainLoop\\Service","type":"::","args":[]},{"file":"/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/include.php","line":243,"args":["/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/app/handle.php"],"function":"include"},{"file":"/var/www/html/custom_apps/rainloop/app/index.php","line":23,"args":["/var/www/html/custom_apps/rainloop/app/rainloop/v/1.15.0/include.php"],"function":"include"},{"file":"/var/www/html/custom_apps/rainloop/lib/Controller/PageController.php","line":105,"args":["/var/www/html/custom_apps/rainloop/app/index.php"],"function":"include"},{"file":"/var/www/html/custom_apps/rainloop/lib/Controller/PageController.php","line":67,"function":"app","class":"OCA\\RainLoop\\Controller\\PageController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"appPost","class":"OCA\\RainLoop\\Controller\\PageController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\RainLoop\\Controller\\PageController"},"appPost"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\RainLoop\\Controller\\PageController"},"appPost"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["PageController","appPost",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"rainloop.page.appPost"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/rainloop/app/"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6182c1355efb7"}`

**Comment by pierre-alain-b** [comment]
Thank you for the detailed report.

**Comment by eibex** [comment]
I can reproduce this too.
This seems to happen when no auto-login email+passwords are set and the admin option "Users will login manually, or define credentials in their personal settings for automatic logins." is selected.

Checking "Remember Me" does not actually work as username and password need to be entered every time the page is visited (even within a few minutes on the same tab).

The error appears every time `/apps/rainloop/` is visited.

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
