### ISSUE TITLE
Clicking on rainloop admin panel brings me to an empty, white screen

### ISSUE THREAD

**Issue by ptizzl** [pierre-alain-b/rainloop-nextcloud#254]
I'm running nextcloud on docker on a raspberry pi 4 (arm64). When I install, it seems to install fine, but when I go to settings and enable, it simply opens an empty white page. 

I'm not sure where to find the logs. Nothing happens in the logs viewable in portainer.

**Comment by ptizzl** [comment]
Did a bit more digging and it looks like I'm having a similar issue to this one https://github.com/pierre-alain-b/rainloop-nextcloud/issues/215

I was able to access the admin panel by adding /index.php after the port as well as after the domain name, however I still can't get to any point where email does anything. I click the icon on the top menu bar in nextcloud, only to come to a blank white screen with the bar on top.

**Comment by leoniscsem** [comment]
Same for me in a regular install. Environment:

```
Nextcloud 22 (latest)
Rainloop latest stable version 
Ubuntu 18.04 amd64
Linux kernel 5.4.0-90-generic x86_64
Web server  nginx/1.21.4
PHP version 7.4.27 (Supports 64bit values)
PHP SAPI  fpm-fcgi
PHP max input variables 1000
PHP time limit  3600
PHP memory limit  1024M
Max input time  3600
Upload max filesize 2048M
PHP post max size 2048M
Database  10.4.22-MariaDB-1:10.4.22+maria~bionic
```

nginx error log
```
022/01/04 09:52:31 [error] 22466#22466: *5518 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /pathto/nextcloud/apps/rainloop/app/index.php:8
Stack trace:
#0 /pathto/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/include.php(57): __get_custom_data_full_path()
#1 /pathto/nextcloud/apps/rainloop/app/index.php(23): include('/srv/nextcloud/...')
#2 {main}
  thrown in /pathto/nextcloud/apps/rainloop/app/index.php on line 8" while reading response header from upstream, client: 120.245.2.200, server: cloud.thebig3.net, request: "GET /apps/rainloop/app/?OwnCloudAuth HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "cloud.thebig3.net"
```

Same error in php8.1 environment too.

**Edit**:  It obviously does not only affect my admin panel, but the Rainloop interface in general.

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
