### ISSUE TITLE
Support for Nextcloud 23

### ISSUE THREAD

**Issue by sbaum** [pierre-alain-b/rainloop-nextcloud#258]
Hi, I hope I haven't missed any information on this, but will there be a version compatible with Nextcloud 23 in the foreseeable future?

**Comment by rabadumpf** [comment]
Hi! Yes, it would be great if there was a version adapted to v23. Rainloop is a great app!

**Comment by pierre-alain-b** [comment]
I've just pushed a version 7.1.3 with updated translations and info.xml accepting NC23. I have no NC23 Instance so I've not tested myself - can you test and tell me if it works in NC23 ?

**Comment by rabadumpf** [comment]
After the first tests everything is going well!

**Comment by pierre-alain-b** [comment]
Thank you for the information! I will therefore close the ticket.
