### ISSUE TITLE
error in the nextcloud-logs (only since nexcloud 12)

### ISSUE THREAD

**Issue by DJCrashdummy** [pierre-alain-b/rainloop-nextcloud#26]
i'm not sure if it is an (real/unknown/critical) error and if the "original owncloud-version" is also effected, but at least i want to mention it somewhere:

with nexcloud 12 (nexcloud 11 is NOT effected) every time i use the rainloop app i get 
`Error	PHP	Undefined property: OC\Server::$get at /www/htdocs/server/nextcloud12/apps/rainloop/app.php#8`
multiple times in the nexcloud logs.

**Comment by pierre-alain-b** [comment]
This has been fixed here.
https://github.com/pierre-alain-b/rainloop-nextcloud/pull/25

I shall publish a new plugin version very soon.

**Comment by DJCrashdummy** [comment]
@pierre-alain-b thanks for the hint!
sorry for not finding this myself.

**Comment by pierre-alain-b** [comment]
No need to be sorry, it was hard to find and correlate! I will post here when the new version of the plugin will go live!

**Comment by DJCrashdummy** [comment]
but interesting that only NC12 has this error in the logs and NC11 not, although both run the latest rainloop-app 5.0.1...

**Comment by pierre-alain-b** [comment]
I've just published 5.0.2 - it should pop up in the Nextcloud apps updater very soon I guess.
