### ISSUE TITLE
Schedule/Send later feature

### ISSUE THREAD

**Issue by moshpirit** [pierre-alain-b/rainloop-nextcloud#260]
I'm looking for a good webmail software with scheduling options, this is why I was wondering if I should get rid of RoundCube and use RainLoop instead, but I can't find it as a listed feature anyway, so, is it a current option? Maybe is it in the To-do list?

**Comment by pierre-alain-b** [comment]
I recommend to see this with the Rainloop developers here https://github.com/RainLoop/rainloop-webmail. In this repository, we integrate Rainloop into nextcloud but we do not improve Rainloop (or only marginally).

I am not aware of this feature in Rainloop - this does not mean it is not there though.
