### ISSUE TITLE
Sieve error/not working in Rainloop (based on 1.15.0)

### ISSUE THREAD

**Issue by nextgen-networks** [pierre-alain-b/rainloop-nextcloud#263]
There is a bug in the current Rainloop Nextcloud plugin based on Rainloop 1.15.0.
This bug is fixed in the latest official Rainloop 1.16.0 release (https://www.rainloop.net/downloads/).

Result:
Sieve is not connected properly therefore filters can not edited or applied anymore

Reason:
SSL-Crypto connection is not requested/established by Rainloop.

Bugfix/Commit (can be maually applied until fixed/updated release for Nextcloud is available):
https://github.com/RainLoop/rainloop-webmail/commit/c2fc21afedb31aecc3fc21265e01c33382dd67aa

Update for Rainloop was already requested in https://github.com/pierre-alain-b/rainloop-nextcloud/issues/243

Cheers! :-)

**Comment by pierre-alain-b** [comment]
Closing this as the rainloop update shall fix it
