### ISSUE TITLE
/appinfo/app.php is deprecated

### ISSUE THREAD

**Issue by Etua** [pierre-alain-b/rainloop-nextcloud#264]
It seems that Rainloop for Nextcloud used a deprecated call. My journal is flooded with debug messages:
`/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.`

**Comment by pierre-alain-b** [comment]
Indeed, happy to get the help to change the way the plugin communicates with nextcloud

**Comment by smartbyte** [comment]
Sorry, I think the situation got worse. with NC25 Beta I am getting the following error, and I think this is because rainloop is using a deprecated interface: "App rainloop threw an error during app.php load and will be disabled: Class 'OCP\\App' not found" :-( And sadly I cannot help. :-( But I would like to use this app again in NC25...

**Comment by pierre-alain-b** [comment]
Thanks for reporting. Happy to receive any help from people actively developing NC plugins. I've been maintaining the plugin but I've not been the one initially developing the plugin and I am not familiar with the development of plugins for NC.

**Comment by the-djmaze** [comment]
Here you go ;)

**Comment by pierre-alain-b** [comment]
@the-djmaze do you have working snappymail plugin for nextcloud? Because if it is the case,  I think that pivoting to snappymail is a better solution.

**Comment by the-djmaze** [comment]
@pierre-alain-b i just made a first test version
https://github.com/the-djmaze/snappymail/issues/96#issuecomment-1274432058

**Comment by pierre-alain-b** [comment]
I therefore recommend to rather focus the efforts on offering a snappymail pluging for nextcloud rather than sticking to rainloop that is not maintained anymore...

**Comment by scubamuc** [comment]
@pierre-alain-b , do you see a migration possibility for existing nextcloud-rainloop to nextcloud-snappymail. I'm a nextcloud-snap user and rainloop/snappymail is priority for our cloud. I'm keen to migrate. Complete reconfiguration would be difficult to manage.
Thanks for your input.

**Comment by the-djmaze** [comment]
> do you see a migration possibility for existing nextcloud-rainloop to nextcloud-snappymail

@scubamuc probably, but i understand that pierre-alain-b does not know all changes of SnappyMail (as his focus was RainLoop).

There are differences, so the best way to test is to install SnappyMail and copy the `_data_` folder of RainLoop into your `{nextcloud-data-directory}/appdata_snappymail/`
For example you have the following directory structure:
- `/home/nextcloud/data/appdata_snappymail/_data_/`
- `/home/nextcloud/public_html/apps/snappymail/`
- `/home/nextcloud/public_html/ocs/`
- `/home/nextcloud/public_html/ocs-provider/`

And read https://github.com/the-djmaze/snappymail/wiki/Installation-instructions#migrationupgrade-from-rainloop

**Comment by pierre-alain-b** [comment]
Yes I agree that @the-djmaze is better placed! that said I will be happy to reroute all potential users to the snappymail nextcloud integration as I clearly believe snappymail is a more sound option today than rainloop.
