### ISSUE TITLE
Failed authentication

### ISSUE THREAD

**Issue by Wotan6891** [pierre-alain-b/rainloop-nextcloud#266]
Hello,

I have configured everything as explained here. and I have also searched the forums and here if there is a solution.

I did the tests creating the database and adding a new domain, and everything gave me OK.

so assuming my domain is
no.com then in the section where the email and password are entered (where the user must also enter) I put: emial: admin@no.com - password: XXXXXX.

but it doesn't work, and I've tried it on the user side as well.

and the message is: "Authentication failed"

1. why it fails?

2. When registering a domain, can the email be created directly from nextcloud-rainloop or does it have to be created in the web server panel?

Thanks for your help.

**Comment by pierre-alain-b** [comment]
Please check on the email server side if the email exists and password is correct. I guess the email account is not set as next configured in rainloop.
