### ISSUE TITLE
[7.2.0] White page

### ISSUE THREAD

**Issue by Valdnet** [pierre-alain-b/rainloop-nextcloud#267]
After installing Rainloop version 7.2.0, it does not start. Only the white page is displayed.

Apps:
Nextcloud 23.0.3
Rainloop 7.2.0

**Comment by pierre-alain-b** [comment]
Thanks for testing!

Was 7.1.3 working fine in NC 23? (I still have NC22)

**Comment by Valdnet** [comment]
> Was 7.1.3 working fine in NC 23? (I still have NC22)

Yes, it works fine in NC 23.0.3.

**Comment by Valdnet** [comment]
I uploaded Rainloop 7.2.0 back to the server and installed it.
Works correctly 👍.
The problem could be caused by a wrong upload from one of the files.

I think I can close the issue.

**Comment by joergmschulz** [comment]
here, the white page appears as well after the upload from the app store. Maybe the app needs to be deleted and reinstalled completely to make it work?

**Comment by Valdnet** [comment]
I suggest uninstalling the application and checking if there are any files left after installation. Then reinstall it.

**Comment by joergmschulz** [comment]
sorry, this didn't work. But the browser console shows something interesting: 
`Refused to execute script from 'https://testserver.mydomain.de/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
`
The admin page can't be loaded as well.

**Comment by pierre-alain-b** [comment]
Duplicate of #274
