### ISSUE TITLE
Account not Allowed on 7.2.0

### ISSUE THREAD

**Issue by hydrian** [pierre-alain-b/rainloop-nextcloud#268]
@pierre-alain-b,
I upgraded to 7.2.0. Now when I attempt to login, I get 'Account Not Allowed'. I verified the domain was still in the allowed domains list, and it was. My users are LDAP backend users. 

[14:17:49.810][e896a9ae] AJAX[NOTE]: Action: DoLogin
[14:17:49.810][e896a9ae] POST[DATA]: {"Email":"hydrian","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"0","Action":"Login","XToken":"807f404e85697e613aea4c397b1e38de"}
[14:17:49.810][e896a9ae] LOGIN[DATA]: The email address "hydrian" is not complete
[14:17:49.810][e896a9ae] LOGIN[DATA]: Determined user domain: secure.tygerclan.net
[14:17:49.811][e896a9ae] LOGIN[DATA]: Check "secure.tygerclan.net": NO
[14:17:49.811][e896a9ae] LOGIN[DATA]: Check "tygerclan.net": OK (hydrian > hydrian@tygerclan.net)
[14:17:50.812][e896a9ae] INFO[NOTICE]: RainLoop\Exceptions\ClientException: AccountNotAllowed[110] in /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php:1315
Stack trace:
#0 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2328): RainLoop\Actions->LoginProvide()
#1 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2456): RainLoop\Actions->LoginProcess()
#2 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#3 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(151): RainLoop\ServiceActions->ServiceAjax()
#4 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#5 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#6 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/app/handle.php(94): RainLoop\Service::Handle()
#7 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/include.php(243): include('/var/www/nextcl...')
#8 /var/www/nextcloud/apps/rainloop/app/index.php(23): include('/var/www/nextcl...')
#9 /var/www/nextcloud/apps/rainloop/lib/Controller/PageController.php(105): include('/var/www/nextcl...')
#10 /var/www/nextcloud/apps/rainloop/lib/Controller/PageController.php(67): OCA\RainLoop\Controller\PageController->app()
#11 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(217): OCA\RainLoop\Controller\PageController->appPost()
#12 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(126): OC\AppFramework\Http\Dispatcher->executeController()
#13 /var/www/nextcloud/lib/private/AppFramework/App.php(156): OC\AppFramework\Http\Dispatcher->dispatch()
#14 /var/www/nextcloud/lib/private/Route/Router.php(302): OC\AppFramework\App::main()
#15 /var/www/nextcloud/lib/base.php(1006): OC\Route\Router->match()
#16 /var/www/nextcloud/index.php(36): OC::handleRequest()
#17 {main}
[14:17:50.812][e896a9ae] AJAX[DATA]: {"Action":"Login","Result":false,"ErrorCode":110,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1014}

This is in reference to #243

**Comment by hydrian** [comment]
I had a 'tygerclan.net' whitelisted and it was the only one in the whitelist. Once I removed it from the whitelist, I was able to log in successfully. This sounds more like a rainloop issue than a rainloop-nextcloud issue.

**Comment by pierre-alain-b** [comment]
OK good to know. I've not studied the changes in 1.16 to detect if a novel feature/a change in 1.16 in RL could explain this!

**Comment by pierre-alain-b** [comment]
Then can we say that the issue is solved?
(or at least not in the perimeter of rainloop-nextcloud?)

**Comment by hydrian** [comment]
I think we can. I wanted to hear if you had any thoughts on this. Obviously, it didn't ring any bells for you. I did do a diff of doLogin() between 7.1.3 and 7.2.0 and there were no changes for that function. I think it is safe to close this issue. I wanted it here for at least documentation.

**Comment by pierre-alain-b** [comment]
I've no clue where this could come from - at least I know this is not one function that I've altered... sorry not to help here.

**Comment by pierre-alain-b** [comment]
And thanks for testing!
