### ISSUE TITLE
Argument #1 ($sLine) must be passed by reference

### ISSUE THREAD

**Issue by JordanDIG** [pierre-alain-b/rainloop-nextcloud#269]
Hello,
This error often appears in my logs
RainLoop\Config\AbstractConfig::RainLoop\Config\{closure}(): Argument #1 ($sLine) must be passed by reference, value given at /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/app/libraries/RainLoop/Config/AbstractConfig.php#306

**Comment by pierre-alain-b** [comment]
This time the code is in Rainloop itself => I recommend this is shared with the Rainloop team as I try as much as possible not to tamper with upstream Rainloop
