### ISSUE TITLE
Mobile View - Body content window is very small

### ISSUE THREAD

**Issue by kesavarajaphp** [pierre-alain-b/rainloop-nextcloud#27]
Hi,

We integrated the rainloop app latest version with Nextcloud 12. We are facing the problem in Mobile, as we try to type large content but we can see only two to three lines of typing and to scroll for view remaining. We are saying about ckeditor window is very small in height. 

Expectation : When we type in mobile, the height of the ckeditor content window should be increased automatically.

How it can be done ? Please suggest.

Thank you,
Kesavaraja

**Comment by kesavarajaphp** [comment]
Hi,
Any update for Mobile view issues ?

**Comment by pierre-alain-b** [comment]
Could you precise which mobile browser you use, on which OS and whice device? Could you post a couple of screenshots maybe?

**Comment by kesavarajaphp** [comment]
@pierre-alain-b 
Thank you for the reply.
We checked in the below mobile version.
1. Google Chrome V 60.0.3112.107
2. Android V 7 (Nougat)
3. Redmi Note 4

When we click on the body, the keyboard pops up and hide the body. The user needs to scroll to see the editing window.
The user scrolls two to three lines of body content is visible, if it is very long, then the user need to scroll to read.
We have attached the screenshot. Please check it and revert back.

![android mobile view](https://user-images.githubusercontent.com/29251273/30146803-d3de28dc-93b7-11e7-8398-1fb9721a273e.png)
![keyboard popup in rainloop mobile](https://user-images.githubusercontent.com/29251273/30146804-d3e4bc56-93b7-11e7-8717-d8cfb7d2210b.png)

**Comment by pierre-alain-b** [comment]
Apparently 1.11.3 brings some new features about "mobile view". It seems to me that this is now fixed.
