### ISSUE TITLE
Switch from Rainloop to Snappy?

### ISSUE THREAD

**Issue by daffydock** [pierre-alain-b/rainloop-nextcloud#270]
Hi, 

Noticed a security error while on the Rainloop admin. Due to this, I got to perusing the Rainloop Webmail Github and came across [#2162 ](https://github.com/RainLoop/rainloop-webmail/issues/2162). It points to a number of unresolved security flaws being pointed out by many users. Including people who are actively trying to help, however these remain open, unaddressed or are eventually closed, by the users themselves. Due to this, I have decided to disable the app on my NC instance. At least for the time being. 

Having said that, it seems Rainloop's development has stalled, with few commits and lingering security problems. [I did however notice a fork of Rainloop available](https://github.com/the-djmaze/snappymail/releases), one that is actively maintained and was wondering if perhaps the NC project would perhaps switch to that one? Since the NC integration here is excellent. As it seems they are actively plugging the security issues. Either way, thank you for your time.

**Comment by mactrent** [comment]
Related: it appears that SnappyMail removed some of the code that's needed for the integration, but they have a WIP branch that would enable it again.  They're [looking for contributions](https://github.com/the-djmaze/snappymail/issues/96) from their side, if anyone's able.

**Comment by daffydock** [comment]
Alright, thanks. So, should I just close this then?

**Comment by pierre-alain-b** [comment]
No I think it is good to keep this open to bring as many effort as possible to the fork. And of course I'd be more than happy to get some help to switch the rainloop plugin to Snappy if Snappy is indeed far superior to Rainloop.

**Comment by the-djmaze** [comment]
> if Snappy is indeed far superior to Rainloop.

Depends on your needs.
SnappyMail has removed several "features" for security reasons, but that also limits its use for some people.

For example it is hard to use OAuth2 with the "multiple accounts" feature.
Because the additional accounts are encrypted on the server with the main login password, and when the main login is OAuth2 it rotates and then you must re-enter password for the additional accounts.
This is due to https://github.com/RainLoop/rainloop-webmail/issues/2134

But in return you do get more privacy, security and a dark mode.

Although i don't have a NextCloud instance, i'm always available for integration needs/help

**Comment by daffydock** [comment]
> No I think it is good to keep this open to bring as many effort as possible to the fork. And of course I'd be more than happy to get some help to switch the rainloop plugin to Snappy if Snappy is indeed far superior to Rainloop.

Very well, I will keep it as is then. 
As an aside, I was playing around with the SnappyMail demo setup by @the-djmaze, as such, for those who are curious, here is a short side to side comparison between Rainloop and Snappy. 

https://snappymail.eu/comparison.html

**Comment by pierre-alain-b** [comment]
Nice comparison. My feeling is that we should not change the Rainloop plugin as some people may prefer Rainloop for some of the features that have been simplified.
But clearly a Snappy integration would make sense for those who like to have the webmail within Nextcloud.

**Comment by pierre-alain-b** [comment]
I am closing this ticket as this project will not switch. But I totally agree a new snappy-nextcloud project would make sense!

**Comment by daffydock** [comment]
Sounds fair. Thanks.

**Comment by Neustradamus** [comment]
@pierre-alain-b: I do not see "snappy-nextcloud" and a redirection to this...

**Comment by pierre-alain-b** [comment]
I don't know if such a project has been started by someone!
