### ISSUE TITLE
Automatic login stops working

### ISSUE THREAD

**Issue by Mitschmaster** [pierre-alain-b/rainloop-nextcloud#271]
Hi,
i have automatic login configured and it works well if i freshly login to nextcloud and the go to rainloop. but after a while when i open rainloop from nextcloud (to which i am still logged on) i get a login screen.
i ll provide a log file, but i just logged in so ill have to wait until the error shows again.
but in the log it basically says, that in 
app/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php on Line 2307
it throws an exception.
probably the password is 0 there.
i tried to understand what is going on, but since i could not find out for an hour what the RunHook does i decided maybe someone with better knowledge knows what happens.

**Comment by pierre-alain-b** [comment]
Is this after migration du v7.2.1? Can you confirm the behavior?

**Comment by pierre-alain-b** [comment]
Can you update to 7.2.2 and tell me if this persists?

**Comment by Mitschmaster** [comment]
I was on 7.1.3. The version was installed from web interface.
Now i upgraded to 7.2.2. I will provide an update.

**Comment by Mitschmaster** [comment]
the problem is still there. i still get logged out automatically and must enter password.

**Comment by Aquariu** [comment]
I have the same situation but I used to consider it as normal. I thought it was related to the IMAP session timeout.

**Comment by unsalkorkmaz** [comment]
I have problem with auto login too. If I click mobile version, it is directly logging in.

For example;
If I use `https://NEXTCLOUD/apps/rainloop/app/?/DesktopVersion/` it is always logging in.


```
Operating system: Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64

Webserver: Apache (fpm-fcgi)

Database: mysql 10.3.34

PHP version: 8.1.5

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, ldap, exif, mcrypt, msgpack, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, pspell, readline, redis, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

Nextcloud version: 24.0.0 - 24.0.0.12
```

**Comment by cdidier** [comment]
Might want to check "session.gc_maxlifetime" in your php config. If it is set to 24 minutes (the default) and you suspend your computer or you have no keepalive in nextcloud and leave your computer alone, 24 minutes later your session will be garbage collected and you'll loose your credentials for rainloop.

See 'session_lifetime' in https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html.

**Comment by unsalkorkmaz** [comment]
Oh, I forget to update here, my bad.
![Screenshot 2022-06-02 114240](https://user-images.githubusercontent.com/207720/171591620-13ab223c-28b4-4792-85ec-20bd10054dd4.png)
there is a setting in personal settings. I thought checking "remember me" in login page is what needed but it seems not

**Comment by GUNT0815** [comment]
My expectation is, that every single user can use the "remember login" function with his individuel login sequence. But checking the box does not do so. But instead the nextcloud login data are prefiled. That makes no sense from my perspective. I use verions 7.2.5.

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
