### ISSUE TITLE
[proposal] Integrate snappymail instead of rainloop

### ISSUE THREAD

**Issue by ghost** [pierre-alain-b/rainloop-nextcloud#276]
https://thehackernews.com/2022/04/unpatched-bug-in-rainloop-webmail-could.html?m=1

Could you let us know what can be done to mitigate this? I totally understand if you refuse this proposal. But should there at least be a RED BANNER ALERT in the nextcloud web client instead of giving users false sense of security?

**Comment by pierre-alain-b** [comment]
Well we will incorporate here the updated version of Rainloop when it is released. There is no plan in this repository to do more than just follow rainloop unfortunaltely.

I agree switching to Snappy would make sense but this is another project.

**Comment by pierre-alain-b** [comment]
And for the sake of clarity, we are not maintainers of Rainloop and we never got any contact with Rainloop maintainers (although we tried).

I will have a look at Snappy again.

**Comment by pierre-alain-b** [comment]
See #277 as well

**Comment by pierre-alain-b** [comment]
In ccb381827442e26d8b7ee484540c127d375dce00 a fix was inserted. However it is clear that Rainloop is not maintained anymore and that the situation is not sustainable. I agree a switch to SnappyMail is needed.
