### ISSUE TITLE
PDF attachment preview does not open in Firefox 55.0.2 (64-Bit)

### ISSUE THREAD

**Issue by cwm77** [pierre-alain-b/rainloop-nextcloud#28]
Hello,

It seems, there is a problem to use preview of pdf files in Firefox. The eye, like in chrome, doesn't appear. I tried it with Windows (7 and 10) and Linux (Mint and Ubuntu 16.04). I read somewhere here in a closed issue message, that this was done for Chrome, but Firefox would have no support to preview pdf´s. I can´t believe this :)

https://blog.mozilla.org/blog/2013/02/19/firefox-introduces-pdf-viewer-to-browse-the-web-without-interruption/

Overall I´m very happy with rainloop-nextcloud :+1: . Thank you for providing it.

**Comment by pierre-alain-b** [comment]
Same behavior here. I am pretty positive it worked some months ago but for some time I had not seen it working. I believed it was an issue with my Firefox profile but apparently I am not alone.
I see no error in the developer console, anything on your side? Any clue on where to look?
PAB

**Comment by cwm77** [comment]
What I know is, that it has not something to do with an ff extension. Unfortunately it has the same behavior with Firefox in safe mode.

**Comment by pierre-alain-b** [comment]
Sam behavior with 1.11.3 that has just been released. Unfortunately...

**Comment by MohammadYaaser** [comment]
Hi Pierre, Even Chrome Has the same Issue . i would like to preview all the attachments (PDF, Excel etc. ) the default Next-cloud previews files  in files module

**Comment by pemocarlo** [comment]
Unfortunately I still see the same issue, it works in Chrome but not in Firefox.

@pierre-alain-b  What do you think is the relevant portion of code here so that I can have a look?

Thank you
