### ISSUE TITLE
RainLoop data folder is accessible in nextcloud snap

### ISSUE THREAD

**Issue by S0ulf3re** [pierre-alain-b/rainloop-nextcloud#280]
Im getting a warning that Rainloops data folder is accessible in the nextcloud snap. Should I be worried or is this just a side effect of having it installed within the snap?

**Comment by pierre-alain-b** [comment]
It is presumably just a side effect but in my experience there is no real access to the data folder. Can you maybe give it a try and report if the data folder is really accessible?
