### ISSUE TITLE
NC24.0.1 Docker - admin page loads HTTP ERROR 500 - app shows blank page

### ISSUE THREAD

**Issue by Arcau** [pierre-alain-b/rainloop-nextcloud#281]
I attempted to follow the fix in with no luck - removed and reinstalled 
https://github.com/pierre-alain-b/rainloop-nextcloud/issues/201

I am using the 7.2.5 version of the app from the app store. 
I am running the NC instance in Docker on Unraid behind an Nginx Proxy Manager setup.

Looks to be similar to issue https://github.com/pierre-alain-b/rainloop-nextcloud/issues/254
Unsure if that is still being addressed.

**Comment by pierre-alain-b** [comment]
Have you tried the solution proposed here? https://github.com/pierre-alain-b/rainloop-nextcloud/issues/215

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
