### ISSUE TITLE
Upload files from Nextcloud in the Rainloop mail Nextcloud 24.*.*

### ISSUE THREAD

**Issue by lixxdee** [pierre-alain-b/rainloop-nextcloud#284]
hello everyone! I have been looking for solutions for a long time on how to upload files from Nextcloud in the Rainloop mail. Could you please update app rainloop compatibility with Nextcloud 24 with the ability to upload files? Or give advice on how to do it?

**Comment by Bolli84** [comment]
Hi @lixxdee you can found some code to do it here: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/42#issuecomment-633115762

But you need to create and replace the app.ja and app.min.js files.

**Comment by webagroprom** [comment]
```
_proto.dropboxCommand = function dropboxCommand() {
var _this4 = this;
parent.OC.dialogs.filepicker(
'Choose a file to add as attachment',
function (path) {
var size = 0;
var name = path.substring(path.lastIndexOf("/") + 1, path.length);
var password = prompt("Password please:");
for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
if (parent.OC.dialogs.filelist[i].name == name) {
size = parent.OC.dialogs.filelist[i].size;
var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path);
var dropboxFile = { link: ncurl, bytes: size, name: name };
_this4.addDropboxAttachment(dropboxFile);
}
}
return true;
};
```
Nextcloud 24 - rainloop, don't work  for me.

Does this code work for anyone in Nextcloud version 24?
Can anyone post a working file to replace the current rainloop files in order for the download function to work in the mail client?

**Comment by pierre-alain-b** [comment]
I recommend that you take a loot at snappymail being ported to Nextcloud. Snappymail is maintained unlike Rainloop that seems not to be anymore. https://github.com/the-djmaze/snappymail/issues/96
