### ISSUE TITLE
[Feature Request] Connect rainloop to nextcloud notification 

### ISSUE THREAD

**Issue by elhananjair** [pierre-alain-b/rainloop-nextcloud#286]
Hello, @pierre-alain-b I just wanted to ask if it's possible to connect rainloop with nextcloud notification. It would be awesome if I can get notifications for new Email arrival, and any notifications that rainloop might generate. Thank you

**Comment by pierre-alain-b** [comment]
I recommend that you take a loot at snappymail being ported to Nextcloud. Snappymail is maintained unlike Rainloop that seems not to be anymore. https://github.com/the-djmaze/snappymail/issues/96
