### ISSUE TITLE
Grey screen when switching to other accounts

### ISSUE THREAD

**Issue by jimbolaya** [pierre-alain-b/rainloop-nextcloud#287]
I have a setup where I've got three accounts set up. 

The main account almost always works correctly. I click on the email icon, and the rainloop/snappymail interface loads. Sometimes it doesn't work, but the majority of the time it's fine.

However, if I pull down the list of accounts, and pick another account, it loads maybe once out of every 4-5 times, the rest of the time, there's no rainloop interface, just the standard grey background. 

Watching the logs in a window, it appears that it stops loading and nothing more shows up on the interface part of the window.

Should I try something in Nextcloud to improve the performance of this? I'm not sure what other information would be helpful.

I'm running Nextcloud 23.0.10 on Apache2 2.4.54 and php 7.4.30 using standard Debian Bullseye packages.

**Comment by pierre-alain-b** [comment]
I recommend that you take a loot at snappymail being ported to Nextcloud. Snappymail is maintained unlike Rainloop that seems not to be anymore. https://github.com/the-djmaze/snappymail/issues/96
