### ISSUE TITLE
Can't enable Rainloop after upgrade to Nextcloud 25

### ISSUE THREAD

**Issue by steelsnake** [pierre-alain-b/rainloop-nextcloud#289]
After upgrading to Nextcloud 25 I cannot enable RainLoop 7.2.5.

I tried removing and reinstalling RainLoop, always same error. This is the only app that seems to fail.

The NextCloud log has the following entries:
{"reqId":"4lzYheGbUiAem8HwGi2Y","level":3,"time":"2022-10-20T05:39:57+00:00","remoteAddr":"69.162.230.182","user":"jennifer","app":"no app in context","method":"GET","url":"/apps/files","message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Class \"OCP\\App\" not found","Code":0,"Trace":[{"file":"/www/cloud/apps/rainloop/appinfo/app.php","line":13,"function":"registerPersonalSettings","class":"OCA\\RainLoop\\AppInfo\\Application","type":"->"},{"file":"/www/cloud/lib/private/legacy/OC_App.php","line":306,"args":["/www/cloud/apps/rainloop/appinfo/app.php"],"function":"require_once"},{"file":"/www/cloud/lib/private/legacy/OC_App.php","line":187,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/www/cloud/lib/private/legacy/OC_App.php","line":141,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/www/cloud/lib/base.php","line":1027,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/www/cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/www/cloud/apps/rainloop/lib/AppInfo/Application.php","Line":83,"message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","CustomMessage":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found"}}

**Comment by pierre-alain-b** [comment]
Rainloop is deprecated - consider migrating to snappymail!
https://github.com/the-djmaze/snappymail
