### ISSUE TITLE
CKeditor Original Update, Missing the signature

### ISSUE THREAD

**Issue by kesavarajaphp** [pierre-alain-b/rainloop-nextcloud#29]
Hi,

We have downloaded the latest version of CKeditor and replaced in Rainloop ckeditor plugin. Also we have uploaded the Vendor CK editor Plain and Signature plugin from rainloop git. 
But the signature is missing in the Ckeditor. Is there anyother way to update CKeditor. Or do we need add anything in the code of rainloop.

Please kindly help us to resolve the issue.

Thank you,
Kesavaraja.

**Comment by pierre-alain-b** [comment]
Can you detail further what you have done?
I recommend that you find the maintainers for those plugins and discuss with them - here we just maintain the nextcloud integration (and we just inject rainloop as it is in here).
By the way, it is maybe easier to try this in a standalone version of Rainloop first (just to make sure there is no inteference with the plugin, I see no reason for interferences but...)

**Comment by kesavarajaphp** [comment]
@pierre-alain-b 

Thank you for the reply.

For the purpose of using the latest version of CKeditor, we updated the ckeditor plugin by downloading from https://ckeditor.com.

> I recommend that you find the maintainers for those plugins and discuss with them - here we just maintain the nextcloud integration (and we just inject rainloop as it is in here).

 I agree, and will communicate them regarding the above mentioned issue.

> By the way, it is maybe easier to try this in a standalone version of Rainloop first (just to make sure there is no inteference with the plugin, I see no reason for interferences but...)

Ya we tried yesterday, and we found the issue is still in rainloop mail system. For this issue, we'll contact rainloop.

Thank you for the support. We can close this thread now.
