### ISSUE TITLE
Nextcloud Hub 3 (25.0.0) - Rainloop plugin gets disabled with the following error:

### ISSUE THREAD

**Issue by ghost** [pierre-alain-b/rainloop-nextcloud#290]
`{"reqId":"yK0EXre4S58ZUOrZ7TbQ","level":3,"time":"2022-10-20T10:24:58+02:00","remoteAddr":"10.8.0.4","user":"admin","app":"no app in context","method":"GET","url":"/","message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Class \"OCP\\App\" not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/rainloop/appinfo/app.php","line":13,"function":"registerPersonalSettings","class":"OCA\\RainLoop\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":306,"args":["/var/www/nextcloud/apps/rainloop/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":187,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":141,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1027,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/rainloop/lib/AppInfo/Application.php","Line":83,"message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","CustomMessage":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found"}}`

`{"reqId":"WdO0jkbmfPkh0iAu3MYY","level":3,"time":"2022-10-20T10:26:01+02:00","remoteAddr":"10.8.0.4","user":"admin","app":"no app in context","method":"GET","url":"/apps/files/","message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Class \"OCP\\App\" not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/rainloop/appinfo/app.php","line":13,"function":"registerPersonalSettings","class":"OCA\\RainLoop\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":306,"args":["/var/www/nextcloud/apps/rainloop/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":187,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":141,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1027,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/rainloop/lib/AppInfo/Application.php","Line":83,"message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","CustomMessage":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found"}}`

`{"reqId":"Rhd64sQ8Out8pnKv7TZ2","level":3,"time":"2022-10-20T10:26:09+02:00","remoteAddr":"10.8.0.4","user":"admin","app":"no app in context","method":"GET","url":"/apps/files/","message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Class \"OCP\\App\" not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/rainloop/appinfo/app.php","line":13,"function":"registerPersonalSettings","class":"OCA\\RainLoop\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":306,"args":["/var/www/nextcloud/apps/rainloop/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":187,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":141,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1027,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/rainloop/lib/AppInfo/Application.php","Line":83,"message":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found","CustomMessage":"App rainloop threw an error during app.php load and will be disabled: Class \"OCP\\App\" not found"}}`

**Comment by pierre-alain-b** [comment]
I will push a final release fixing this point not to block users in NC25

**Comment by ghost** [comment]
Thanks for the fast solution, installed rainloop update and plugin works now!

**Comment by pierre-alain-b** [comment]
That said, I must stay that I sill recommend you consider a migration to snappymail...

**Comment by ghost** [comment]
Thanks for the hint, I will try it out and if it works I will disable RainLoop.
