### ISSUE TITLE
Add filter possibility

### ISSUE THREAD

**Issue by jybeeL** [pierre-alain-b/rainloop-nextcloud#3]
Hi, 

Is it possible to add a new function to rainloop?
for example , i want to filter my mail by sender and automatically move this or these mails to a folder already existing or a new folder.

Thx :)

**Comment by pierre-alain-b** [comment]
Hello,
I recommend that you post feature requests in the issue tracker of Rainloop itself.
https://github.com/RainLoop/rainloop-webmail/issues
Best
PAB
