### ISSUE TITLE
Always show the extra options (Download as zip + Save to ownCloud)

### ISSUE THREAD

**Issue by VisioFX** [pierre-alain-b/rainloop-nextcloud#32]
Always show the extra options: 'Download as zip' + 'Save to ownCloud'.
Or perhaps make an user or global option to always show this extra functionality.

**Comment by pierre-alain-b** [comment]
That should be shared with the Rainloop team, for now we incorporate Rainloop as it is developed in a standalone way.

**Comment by VisioFX** [comment]
Ok request filed at: https://github.com/RainLoop/rainloop-webmail/issues/1502
