### ISSUE TITLE
Update to the latest version of Rainloop

### ISSUE THREAD

**Issue by Larsene** [pierre-alain-b/rainloop-nextcloud#33]
Hi, will you update it to the latest version of rainloop (1.11.3), who add some useful fixes ?

Thanks

**Comment by pierre-alain-b** [comment]
Yes, I will do this week end, thank you for pointing out that the new version of Rainloop is out!
PAB

**Comment by Larsene** [comment]
Thanks for your work !

**Comment by pierre-alain-b** [comment]
5.0.3 with 1.11.3 has just been released!
