### ISSUE TITLE
Preconfigured E-Mail-Server Settings

### ISSUE THREAD

**Issue by Huster-at-github** [pierre-alain-b/rainloop-nextcloud#35]
It would be nice to have more frequently used e-mail servers preconfigured in the app.

Like:
* gmx.*
* t-online.de
* yahoo.* (if possible)
* web.de

Current servers configured:

![rainloop_email_server](https://user-images.githubusercontent.com/3857906/32177432-a71c8274-bd8a-11e7-9a48-a6f510ac2a12.JPG)

**Comment by pierre-alain-b** [comment]
Sure, it is in fact very easy to do. You just have to collect the info and create a your_domain.ini to be placed in rainloop/app/rainloop/v/1.11.3/app/domains/.

The example syntax for the .ini file is:

```
imap_host = "imap.gmail.com"
imap_port = 993
imap_secure = "SSL"
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_secure = "TLS"
smtp_auth = On
```

If you (or someone else) collect the info, I will be happy to ship this in the future version of Rainloop for Nextcloud, and I will also push this to Rainloop team.

Best
Pierre-Alain

**Comment by omigeot** [comment]
Just for the records, these are the mechanisms used by Thunderbird for email autoconfiguration : https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

**Comment by pierre-alain-b** [comment]
Yes thank you,  unfortunately this is not the mechanism Rainloop relies on for the moment.
That said, it would be a worthwile addition for Rainloop, if someone would like to develop and bring to upstream!
