### ISSUE TITLE
Multi Account

### ISSUE THREAD

**Issue by Ser1ous1** [pierre-alain-b/rainloop-nextcloud#36]
Hello,
it would be very nice if i sign in on my nextcloud -> go to the rainloop app and have all my email accounts with saved credentials, so i don't have to remember the passwords.

**Comment by pierre-alain-b** [comment]
Hi, it seems to me that this is what Rainloop offers as a feature. What does not work for you?

**Comment by Ser1ous1** [comment]
Works for me now. Thanks, for this wonderful Application!
