### ISSUE TITLE
nextcloud 13.x

### ISSUE THREAD

**Issue by JimmyKater** [pierre-alain-b/rainloop-nextcloud#38]
as of today nextcloud 12 wouldn't be able to update to version 13 (they're working on it and seem to be pretty far, already)... without losing support for rainloop-app.

what about trying to make rainloop nc13-ready from now on so that there won't be any diffculties with it when nc-devs plan to release v13?

well this is just a reminder of upcomping nc-update and what it's prolly gonna do to rainloop. i just don't want to lose it ;)

**Comment by pierre-alain-b** [comment]
Have you identified what would be blocking for Rainloop under NC13? I haven't had the opportunity to test it to see what happens.
@MorrisJobke has recently (2 days ago) submitted a patch on some items of the plugin - could it be that this was the blocking part now fixed?

**Comment by JimmyKater** [comment]
no i haven't identified anything or even crosschecked it.

maybe it would be as simple as entering kind of "valid for version 13.0" as well somewhere.
right now it's not mentioned to be able to update to version 13. (see new app "can i update" as well as on [https://apps.nextcloud.com/apps/rainloop](url) )

**Comment by pierre-alain-b** [comment]
OK then it could only be the min/max version in the app package. I will update this and submit a new release!

**Comment by JimmyKater** [comment]
> it could only be the min/max version

that's what i meant. and yes... hopefully it's THAT easy.

**Comment by MorrisJobke** [comment]
> it could only be the min/max version

It is there, so that the developer actively checks if the app works as expected. Usually it should work just fine. It's just a way to have some tests before users will notice the hard issues that could otherwise have been avoided.

**Comment by pierre-alain-b** [comment]
Thanks @MorrisJobke, sure I will test before rolling out the version for 13. However, what is the best way to test? Test on master or wait maybe for NC 13 release candidates?

**Comment by MorrisJobke** [comment]
> Test on master or wait maybe for NC 13 release candidates?

Maybe with the beta: https://download.nextcloud.com/server/prereleases/nextcloud-13.0.0beta1.zip ?

**Comment by pierre-alain-b** [comment]
Thank you!

**Comment by pierre-alain-b** [comment]
Test done, works very well. I will ship 5.0.5 into the nextcloud store so that it will be available!
