### ISSUE TITLE
Credentials 'not' remembered

### ISSUE THREAD

**Issue by kees-closed** [pierre-alain-b/rainloop-nextcloud#39]
I'm using Nextcloud 12.0.3 with the latest Rainloop 5.0.6.

After I enable the 'Remember Me' option and log in, I get the same prompt again after I open Rainloop again. The funny thing is that when I choose 'Mobile version' it does login without any prompt. This happened after the upgrade to Rainloop 5.0.6.

Running Raspbian 9.1 with Apache, Postfix and Dovecot.

**Comment by pierre-alain-b** [comment]
Interesting as 5.0.6 ditches mcrypt (soon to be deprecated) for openssl to keep the login info! So it should come from this version. I will do further tests (it works on my side) and see if (i) we should revert to the mcrypt version for now or (ii) if that behavior can be fixed with the openssl version.

**Comment by kees-closed** [comment]
Hi @pierre-alain-b, I think it works fine, since it does work in the mobile version of Rainloop. But for the desktop version something seems to go wrong and credentials are asked every time. Raspbian uses OpenSSL 1.1.0f-3+deb.

**Comment by pierre-alain-b** [comment]
Have you tried flushing the cache (or using incognito mode) of your browser? Just to make sure this is not due to sthg remnant from previous sessions!

**Comment by kees-closed** [comment]
It's also still there after clearing the cache. Sometimes the login prompt also happens again with the mobile version, then reverting to the desktop version enables me to log in automatically again. Using Chrome.

**Comment by kees-closed** [comment]
After I upgraded to Nextcloud 12.0.4 just now, everything is fine again. Although I had to reset the Rainloop admin password for some reason. Other than that, everything is back to normal. Maybe it was a cache issue within Nextcloud, which the upgrade cleared.

Edit: Celebrated too early, the problem still persists...

**Comment by pierre-alain-b** [comment]
Did you reopen it on purpose?

**Comment by kees-closed** [comment]
Yes, when I did I updated my comment as well. The issue persists.

**Comment by fxaguessy** [comment]
Hi,
same problem here after the update to 5.0.6.

**Comment by pierre-alain-b** [comment]
I don't have the issue (but I've reseted the password, see below).

Have you tried re-setting the password in the Rainloop settings in your NC user account settings page? As the way passwords are stored has changed, it is necessary to reset it (to force its proper storage under the new format)

**Comment by fxaguessy** [comment]
Thanks, it seems indeed to fix the problem. I forgot that the password was set in [https://.../settings/personal#rainloop-webmail](https://.../settings/personal#rainloop-webmail)
