### ISSUE TITLE
No automatic login

### ISSUE THREAD

**Issue by dakira** [pierre-alain-b/rainloop-nextcloud#40]
Hi, any pointers on debugging automatic login? I successfully configured the IMAP backend for Nextcloud and it works as it should. Autologin to Rainloop with the exact same credentials doesn't though. I only get the Rainloop login window (manually loggin in works as it should).

**Comment by dakira** [comment]
So.. the problem seems to be, that Nextloud only uses the local part of IMAP authenticated users for the username (which is in turn used to authenticate against rainloop). The behavior is described here: https://github.com/nextcloud/apps/blob/master/user_external/README.md#configuration-1

**Comment by dakira** [comment]
The problem is specifying the allowed domain. If I don't specify one, everything works. In the example below I have to omit example.com. Maybe this could be added to the documentation of this plugin? @pierre-alain-b 

```
'user_backends' => array(
    array(
        'class' => 'OC_User_IMAP',
        'arguments' => array(
            '{127.0.0.1:143/imap/readonly}', 'example.com'
        ),
    ),
),
```

**Comment by pierre-alain-b** [comment]
Hello @dakira,
Thank you for the interesting point. Do you confirm that set up this way, you never had to enter the IMAP username/password in the Rainloop section of the user account panel in NC?

**Comment by dakira** [comment]
@pierre-alain-b, yup, I can confirm that. Never entered it in the backend. Also tried loggin in new users. To make it perfectly clear: The config setting above **did not** work. It only worked after **removing** example.com. I had the domainin there previously, because the Nextcloud documentation and several blog posts suggested it.
