### ISSUE TITLE
Add files from Nextcloud as Attachement

### ISSUE THREAD

**Issue by j-insan3** [pierre-alain-b/rainloop-nextcloud#42]
I don't know if it has been requested before but i were unable to find a similar issue.

Can you make it possible to add files from the Nextcloud instance as a attachment to an email in Rainloop?

**Comment by mehrdad-shokri** [comment]
I don't think there is a file chooser available for Nextcloud.

**Comment by sunjam** [comment]
[Issue #1329 on main rainloop Github.](https://github.com/RainLoop/rainloop-webmail/issues/1329)
[Issue #1535 on main rainloop Github.](https://github.com/RainLoop/rainloop-webmail/issues/1535)

**Comment by tempuser779** [comment]
yes, it would be great if this feature is available. I have already several times enabled/disabled this app looking for this feature. for ex. mail app has an ability to add files from nextcloud directly, but mail app is two levels below rainloop in design and usability. this function should be in rainloop.

**Comment by lavdnone** [comment]
can be copied from here 
https://github.com/nextcloud/mail


     import {pickFileOrDirectory} from 'nextcloud-server/dist/files'
    ....
		onAddCloudAttachment() {
			return pickFileOrDirectory(t('mail', 'Choose a file to add as attachment'))
				.then(path => this.emitNewAttachment(this.fileNameToAttachment(path)))
				.catch(console.error.bind(this))
		},

**Comment by yward** [comment]
This build has the feature but isn't compatible with NC 15, perhaps you can fix compatibility?
https://github.com/vijaydwivedics/rainloop


_______________

EDIT: I have read the code thoroughly, there is no code changes in that guy's repo, he just did some fancy screenshots with no code changes, disregard.

**Comment by lavdnone** [comment]
Just merging changes https://github.com/vijaydwivedics/rainloop has against rainloop-nextcloud nc13 brunch to current brunch didn't work. Guess someone with knowledge or either rainloop or nextcloud would be the best to ask. Someone already asked original author https://github.com/vijaydwivedics/rainloop/issues/1

**Comment by andrewborell** [comment]
> This build has the feature but isn't compatible with NC 15, perhaps you can fix compatibility?
> https://github.com/vijaydwivedics/rainloop
> 
> EDIT: I have read the code thoroughly, there is no code changes in that guy's repo, he just did some fancy screenshots with no code changes, disregard.

I went through it as well and it seems like he basically tried modifying the rainloop dropbox integration slightly to connect to nextcloud instead.  

The functionality exists to save attachments to nextcloud, so its hard for me to understand why we cannot pull from nextcloud aside from the saving functionality is very rudimentary. ( It only saves to an attachments folder in the root, you cannot select your save location ).  That said, the OCP\Files class is already included.  Maybe I will take a shot at making this work if no one else will. Or if it looks like a lot of work I will throw out a bounty.  

In any case, the official mail app in nextcloud is far too green for most businesses to use. It  lacks sieve filters and printing for starters.  These two reasons alone are why rainloop integration is critical in my opinion.  Adding the ability to work with the file system for attachments would make rainloop "almost" perfect.

**Comment by vgdh** [comment]
> > This build has the feature but isn't compatible with NC 15, perhaps you can fix compatibility?
> > https://github.com/vijaydwivedics/rainloop
> > EDIT: I have read the code thoroughly, there is no code changes in that guy's repo, he just did some fancy screenshots with no code changes, disregard.
> 
> I went through it as well and it seems like he basically tried modifying the rainloop dropbox integration slightly to connect to nextcloud instead.
> 
> The functionality exists to save attachments to nextcloud, so its hard for me to understand why we cannot pull from nextcloud aside from the saving functionality is very rudimentary. ( It only saves to an attachments folder in the root, you cannot select your save location ). That said, the OCP\Files class is already included. Maybe I will take a shot at making this work if no one else will. Or if it looks like a lot of work I will throw out a bounty.
> 
> In any case, the official mail app in nextcloud is far too green for most businesses to use. It lacks sieve filters and printing for starters. These two reasons alone are why rainloop integration is critical in my opinion. Adding the ability to work with the file system for attachments would make rainloop "almost" perfect.

so true!

**Comment by feutl** [comment]
Afterlogic seems to integrate their WebMail App into NextCloud. There Lite Version is OpenSource as well.

If you have followed the news or did some research you know that name as a Rainloop user ;) for me Rainloop seems more abandoned then active developed.
I am looking forward to Afterlogic Webmailer, even if the features I could need are premium, but this is fine because there are just no alternatives any more and good software should also be able to earn some money.

Nextclouds Mail app is just so far away from good and Rainloop has not seen an update for month/years.

Just see Afterlogics comment
https://afterlogic.uservoice.com/forums/106725-ideas-for-afterlogic-products/suggestions/37763308-webmail-lite-app-for-nextcloud

https://github.com/afterlogic/webmail-lite-8

**Comment by andrewborell** [comment]
> If you have followed the news or did some research you know that name as a Rainloop user ;) for me Rainloop seems more abandoned then active developed.

I dont think rainloop has been abandoned, seeing as there is a commit from 6 months ago to bring rainloop up to speed with the current nextcloud release. The last changes in RFC related to email that I can find are from 2012, so only security fixes, integration features and UI improvements would ever require any development.  

Paying for software is not a roadblock for me.  I've been through too many mergers, acquisitions, attrition and product abandonment in my days to trust a paid product unless I get the source.  With an opensource project I can take it upon myself or contract out development to continue using a product if the software company changes direction.  I think MIRTH project ( HL7 interfacing ) is a great example where I was part of a great community that sold out and I was left in the dark in some ways.

**Comment by lavdnone** [comment]
do not see nextcloud integration or manage sieve in latest afterlogic
with below compose following the guide https://afterlogic.com/docs/webmail-lite-8/configuring-webmail/nextcloud-integration
autologin and mail icon in nextcloud work
```afterlogic-webmail-lite:
  image: hardware/afterlogic-webmail-lite
  container_name: afterlogic-webmail-lite
  volumes:
    - /mnt/docker/afterlogic-webmail-lite:/afterlogic-webmail-lite/data
  depends_on:
    - mailserver
    - mariadb
```
Looking for this functionality we can continue discussion at afterlogic if rainloop is abandoned
https://github.com/afterlogic/nextcloud-connector

**Comment by pierre-alain-b** [comment]
Hi there, looking at the commits for Rainloop webmail, I do not think Rainloop is totally abandonned.
https://github.com/RainLoop/rainloop-webmail/commits/master
The rainloop developer is accepting merge request so it also means good contributions can improve rainloop.

On my side, when new versions of Rainloop will be made available, I will package a version for Nextcloud.

**Comment by szaimen** [comment]
Is this feature somehow doable? I know that there is now a cross-app filepicker available which would provide the exact functionality that is needed here...

**Comment by Bolli84** [comment]
in the app.min.js (and app.js) you find the following command:
"_proto.dropboxCommand = function dropboxCommand()"

this gives you the entrance key. Allow Dropbox in the admin menu and enter something weird into the API-key. (It MUST NOT be blank).

Then open the app.min.js and replace the "_proto.dropboxCommand = function dropboxCommand()"

with the following code:

_proto.dropboxCommand = function dropboxCommand() {
        var _this4 = this;
        parent.OC.dialogs.filepicker(
            'Choose a file to add as attachment',
            function (path) {
                var size = 0;
                var name = path.substring(path.lastIndexOf("/") + 1, path.length);
                var password = prompt("Password please:");
                for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
                    if (parent.OC.dialogs.filelist[i].name == name) {
                        size = parent.OC.dialogs.filelist[i].size;                      
                        var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path);
                        var dropboxFile = { link: ncurl, bytes: size, name: name };
                        _this4.addDropboxAttachment(dropboxFile);
                    }
                }

            });
        return true;
    };

It has two disadvantages: 
1. Not multiselct (yet)
2. You need to enter your password. We did't find the solution to get rid of it yet.

**Comment by yward** [comment]
> 
> 
> in the app.min.js (and app.js) you find the following command:
> "_proto.dropboxCommand = function dropboxCommand()"
> 
> this gives you the entrance key. Allow Dropbox in the admin menu and enter something weird into the API-key. (It MUST NOT be blank).
> 
> Then open the app.min.js and replace the "_proto.dropboxCommand = function dropboxCommand()"
> 
> with the following code:
> 
> _proto.dropboxCommand = function dropboxCommand() {
> var _this4 = this;
> parent.OC.dialogs.filepicker(
> 'Choose a file to add as attachment',
> function (path) {
> var size = 0;
> var name = path.substring(path.lastIndexOf("/") + 1, path.length);
> var password = prompt("Password please:");
> for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
> if (parent.OC.dialogs.filelist[i].name == name) {
> size = parent.OC.dialogs.filelist[i].size;
> var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path);
> var dropboxFile = { link: ncurl, bytes: size, name: name };
> _this4.addDropboxAttachment(dropboxFile);
> }
> }
> 
> ```
>         });
>     return true;
> };
> ```
> 
> It has two disadvantages:
> 
>     1. Not multiselct (yet)
> 
>     2. You need to enter your password. We did't find the solution to get rid of it yet.

Thank you so much for the snippet! I'll try in one of my NC instances and give feedback.

**Comment by pierre-alain-b** [comment]
@yward happy to read the feedback of your tests!

**Comment by Bolli84** [comment]
@yward @pierre-alain-b it would be fine if someone can solve the issue with the password request. I cannot get through it.

**Comment by Bolli84** [comment]
So, this is the Multiselect. The Authenfication is still missing.


`_proto.dropboxCommand = function dropboxCommand() {
        var _this4 = this;
        parent.OC.dialogs.filepicker(
            'Choose a file to add as attachment',
            function (path) {
                var password = prompt("Enter your Nextcloud Password please:");
                var index;
                for (index = 0; index < path.length; ++index) {
                    var size = 0;
                    var name = path[index].substring(path[index].lastIndexOf("/") + 1, path[index].length);
                    for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
                        if (parent.OC.dialogs.filelist[i].name == name) {
                            size = parent.OC.dialogs.filelist[i].size;
                            var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path[index]);
                            var dropboxFile = { link: ncurl, bytes: size, name: name };
                            _this4.addDropboxAttachment(dropboxFile);
                        }
                    }
                }
            },true);
        return true;
    };`

**Comment by yward** [comment]
> 
> 
> So, this is the Multiselect. The Authenfication is still missing.
> 
> `_proto.dropboxCommand = function dropboxCommand() { var _this4 = this; parent.OC.dialogs.filepicker( 'Choose a file to add as attachment', function (path) { var password = prompt("Enter your Nextcloud Password please:"); var index; for (index = 0; index < path.length; ++index) { var size = 0; var name = path[index].substring(path[index].lastIndexOf("/") + 1, path[index].length); for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) { if (parent.OC.dialogs.filelist[i].name == name) { size = parent.OC.dialogs.filelist[i].size; var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path[index]); var dropboxFile = { link: ncurl, bytes: size, name: name }; _this4.addDropboxAttachment(dropboxFile); } } } },true); return true; };`

I'll work on it next week and try to solve the authentication problem, and share the code back with you guys if I do.
Thank you so much for sharing!

**Comment by miceno** [comment]
Hi 

I am quite interested in this feature. @yward, were you successful?  

I was thinking about the way to integrate NextCloud + RainLoop and I think there are two ways:
1. integrate in this app.
1. integrate as a storage plugin on RainLoop.

I think this issue is about trying the first one. Have you considered the second option?

Regards.

**Comment by yward** [comment]
I'm sorry for the late reply as I have been migrating servers and you know how hectic that can be.
The snippet provided by Bolli84 works flawlessly, I've been trying to work around the authentication requirement but haven't been able to yet, I'll keep you guys posted with any updates.

**Comment by yward** [comment]
> 
> 
> Hi
> 
> I am quite interested in this feature. @yward, were you successful?
> 
> I was thinking about the way to integrate NextCloud + RainLoop and I think there are two ways:
> 
>     1. integrate in this app.
> 
>     2. integrate as a storage plugin on RainLoop.
> 
> 
> I think this issue is about trying the first one. Have you considered the second option?
> 
> Regards.

Rainloop is already integrated in nextcloud, but previously it only allowed you to save attachements to nextcloud but not to upload attachment from your nextcloud files. This issue addresses the attachments problem.

The only thing left to be synced it contacts and that is not a major problem for me personally as I manually add the sync dav and that covers it.

**Comment by cosminadrianpopescu** [comment]
This is another small trick: put the password in the dropbox api key ;). Here is the code: 

```
var _this4 = this; parent.OC.dialogs.filepicker( Choose a file to add as attachment, function (path) { var password = R.a.Dropbox.appKey; var index; for (index = 0; index < path.length; ++index) { var size = 0; var name = path[index].substring(path[index].lastIndexOf("/") + 1, path[index].length); for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) { if (parent.OC.dialogs.filelist[i].name == name) { size = parent.OC.dialogs.filelist[i].size; var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path[index]); var dropboxFile = { link: ncurl, bytes: size, name: name }; _this4.addDropboxAttachment(dropboxFile); } } } },true); return true;
```

**Comment by yward** [comment]
> 
> 
> This is another small trick: put the password in the dropbox api key ;). Here is the code:
> 
> ```
> var _this4 = this; parent.OC.dialogs.filepicker( Choose a file to add as attachment, function (path) { var password = R.a.Dropbox.appKey; var index; for (index = 0; index < path.length; ++index) { var size = 0; var name = path[index].substring(path[index].lastIndexOf("/") + 1, path[index].length); for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) { if (parent.OC.dialogs.filelist[i].name == name) { size = parent.OC.dialogs.filelist[i].size; var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path[index]); var dropboxFile = { link: ncurl, bytes: size, name: name }; _this4.addDropboxAttachment(dropboxFile); } } } },true); return true;
> ```

But wouldn't this only work for the admin account? Since you're using the admin account in rainloop setting as password most likely.

**Comment by cosminadrianpopescu** [comment]
I assumed that every user will have it's own instance of the settings for the application application. I see that this is not the case. But this has a big issue anyway. How can I set the accounts for example? Anyway, I will only have accounts for one user. So, I would say that this is a generic problem of this app. I think that the settings should be isolated for every user.

**Comment by cosminadrianpopescu** [comment]
It's not such a big change to isolate the instances for each user (in which case the above mentioned fix would work). 

In the `rainloop/app/index.php` file, the name of the user needs to be included. Something on these lines: 

```
return @is_dir($sData) ? $sData.'rainloop-storage-'.OC::$server->getUserSession()->getLoginName() : '';
```

And then the admin link should be included for each user's settings page.  Like this, every user could manage his own instance (with his own domains, his own LDAP settings or webdav settings and so on). 

But I don't know if this is in the scope of the project or not. 

@pierre-alain-b : Are you interested in such a pull request? And also, maybe a pull request which should formalize this fix in a nicer way (I would inject the piece of js code from the main frame). Please let me know if I should put the effort.

**Comment by pierre-alain-b** [comment]
I would certainly be interested, would review it with care and then accept!

**Comment by cosminadrianpopescu** [comment]
See #202

**Comment by yward** [comment]
@cosminadrianpopescu 
I believe an isolated user app configuration is not a proper solution. If you only isolate the part for the Dropbox that would be okay, however, most companies like mine and others uses nextcloud as an internal system for staff (non-tech savvy people), think Microsoft Teams, and not all staff (dare I say 99% of staff) know how to setup up API Keys or configure domain names and ports, nor they need to know how to.

While you solution solves the authentication part, it create a whole new package of problems assuming all Nextcloud users are system administrators which is not the case.

@pierre-alain-b I wouldn't force this to master, perhaps a separate branch or an optional release.

**Comment by cosminadrianpopescu** [comment]
> I believe an isolated user app configuration is not a proper solution. If you only isolate the part for the Dropbox that would be okay, however, most companies like mine and others uses nextcloud as an internal system for staff (non-tech savvy people), think Microsoft Teams, and not all staff (dare I say 99% of staff) know how to setup up API Keys or configure domain names and ports, nor they need to know how to.

This is why I asked before if I should go ahead with this. 

I have another solution: 

In nextcloud, we can do `OC.Files.getClient().getFileContents(path)`, which will return us the content. Then, with the content, we can trigger the file upload button, into tricking the browser that we uploaded that file. This way, there would be no need for a password or for isolation. 

However, there are a few issues with this: 

1. The `getFileContents` function will assume that the files returned are text. Since the `responseType` is always set as text. it will fail for binary files (PDF's, for example). So, in order to bypass this, I added a new function `getFileContentsBinary` to the OC client, in the `rainloop.js` file, like this:

```
        watchIFrameTitle();
        const client = OC.Files.getClient();
        const getFileContentsBinary = function(path) {
            if (!path) {
                throw 'Missing argument "path"';
            }
            var self = this;
            var deferred = $.Deferred();
            var promise = deferred.promise();

            this._client.request(
                'GET',
                this._buildUrl(path), {}, null, "blob"
            ).then(
                function(result) {
                    if (self._isSuccessStatus(result.status)) {
                        deferred.resolve(path, result.status, result.body);
                    } else {
                        result = _.extend(result, self._getSabreException(result));
                        deferred.reject(result.status, result);
                    }
                }
            );
            return promise;
        }
        client.__proto__.getFileContentsBinary = getFileContentsBinary.bind(client);
```

Basically it's the same `getFileContents` function, but it sets the `responseType` to `blob`.

2. In triggering the change event on the file input, I've used `DataTransfer` and `createEvent`. I don't know how compatible this is with Microsoft products. 

Here is the `dropboxCommand` function content: 

```
var _this4 = this; parent.OC.dialogs.filepicker("Choose a file to add as attachment", function (path) { var index; for (index = 0; index < path.length; ++index) { var size = 0; var name = path[index].substring(path[index].lastIndexOf("/") + 1, path[index].length); for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) { if (parent.OC.dialogs.filelist[i].name == name) {parent.OC.Files.getClient().getFileContentsBinary(path[index]).then((name, code, content) => {if (code != 200) {return }; const x = document.querySelectorAll('input[type="file"]')[0]; const b = new File([content], name); const l = new DataTransfer(); l.items.add(b); x.files = l.files; const e = document.createEvent('UIEvents'); e.initUIEvent('change', true, true); x.dispatchEvent(e);});} } } },true); return true;
```

Do we care about Microsoft products? And if we do, can anyone test this? (I don't have any Microsoft products in the house)

So, if we care about Microsoft and if my code is compatible, I can have a pull request with the new approach. What does everyone think?

If you think the approach is ok, I would also think about doing a proper Nextcloud integration with a proper PR. This PR should be against this repository, or against the Rainloop webmail repository? 

Cheers,

**Comment by cosminadrianpopescu** [comment]
Update: I've found a Microsoft Edge and `new File()` is not acceptable there. So, do we care about Microsoft products? If we do, then we can have a check, and for IE we ask the password (I would also do something to cache it somewhere, so it would only be asked once) and for a sane browser, we go without password. What do you think?

**Comment by Bolli84** [comment]
@cosminadrianpopescu Your PR is pretty good. Do you mind to take the content of the dropboxcommand to it as well? 
That would make it complete.

Btw: would you like to create another PR for  using mail calendar-imports? Since you also modified the rainloop.js it would make sense.
(I am not a real developer and have my issues with PR and such things.)

**Comment by cosminadrianpopescu** [comment]
> Do you mind to take the content of the dropboxcommand to it as well?

I amended the PR. But the point raised by @yward is valid. Please consider that also before merging.

> Btw: would you like to create another PR for using mail calendar-imports? Since you also modified the rainloop.js it would make sense.

What is "mail calendar-imports"?

**Comment by Bolli84** [comment]
@cosminadrianpopescu 
Yes, it is not effective by using the dropbox-api-key as replacement. You would need to save the password as plain Text....

With mail calendar, i think about this one: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/152#issue-613532704

**Comment by Bolli84** [comment]
@cosminadrianpopescu 
another idea: the custom-settings-tab-plugin would allow such a configuration for an individual user.
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/custom-settings-tab

Easy to change and would be good to allow more integration of rainloop/nextcloud. this could be used as a good interaction space.

**Comment by yward** [comment]
I've been digging into attachmentsActions which is the way attachments are being save to nextcloud but I truly do not get the syntax or how does it work without a password, for example this is the code to save an attachment to your next cloud:
`_proto.saveToOwnCloud = function saveToOwnCloud() {
    var _this5 = this;

    var hashes = this.getAttachmentsHashes();

    if (0 < hashes.length) {
      Promises_User_Ajax__WEBPACK_IMPORTED_MODULE_30__[/* default */ "a"].attachmentsActions('OwnCloud', hashes, this.saveToOwnCloudLoading).then(function (result) {
        if (result && result.Result) {
          _this5.saveToOwnCloudSuccess(true);
        } else {
          _this5.saveToOwnCloudError(true);
        }
      }).catch(function () {
        _this5.saveToOwnCloudError(true);
      });
    } else {
      this.highlightUnselectedAttachments(true);
    }
  };`

While it looks very simple doesn't explain how is it able to save files to the user account without authenticating

This is the success function for example:
` _this.saveToOwnCloudSuccess = ko__WEBPACK_IMPORTED_MODULE_10__[/* default */ "a"].observable(false).extend({
      falseTimeout: 2000
    });`

again not idea how this webpack_imported_module_10 works, but I think it's a good place to start looking for this.

**Comment by andrewborell** [comment]
> I've been digging into attachmentsActions which is the way attachments are being save to nextcloud but I truly do not get the syntax or how does it work without a password, for example this is the code to save an attachment to your next cloud:

Can you please cite the nc version and files? That code looks like reactjs which i dont have much experience with but i can probably sort out how they are authenticating later tonight.  Promise is sonething i use with node and express for options request with CORS. Perhaps the creds are handed back in an options request.  You can probably see what you need to know if you run fiddler from Telerik and go through the steps to trace the requests. Enable https and then use the inspector to view the raw requests. 

Replying from mobile. Sry i cannot be more specific.

**Comment by cosminadrianpopescu** [comment]
Lately, I took a different approach. I discovered the `afterlogic webmail lite` which has an amazing REST api. With this API I was able to implement my own client (for mobile) but being an IONIC application can be used also as a web app. So, I developed also the nextcloud app for it, [here](https://github.com/cosminadrianpopescu/nextcloud-afterlogic-client). 

The thing is that in the app (it's true that I've deployed it in the `apps` folder, not in the `custom_apps`, but normally this should not matter) I have an `iframe` which points to my IONIC angular app (which is a purely js app). But having the same domain, I can do 

```
await OC['Files'].getClient().putFileContents(_path, content);
```

to put a file.

And I can even to a simple `fetch` to retrieve a file content.

```
const content = await fetch(`${FilePicker.basePath}/${path}`);
```

The url is something like `https://<my-cloud>/remote.php/dav/files/<my-user>/<my-nextcloud-folder>/<my-nextcloud-file>.pdf`

And this will work without any issue, since I am already authenticated in the top application.

So I have the impression that the issue here is the user and the password sent in the url. Those should not be needed. The issue here is the way that the dropbox client is fetching the file and that we tried to adapt this to the rainloop application. I think that just developing from scratch the fetch should be much more straight forward. Unfortunately I don't have enough knowledge of the rainloop application. But it should really not be a problem. As I was saying, in my app I am doing this by simply doing a fetch of the url. No header, no nothing.

**Comment by Valdnet** [comment]
@pierre-alain-b I think this feature would be very useful on Railoop. Would make it easy to send files directly from the Nextcloud instance 😉.

**Comment by pierre-alain-b** [comment]
I agree, but I would rather see the topic handled by the Rainloop guys upstream, because this needs potentially real changes within Rainloop itself, beyond the scope of the plugin.

**Comment by Valdnet** [comment]
I asked to add this feature in [Rainloop](https://github.com/RainLoop/rainloop-webmail/issues/2023).

**Comment by yward** [comment]
@Bolli84  @cosminadrianpopescu  so I've faced a small issue with the current solution we are using which was flawless up until this issue appeared (I was okay with having to reauthenticate) .
It seems that you cannot use this hack if you have 2-factor auth enabled (TOTP), even if you use App passwords it'll fail to upload the files, any hints?
Usually app passwords worked fine for other apps that required authentication, but app passwords aren't overwriting the 2fa for this implementation for some reason.

**Comment by Bolli84** [comment]
@yward : you are right. 2-factor cannot be used in this manner. That's why we need to find another solution for that.
I still do not understand, why we cannot use the download into rainloop, whilst upload from rainloop works properly. 

However, my current topic is around the better calendar integration Nextcloud-to-rainloop and i spend the open time on that. (Currently i want to find out about replaying calendar messages :-) )

**Comment by yward** [comment]
> 
> 
> @yward : you are right. 2-factor cannot be used in this manner. That's why we need to find another solution for that.
> I still do not understand, why we cannot use the download into rainloop, whilst upload from rainloop works properly.
> 
> However, my current topic is around the better calendar integration Nextcloud-to-rainloop and i spend the open time on that. (Currently i want to find out about replaying calendar messages :-) )

I'm already using the built-in CardDAV functionality in rainloop along with an app password to keep contacts in Sync, I'd imagine the same work around will work for calendar. Only downside would be that this has to be configured manually for each account, not the best solution but works.

**Comment by Bolli84** [comment]
To my understanding, the issue is the token given by nextcloud. 
Rainloop is embedded as iframe, which makes is very unhandy.

**Comment by webagroprom** [comment]
Any news on this issue? Did anyone manage to implement the nesting feature in rainloop ?

Will someone implement this feature?

Maybe someone can create an attachment attachment function for a fee, if so, how much will it cost?

**Comment by Bolli84** [comment]
With the code posted above (https://github.com/pierre-alain-b/rainloop-nextcloud/issues/42#issuecomment-633115762), it is working. Only backside: You need to enter the password for the file selection. 
I did not manage to avoid or get clear the question on the password, but it is fine for me.

**Comment by webagroprom** [comment]
> With the code posted above ([#42 (comment)](https://github.com/pierre-alain-b/rainloop-nextcloud/issues/42#issuecomment-633115762)), it is working. Only backside: You need to enter the password for the file selection.
> I did not manage to avoid or get clear the question on the password, but it is fine for me.


**I'm coming here**
/nextcloud/apps/rainloop/app/rainloop/v/1.16.0/static/js/app.js

**find:** _proto.dropboxCommand = function dropboxCommand() {

**I replace it with:**

http://joxi.ru/YmEkeY7ULqx6EA

```
_proto.dropboxCommand = function dropboxCommand() {
var _this4 = this;
parent.OC.dialogs.filepicker(
'Choose a file to add as attachment',
function (path) {
var size = 0;
var name = path.substring(path.lastIndexOf("/") + 1, path.length);
var password = prompt("Password please:");
for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
if (parent.OC.dialogs.filelist[i].name == name) {
size = parent.OC.dialogs.filelist[i].size;
var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path);
var dropboxFile = { link: ncurl, bytes: size, name: name };
_this4.addDropboxAttachment(dropboxFile);
}
}
    return true;
  };
```

**I turn on the function:**
http://joxi.ru/MAjMVJXCYoO7D2

**Result:** :(((
http://joxi.ru/823je4QHw3lqam

What am I doing wrong?
Can you tell me how to enable the nesting function using your code?

**Comment by webagroprom** [comment]
**Please help me install this code correctly. Does it work on nextcloud 23 ?**

```
_proto.dropboxCommand = function dropboxCommand() {
var _this4 = this;
parent.OC.dialogs.filepicker(
'Choose a file to add as attachment',
function (path) {
var size = 0;
var name = path.substring(path.lastIndexOf("/") + 1, path.length);
var password = prompt("Password please:");
for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
if (parent.OC.dialogs.filelist[i].name == name) {
size = parent.OC.dialogs.filelist[i].size;
var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path);
var dropboxFile = { link: ncurl, bytes: size, name: name };
_this4.addDropboxAttachment(dropboxFile);
}
}
return true;
};


```

**Comment by brendan-pike** [comment]
> With the code posted above ([#42 (comment)](https://github.com/pierre-alain-b/rainloop-nextcloud/issues/42#issuecomment-633115762)), it is working. Only backside: You need to enter the password for the file selection. I did not manage to avoid or get clear the question on the password, but it is fine for me.

I just looked at testing this and found that the cited code in app.min.js, `ie _proto.dropboxCommand = function dropboxCommand()` no longer exists in the current file.  I see references to dropbox but unless your a programmer it's difficult to work out.

It's such a shame this feature isn't available in the nextcloud rainloop app because it if was it currently it would easily be hands down be the most viable mail app for nextcloud.   But getting official support from nextcloud will never happen now they've released their own mail app.

As a small company we've tested nextcloud mail, rainloop and afterlogic, sadly none are usable so we continue to use external solutions.

**Comment by webagroprom** [comment]
**Friends who can decide on the latest version of nextcloud - rainloop ?**

```
_proto.dropboxCommand = function dropboxCommand() {
var _this4 = this;
parent.OC.dialogs.filepicker(
'Choose a file to add as attachment',
function (path) {
var size = 0;
var name = path.substring(path.lastIndexOf("/") + 1, path.length);
var password = prompt("Password please:");
for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
if (parent.OC.dialogs.filelist[i].name == name) {
size = parent.OC.dialogs.filelist[i].size;
var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path);
var dropboxFile = { link: ncurl, bytes: size, name: name };
_this4.addDropboxAttachment(dropboxFile);
}
}
return true;
};

```

**I really need the option to attach files to rainloop from nextcloud.**
**Is it really possible to make this possible?**

**Comment by Bolli84** [comment]
The code you took out is working.

Open your app.js file, search for _proto.dropboxCommand = function dropboxCommand() { and replace it with code above.
then save it and compress the file to app.min.js

Upload them both into your rainloop location at the correct place.

Is works fine with me

**Comment by webagroprom** [comment]
> The code you took out is working.
> 
> Open your app.js file, search for _proto.dropboxCommand = function dropboxCommand() { and replace it with code above. then save it and compress the file to app.min.js
> 
> Upload them both into your rainloop location at the correct place.
> 
> Is works fine with me

![1651960592923](https://user-images.githubusercontent.com/30408997/167273024-de2af44f-4da0-485e-acae-f40ccb00380d.jpg)

I try again to replace the code in the app.js file, then compress the file into app.min.js and upload it to the server, the function still doesn't work.

You can email me your two files
app.js and app.min.js ? ( my email is in my profile ).

I would upload them to the server and see if the feature worked or not.

**Comment by webagroprom** [comment]
> The code you took out is working.
> 
> Open your app.js file, search for _proto.dropboxCommand = function dropboxCommand() { and replace it with code above. then save it and compress the file to app.min.js
> 
> Upload them both into your rainloop location at the correct place.
> 
> Is works fine with me

**Can you email me two files with changes for rainloop ?**

**I will try to replace my files and see if the function works.**

**Comment by webagroprom** [comment]
Does the above code work for anyone on nextcloud 23 ? rainloop 1.16.0
Can someone who works code, send two files for verification?

**Comment by webagroprom** [comment]
```
_proto.dropboxCommand = function dropboxCommand() {
var _this4 = this;
parent.OC.dialogs.filepicker(
'Choose a file to add as attachment',
function (path) {
var size = 0;
var name = path.substring(path.lastIndexOf("/") + 1, path.length);
var password = prompt("Password please:");
for (var i = 0; i < parent.OC.dialogs.filelist.length; i++) {
if (parent.OC.dialogs.filelist[i].name == name) {
size = parent.OC.dialogs.filelist[i].size;
var ncurl = parent.OC.getProtocol() + "://" + parent.OC.getCurrentUser().uid + ":" + password + "@" + parent.OC.getHostName() + "/remote.php/dav/files/" + parent.OC.getCurrentUser().uid + encodeURI(path);
var dropboxFile = { link: ncurl, bytes: size, name: name };
_this4.addDropboxAttachment(dropboxFile);
}
}
return true;
};
```
Nextcloud 24 - rainloop, don't work  for me.

Does this code work for anyone in Nextcloud version 24?
Can anyone post a working file to replace the current rainloop files in order for the download function to work in the mail client?

**Comment by alahwany** [comment]
i have 1.16.0 with NC 24 and i can't attach files from NC when sending a message

is there any solution for that?

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
