### ISSUE TITLE
How can use webmail Hooks

### ISSUE THREAD

**Issue by yonineitor** [pierre-alain-b/rainloop-nextcloud#43]
How can i use hooks in rainloop, this APP is awesome but i need callback from my Personal App.

I wish could do something like this:
```php
//from myapp: Hook sending email
$RAINLOOP->AddHook('filter.smtp-from', function( $args ){ ............... });
```

**Comment by pierre-alain-b** [comment]
I am not sure to understand what you are looking for. If you could explain more precisely what is your objective, it would help.
Thanks!

**Comment by pierre-alain-b** [comment]
Closing as the issue is not clear.
