### ISSUE TITLE
Keep user logged in

### ISSUE THREAD

**Issue by mehrdad-shokri** [pierre-alain-b/rainloop-nextcloud#44]
I've successfully installed Rainloop. I Also can log in successfully.  
But when a refresh occurs user gets logged out. How can I keep the user logged in?

**Comment by pierre-alain-b** [comment]
This is an unusual behavior. Which version of Rainloop / Nextcloud do you use? Which browser? Any error message in the log files?

**Comment by mehrdad-shokri** [comment]
Sorry, guess you meant unusual, right?  
Nextcloud:  13.0.0.5,
RainLoop:  5.0.6,
Chrome: 63

**Comment by mehrdad-shokri** [comment]
No logs generated. But I can see Rainloop cookies set when logged in. 
I see after page refresh cookie is still there but asks for credentials from me again

**Comment by pierre-alain-b** [comment]
Yes sorry, I meant unusual. I updated the comment.
You have set up the username and password in the personal admin settings, right?
![image](https://user-images.githubusercontent.com/386857/34463108-e220ae60-ee52-11e7-9ab1-4afef81d543a.png)

**Comment by pierre-alain-b** [comment]
And the remember me option as well?

![image](https://user-images.githubusercontent.com/386857/34463123-1b856312-ee53-11e7-9be4-e9f648f484c5.png)

**Comment by mehrdad-shokri** [comment]
Sorry, all I had to do was to check Remember me. thank you.
