### ISSUE TITLE
Nextcloud 14 - drop of deprecated APIs

### ISSUE THREAD

**Issue by MorrisJobke** [pierre-alain-b/rainloop-nextcloud#45]
Hi just want to inform you that with 14 we will drop for example OCP\Config https://github.com/nextcloud/server/pull/7840

See the PHPDoc in that class for how to handle this now.

Please also have a look at https://github.com/nextcloud/server/issues/7827 for other dropped methods or use the app:code-check to highlight deprecated methods in the current code.

**Comment by pierre-alain-b** [comment]
Well received, thanks for the heads up.

**Comment by MorrisJobke** [comment]
Hi just want to inform you that with 14 we will also drop `linkTo*` methods of `OCP\Util` nextcloud/server#8811

So looking at nextcloud/server#7827 from time to time helps to know of all the dropped stuff ;)

**Comment by MorrisJobke** [comment]
Hi @pierre-alain-b, `OCP\JSON` is deprecated since version 8.1 and will run into the 3 year deprecation time soon. With the upcoming Nextcloud 14 this will not be available anymore. We highly encourage you to move over from those manual checks in the files in `ajax/` to the AppFramework way of writing methods. This then takes care of all the checks that are provided by `OCP\JSON` out of the box. If you need help with the migration please reach out to us. The AppFramework was introduced in ownCloud 7 and thus there should be no problems with this migration regarding being compatible to both vendors.

The removal PR: https://github.com/nextcloud/server/pull/8943
A PR that shows how to move from the `ajax/` files to AppFramework: https://github.com/nextcloud/server/pull/8800

**Comment by pierre-alain-b** [comment]
Hello all, seeing the number number of people asking for it, I am planning to spend some time and try to do it starting this week-end.
Who would accept being a beta-tester? Who would be able to help in reading the code changes and provide comments/suggestions?

I am locking this thread but discussions can happen in #72

**Comment by pierre-alain-b** [comment]
https://github.com/pierre-alain-b/rainloop-nextcloud/releases/download/6.0-stable/rainloop.tar.gz
Published soon for NC14 !
