### ISSUE TITLE
Autologin with Allow 2-Step Verification 

### ISSUE THREAD

**Issue by moz87** [pierre-alain-b/rainloop-nextcloud#48]
I 've define a mail on the my Personnal setting and configure Rainloop to Use 2-Step Verification.

But when I go to Rainloop , I have to retype my mail/password.
I expected to type only the token and not the login/password again

**Comment by pierre-alain-b** [comment]
Can you give us more details on what you do - what you see and what you expect?
Have you well set your email/password here on the Personal page of Nextcloud?
![image](https://user-images.githubusercontent.com/386857/35763934-23641a1e-08b7-11e8-9def-da27f4cf7ea2.png)

**Comment by moz87** [comment]
Sure,

What I do:
On my personnal settings, I configure my Mail
<img width="366" alt="capture d ecran 2018-02-03 a 16 02 47" src="https://user-images.githubusercontent.com/1301752/35771553-fb33567c-092e-11e8-8aaa-ff58c5d87185.png">

On My Rainloop Security Admin Panel, I force TOTP authentication:
With or without Enforce option

<img width="815" alt="capture d ecran 2018-02-03 a 21 59 06" src="https://user-images.githubusercontent.com/1301752/35771566-3085d9a8-092f-11e8-86a1-b9e3231ee203.png">

What I see:

When I click to the Rainloop Icon, I have to retype my mail/password:

<img width="695" alt="capture d ecran 2018-02-03 a 16 03 11" src="https://user-images.githubusercontent.com/1301752/35771572-6cac1776-092f-11e8-9cd8-60ad026885a4.png">


What I expect:
My mail and my password filled, only the token need to be completed.

<img width="454" alt="capture d ecran 2018-02-03 a 22 06 16" src="https://user-images.githubusercontent.com/1301752/35771637-7c09f8a4-0930-11e8-85cc-d381dd256776.png">

**Comment by moz87** [comment]
Je me permets de relancer le sujet.

**Comment by pierre-alain-b** [comment]
This issue has been opened for a very long time. is it still relevant?

**Comment by moz87** [comment]
> This issue has been opened for a very long time. is it still relevant?

The bug remain on the application, so yes.

**Comment by pierre-alain-b** [comment]
OK I can replicate.
Unfortunately, we will need @RainLoop input on this as I am not familiar with the inner workings of Rainloop. I guess the login form should be instructed somehow to take $_ENV['___rainloop_owncloud_email'] as the default value when loading... @RainLoop, if you have an easy fix, this would be tremendous!

**Comment by pierre-alain-b** [comment]
I suggest that you look at the work here on Snappymail: https://github.com/the-djmaze/snappymail/issues/96
