### ISSUE TITLE
posibility to turn of "hashing" of sieve filters

### ISSUE THREAD

**Issue by wociscz** [pierre-alain-b/rainloop-nextcloud#49]
Is it possible somewhere turn off "hashing" of sieve filters?

Why is it there either?
I have multiple webmails for my mailserver and only rainloop is "incompatible" with existing sieve filters edited in another webmail due this base64 magic in filters. And filters saved in rainloop aren't visible in for example roundcube and vice versa.

I'm just peeking into code and maybe it should be possible to rip off this behaviour from sieve plugin.

**Comment by pierre-alain-b** [comment]
I recommend to open this issue on the Rainloop webmail page:
https://github.com/RainLoop/rainloop-webmail
