### ISSUE TITLE
different version for owncloud and nextcloud

### ISSUE THREAD

**Issue by DJCrashdummy** [pierre-alain-b/rainloop-nextcloud#5]
for owncloud there is a newer version (4.27 with rainloop 1.10.5.192 instead of 4.26 with rainloop 1.10.4.183 for nextcloud), and it is also downloaded direct from http://www.rainloop.net/repository/owncloud/rainloop.zip.

- why are 2 different versions needed?
- if it is not possible to merge the own- & nextcloud version, is it possible to provide both direct from the rainloop team?
- if not, is it possible to update the nextcloud-app?

thanks for at least some clarification.

**Comment by pierre-alain-b** [comment]
Good morning,

To be usable with the Nextcloud apps repo, the plugin needs a little bit of refactoring (tiny changes). When Nextcloud 10 was launched and I migrated from oC, I decided to make a package to ease my use of Rainloop and I decided to make it available for anyone as the Rainloop team was not providing it directly. I also backported some of the needed changes to the Rainloop repository.

Yes it is possible to update the nextcloud app, if you have some free time to do it, you can always fork this repo and propose a merge request. I will then gladly push it (after review) on the Nextcloud app repository. Alternatively, you can sure contact the Rainloop team and propose to merge the 2 versions - I will be happy to help in the process.

I hope this clarifies a little bit the situation.

**Comment by DJCrashdummy** [comment]
first thank you for modifying the rainloop-app for nextcloud and providing the work to everyone!

since i'm sadly not a developer and also new to github, i have no clue how to update something like this.
_i just tried a dirty hack within a test-environment: copied the `rainloop/app/`-folder of the owncloud-app 4.27 over the actual and it seems to work... for sure the app itself stays at 4.26.1 but at least rainloop is updated._

as you also noticed there is already a open issue at the rainloop development... https://github.com/RainLoop/rainloop-webmail/issues/1297 but with no reaction within more than 2 months. :-(

**Comment by pierre-alain-b** [comment]
This is not a dirty hack, this is a bold test :-)
Well this is interesting as it suggests that 1.10.5.192 is fully compatible with Nc 11. I will try to push the new version as soon as possible.

**Comment by DJCrashdummy** [comment]
as i said i'm not a developer (means for me: i have no real programing-skills), i don't know how such things are done right! ;-)
i just came across the "official documentation" (https://www.rainloop.net/docs/upgrade/), looked a little bit around on my ftp-server (as manual installation is not a problem) and gave it a try... so it just felt like a dirty hack.

because it is just in a test-environment and setup only since today, i can't confirm everything is really working under heavy usage, but it looks good for now.
i or better my hoster uses for both nextclouds (10 & 11) ubuntu, apache 2, php 7.0 and both run now rainloop 1.10.5.192 although the rainloop-app is 4.27 (NC10) and 4.26.1 (NC11).

**Comment by pierre-alain-b** [comment]
I think this is fixed! I have just pushed 4.27.0 (with the latest release of Rainloop) for NC11!
I've just set it up from the NC apps store and it works.
Enjoy!
