### ISSUE TITLE
Request: allow Rainloop user to auto-save attachments to Files

### ISSUE THREAD

**Issue by sunjam** [pierre-alain-b/rainloop-nextcloud#50]
[See related Nextcloud Mail issue #682](https://github.com/nextcloud/mail/issues/682) for reference.  The idea is allowing an unprivileged user to mail attachments directly into a Nextcloud files directory.  Services like Evernote offer this as a premium feature, and it is a fantastic way to be able to directly email yourself files.
    
Use case: a teacher sets up user _submissions@example.com_ where students can easily send homework files for review.

**Comment by DJCrashdummy** [comment]
@sunjam i'm not 100% sure that i got everything completely right, but it seems that you can achieve this with an other nextcloud-app: [Files From Mail](https://apps.nextcloud.com/apps/files_frommail)... a look at its [readme](https://github.com/nextcloud/files_frommail/blob/master/README.md) may be a good idea. :wink:

**Comment by pierre-alain-b** [comment]
I agree with DJCrashdummy that Files From Mail seems to make it. I am therefore closing the ticket.
