### ISSUE TITLE
Auto-Login after "Passwords-App" broken

### ISSUE THREAD

**Issue by ThePatzen** [pierre-alain-b/rainloop-nextcloud#54]
Hi!

When switching to the Passwords-App and back again the user is not loggedin automatically.
 
Passwords-App: https://apps.nextcloud.com/apps/passwords
Using latest Apps&Nextcloud on PHP7.2!

Best Regards,
David

**Comment by pierre-alain-b** [comment]
Hello, I am not sure to understand the situation. Could you please detail steps to reproduce the issue?
Thanks
