### ISSUE TITLE
Advice on how to connect rainloop Addressbook to my Nextcloud Contacts

### ISSUE THREAD

**Issue by greavette** [pierre-alain-b/rainloop-nextcloud#58]
Hello,

Can anyone provide some assistance on how I can connect my Rainloop Mail App to use my Nextcloud Contacts? 

Thank you.

**Comment by GoetheG** [comment]
Hi @greavette ,

To the best of my knowledge there is no such option. Unfortunately RainLoop has only limited functions which di not allow collaborative functions. Maybe it'll change. I'd welcome this. But for now that's all I can say.

Cheers

**Comment by pierre-alain-b** [comment]
Rainloop is compatible with CardDAV. You can therefore connect Rainloop to your Rainloop contacts through CardDAV.
Within Rainloop for Nextcloud, go in "Settings", then "Contacts". The 2nd half of the screen presents "Remote Synchronization (CardDAV)". You can enable and configure the module to talk to your Nextcloud instance.

**Comment by brdobrdo** [comment]
This doesn't work. It gives error.
