### ISSUE TITLE
ownCloud-app 4.28 with RainLoop 1.11.0.203

### ISSUE THREAD

**Issue by DJCrashdummy** [pierre-alain-b/rainloop-nextcloud#6]
damn it... they released on 12.03.2017 a new version of RainLoop and the ownCloud-app.

- therefore i guess the trigger-issue https://github.com/RainLoop/rainloop-webmail/issues/479 is dead.
- and although they don't really respond to anything, it seems that they appreciate your work sine they [link it on their homepage](http://www.rainloop.net/downloads/).
- obviously the only action they took was closing the issue https://github.com/RainLoop/rainloop-webmail/issues/1297 after hinting.

i don't have time to test the new version now... maybe next week! ;-)

**Comment by pierre-alain-b** [comment]
Well, this is positive if this means that
i) the Rainloop dev continues
ii) they recognize it is useful to embed it in Nextcloud!

I will prepare a new package with the new version and test it.

**Comment by pierre-alain-b** [comment]
I've just pushed 4.28.0 to the Nextcloud app repository! It works seamlessly on my Nextcloud.
Best
PAB

**Comment by DJCrashdummy** [comment]
**for sure it is positive that the RainLoop development continues!**
i was cursing because just less than a week before you've done all the work for the previous version and this would have been able to prevent with more collaboration or at least a little bit more information... :-/
_(...and sad that my assumption with the trigger-issue was right.)_

recently updated to & happy with 4.28.1 and thank you for your work again!
