### ISSUE TITLE
Show identity not 123214124mail1@domain.com

### ISSUE THREAD

**Issue by Ser1ous1** [pierre-alain-b/rainloop-nextcloud#60]
![unbenannt](https://user-images.githubusercontent.com/33761882/39678164-f002a6d0-5187-11e8-8f3f-dba7cb94f5f8.jpg)

Show the default identity (user@domain.com)

**Comment by pierre-alain-b** [comment]
It does show the account that was set up. It is more relevant to show the account set up by the user than an identity as identities are not necessarily related to mail accounts.
