### ISSUE TITLE
please update to latest rainloop version 1.12.0 #efail

### ISSUE THREAD

**Issue by nextgen-networks** [pierre-alain-b/rainloop-nextcloud#61]
Version 1.12.0 dated 2018-05-01 is the most recent version today
see: https://www.rainloop.net/downloads/

Why?
Security! :-)

https://efail.de/efail-attack-paper.pdf

Thanks for your hard work!

**Comment by Larsene** [comment]
Please !

**Comment by pierre-alain-b** [comment]
Yep, I plan to do it this week-end!

**Comment by pierre-alain-b** [comment]
And thanks for signalling the new version!

**Comment by pierre-alain-b** [comment]
5.1.0 published a few minutes ago! Let me know if you encounter any issue.
