### ISSUE TITLE
After upgrade to 5.1.0 - not work - I need help

### ISSUE THREAD

**Issue by peemek** [pierre-alain-b/rainloop-nextcloud#66]
After upgrade Rainloop to the version 5.1.0 for snap (!) Nextcloud in Ubuntu 16 I get a message like this in my browser:
"[105] Missing version directory".

I need help in restarting this great plugin.

**Comment by pierre-alain-b** [comment]
Hello,
What do you mean "for snap (!)" ?
Do you have access to the instance folder via SSH or other methods?
PAB

**Comment by peemek** [comment]
I did not install Nextcloud directly on Ubuntu. I installed the "Nextcloud snap package" on Ubuntu.
I installed your super plugin for that, it worked until the plugin was updated from Nextcloud.
Yes, I have access through SSH, Webmin and others.

**Comment by peemek** [comment]
After installing the Rainloop update there was no message about the need to restart. However, I restarted the computer and now Rainloop is working properly :) The problem is probably solved.

**Comment by pierre-alain-b** [comment]
Thank you for updating us!
