### ISSUE TITLE
RL keeps loading in IE

### ISSUE THREAD

**Issue by PSAH1** [pierre-alain-b/rainloop-nextcloud#67]
Hi guys,

I'm using Rainloop App 5.1.0 on Nextcloud 13.0.1. When using Rainloop on IE, the apps keeps loading and never finishes.

Is there any known solution for this issue?

Best regards
Phil

**Comment by pierre-alain-b** [comment]
Hi there, which version of IE is it?

**Comment by PSAH1** [comment]
Hi Pierre,

thanks for your reply.

Its MS Edge, Version 42.17134.1.0

Best regards

**Comment by pierre-alain-b** [comment]
Do you have the same behavior on the same instance of RL with another browser?
(just trying to figure out if this is browser-specific)

**Comment by PSAH1** [comment]
works fine with chrome & firefox

**Comment by DonPIZI** [comment]
same problem here, chrome works fine and ie11 keeps loading :/

**Comment by pierre-alain-b** [comment]
Can you try the online demo of Rainloop here: https://mail.rainloop.net/
It will help identify if this a Rainloop issue or an issue with Rainloop in nextcloud.
Isn't there any developer mode with a console in IE that could help detect the error message (sorry, I am not using Edge)?

**Comment by DonPIZI** [comment]
same problem ... I don't have any access to another browser or a console on my work PC

**Comment by pierre-alain-b** [comment]
So it seems this is a Rainloop issue and this is not linked to the plugin itself

**Comment by pierre-alain-b** [comment]
I recommend that you post this issue on the Rainloop page.
