### ISSUE TITLE
 Nextcloud 11.0.2 : [202] Data folder permissions error [is_dir]

### ISSUE THREAD

**Issue by DevSidious** [pierre-alain-b/rainloop-nextcloud#7]
I have Rainloop installed and activated in Nextcloud 11.0.2.

Clicking on "Go to RainLoop Webmail admin panel" in Admin - Additional Settings =>
**[202] Data folder permissions error [is_dir]**

Clicking on the RainLoop mail icon =>
**[202] Data folder permissions error [is_dir]**

Downloaded the check.php from here: 

https://github.com/RainLoop/rainloop-webmail/issues/262

It passes all tests.

No SELinux active in my system and the entire Rainloop folder is recursively chmoded to 777 and owned by the webserver (Apache).

**Comment by pierre-alain-b** [comment]
Thanks for reporting.
The error seems to be "[is_dir]" which makes me think it is not a permission issue. The error is generated here:
https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/include.php
```
case !@is_dir(APP_DATA_FOLDER_PATH):
						$sTest = 'is_dir';
						break;
```
Have you updated Rainloop for Nextcloud from the previous version? Can you try to totally uninstall Rainloop for nextcloud and re-install it?
I am using the same version and it works on my side.
PAB

**Comment by pierre-alain-b** [comment]
OK I start to understand: it seems that the data folder of your nextcloud instance is not found. Where is the data folder for your nextcloud instance? I have indeed a rainloop_storage folder in it where rainloop data are stored.

Here is the function call to determine this APP_DATA_FOLDER_PATH : 
```
			function __get_custom_data_full_path()
			{
				$sData = __DIR__.'/../../data/';
				if (class_exists('OC_Config'))
				{
					$sData = rtrim(trim(OC_Config::getValue('datadirectory', '')), '\\/').'/';
				}
				else if (class_exists('OC'))
				{
					$sData = rtrim(trim(OC::$server->getSystemConfig()->getValue('datadirectory', '')), '\\/').'/';
				}

				return @is_dir($sData) ? $sData.'rainloop-storage' : '';
			}
```

**Comment by pierre-alain-b** [comment]
I've just tested on a fresh install of Nextcloud. No issue with the Rainloop plugin.

**Comment by DevSidious** [comment]
Thank you for the quick reaction.

In my deployment, the sub folders "data" and "apps" inside my root Nextcloud folder, are symlinks pointing to  /mnt/volume/nextcloud/apps and /mnt/volume/nextcloud/data/ as it can be glanced here:

lrwxrwxrwx  1 apache apache    32 Mar 19 02:27 apps -> /mnt/volume/nextcloud/apps
lrwxrwxrwx  1 apache apache    33 Mar 18 19:32 data -> /mnt/volume/nextcloud/data/

I copied the code you pasted in an php file and ran it from inside /mnt/volume/nextcloud/apps/rainloop . It gives:

 php -f datafolder.php
/mnt/volume/nextcloud/apps/rainloop/../../data/rainloop-storage

When one goes ../../data from inside /mnt/volume/nextcloud/apps/rainloop , one ends up in /mnt/volume/nextcloud/data , which IS the data folder of my installation.

I hope that helps.

**Comment by pierre-alain-b** [comment]
And if you call
```
<?php
print(is_dir("/mnt/volume/nextcloud/apps/rainloop/../../data/rainloop-storage"));
?>
```
What do you have?

**Comment by pierre-alain-b** [comment]
Maybe a hint here?
http://stackoverflow.com/questions/6969901/is-dir-returning-false-on-symlinks-in-apache

**Comment by pierre-alain-b** [comment]
In the doc for 'is_dir', I see:

> filename
>     Path to the file. If filename is a relative filename, it will be checked relative to the current working directory. If filename is a symbolic or hard link then the link will be resolved and checked. If you have enabled safe mode, or open_basedir further restrictions may apply.

Do you have safe_mode or open_basedir with further restrictions?

**Comment by DevSidious** [comment]
Running

```
<?php
print(is_dir("/mnt/volume/nextcloud/apps/rainloop/../../data/rainloop-storage"));
?>
```

returns 1.

No relevant **safe_mode** or **open_basedir** settings:

php -i | grep "Loaded Configuration File"
Loaded Configuration File => /etc/php.ini

cat /etc/php.ini | grep basedir
; open_basedir, if set, limits all file operations to the defined directory
; http://php.net/open-basedir
;open_basedir =

```
<?php
if (ini_get('safe_mode')) {
        print("Safemode ON");
}else {
        print("Safemode OFF");
}
?>
```

php -f check.php
Safemode OFF

I also run this code from inside my root Nextcloud installation to see if it recognizes the "data" symlink as a folder:

```
<?php
if (is_dir("data")) {
         print("'data' is a directory\n");
} else {
        print("'data' is not a directory\n");
}
?>
```
php -f check.php
'data' is a directory

I also reinstalled the app and run this:

```
<?php
clearstatcache();
print("Cleared: file status cache.");
?>
```

**Comment by pierre-alain-b** [comment]
Thank you for all these checks.

So the key is in this file:
https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/include.php

Somehow this test returns true:
```
				case !@is_dir(APP_DATA_FOLDER_PATH):
						$sTest = 'is_dir';
						break;
```

and APP_DATA_FOLDER_PATH is defined here:
```
			$sCustomDataPath = function_exists('__get_custom_data_full_path') ? rtrim(trim(__get_custom_data_full_path()), '\\/') : '';
			define('APP_DATA_FOLDER_PATH', 0 === strlen($sCustomDataPath) ? APP_INDEX_ROOT_PATH.'data/' : $sCustomDataPath.'/');
			unset($sCustomDataPath);
```

Normally, within Nextcloud, get_custom_data_full_path() returns the path to the data folder. You tested that and it seemed to work. Can you try to print the content of APP_DATA_FOLDER_PATH after initialization?

**Comment by DevSidious** [comment]
No, this function is the culprit:
```
                       function __get_custom_data_full_path()
                        {
                                $sData = __DIR__.'/../../data/';
                                if (class_exists('OC_Config'))
                                {
                                        $sData = rtrim(trim(OC_Config::getValue('datadirectory', '')), '\\/').'/';
                                }
                                else if (class_exists('OC'))
                                {
                                        $sData = rtrim(trim(OC::$server->getSystemConfig()->getValue('datadirectory', '')), '\\/').'/';
                                }

                                return @is_dir($sData) ? $sData.'rainloop-storage' : '';
                        }
```

On my system the execution reaches inside the **else if** and **$sData** becomes: '/' . Which is the root of the nextcloud installation, meaning it tries to access '/rainloop-storage' and of course it fails because there is nothing there.

Commenting out
`$sData = rtrim(trim(OC_Config::getValue('datadirectory', '')), '\\/').'/';`
and
`$sData = rtrim(trim(OC::$server->getSystemConfig()->getValue('datadirectory', '')), '\\/').'/';`

fixes the issue.

**OC_Config::getValue** and **OC::$server->getSystemConfig()->getValue** seem unreliable, while **$sData = __DIR__.'/../../data/';** produced the correct result even in a custom setup such as mine.

**Comment by DevSidious** [comment]
A possible solution:

```
 function __get_custom_data_full_path()
                        {
                                $sData = __DIR__.'/../../data/';
                                $ocData = '';
                                
                                if (class_exists('OC_Config'))
                                {
                                        $ocData = rtrim(trim(OC_Config::getValue('datadirectory', '')), '\\/').'/';
                                }
                                else if (class_exists('OC'))
                                {
                                        $ocData = rtrim(trim(OC::$server->getSystemConfig()->getValue('datadirectory', '')), '\\/').'/';
                                }

                                return @is_dir($ocData) ? $ocData.'rainloop-storage' : $sData.'rainloop-storage';
                        }
```

**Comment by pierre-alain-b** [comment]
I like it. I will test it on my instance.

**Comment by DevSidious** [comment]
Thanks for writing this great extension and last but not least for your assistance during  precious weekend hours. :)

**Comment by pierre-alain-b** [comment]
FYI, I have pushed 4.28.1 with the suggested fix. It should now work seamlessly for you. It works very well with this fix for me on the two instances I use.

**Comment by oljask** [comment]
Let me mention my solution for problem with same symptom, since this thread is only one I have found in google:
my config.php was missing this line:
`'datadirectory' => '/usr/local/www/nextcloud/data',`
when I added it the [202] Data .... [is_dir] message gone

**Comment by Obada8** [comment]
You should set the path of the data folder in `open_basedir`

for example:
`php_admin_value open_basedir "/tmp:$VH_ROOT:/usr/local/lscp/cyberpanel/rainloop"
`
