### ISSUE TITLE
Feature Request: CardDav auto-login with Nextcloud credentials

### ISSUE THREAD

**Issue by ehprivacy** [pierre-alain-b/rainloop-nextcloud#70]
Just as you can tell nextcloud to auto-login to Rainloop via the nextcloud credentials, it would be amazing if Rainloop's carddav would do the same thing.

**Comment by ehprivacy** [comment]
I just noticed that when starting a new email, it will auto-suggest email addresses present in my nextcloud contacts list, but they don't show up in the rainloop "contacts" modal (without setting up carddav sync).  Have I done something wrong somewhere in my configuration?

**Comment by th-schwarz** [comment]
In your rainloop settings for contacts you can activate the Remote Synchronization (CardDAV).

But it would be a cool feature, if this would be done by the plugin!

**Comment by pierre-alain-b** [comment]
Duplicate of #52 somehow.
