### ISSUE TITLE
Custom HTML Editor

### ISSUE THREAD

**Issue by m-paniez9292** [pierre-alain-b/rainloop-nextcloud#71]
Hi,
Is there a way to customize HTML editor view ?
I would like to add some buttons.

I change config.js, but it seems don't work.

I just see config.js file is never called.

Thanks

**Comment by pierre-alain-b** [comment]
Hi, this is more a question to ask on the main rainloop repository!

**Comment by m-paniez9292** [comment]
Hi,

I don't think so, because the directory structure is a little bit different.

In fact, if you can say me where can I put my js file call, I think it'll be ok.

Thanks
