### ISSUE TITLE
Rainloop for Nextcloud 14

### ISSUE THREAD

**Issue by Larsene** [pierre-alain-b/rainloop-nextcloud#72]
Hi, Since the update to Nextcloud 14, Rainloop doesn't work anymore.

Thanks for your help :-)

**Comment by pierre-alain-b** [comment]
Rainloop for Nextcloud is not available for NC 14 due to changes in the API for the moment.

**Comment by pierre-alain-b** [comment]
See #45

**Comment by Larsene** [comment]
Oh, i'm disappointed as i really like Rainloop for managing my emails :-/

Thanks for your answer anyway, hope we'll see some help.

**Comment by Bolli84** [comment]
Same to me. Rainloop is far better than internal Mail. 
Is there a List of work to do for NC14?

**Comment by pierre-alain-b** [comment]
Hi there,
Basically the API calls that are deprecated should be removed and changed with the new logics. It may not be a huge work. If you have some experience with NC API, it could even be quick. If we get to a sthg functional, I would be happy to reship Rainloop for NC14.
I totally agree the Mail app is not mature enough for now.
PAB

**Comment by feutl** [comment]
I am just watching the Nextcloud Livestream and what should I say, look at the slide at [2:42:39](https://youtu.be/QGVCVC04u5o?t=2h42m39s)

The most used apps ;) in Tirana - first in the list Rainloop
Damn, if this is not a reason to get going :)

**Comment by pierre-alain-b** [comment]
Yes, I should really find a way to devote time to this.

**Comment by ghost** [comment]
@pierre-alain-b Is there a designated issue for NC14 update work?

**Comment by nado** [comment]
#45 as mentioned in third post of this issue ;)

**Comment by ghost** [comment]
Let's start a bounty on #45 then, would you chime in @nado? I'm thinking 10$ each for starters.

**Comment by nado** [comment]
I have neither time nor money at the moment, Within a month that should change though, thats why I react to issues now, in order to either help with feedback/add bounty or work on it later ;)

**Comment by accima** [comment]
Without this app many of us will not be able to upgrade to version 14 of nextcloud, it´s so necessary.

The official mail app is not an real option, at least for the moment, and possibly in a long time. It´s sad.

**Comment by gcotnoir** [comment]
How much would it cost to hire someone?

**Comment by PoGo606** [comment]
Same here, I first migrated to Nextcloud because of Rainloop integration. I and multiple users in my instance are using it everyday.
That would be nice if this project find its new maintainer!

**Comment by pierre-alain-b** [comment]
Hello all, seeing the number number of people asking for it, I am planning to spend some time and try to do it starting this week-end.
Who would accept being a beta-tester? Who would be able to help in reading the code changes and provide comments/suggestions?

**Comment by PoGo606** [comment]
> 
> 
> Hello all, seeing the number number of people asking for it, I am planning to spend some time and try to do it starting this week-end.
> Who would accept being a beta-tester? Who would be able to help in reading the code changes and provide comments/suggestions?

I can help with the beta-testing!

**Comment by nado** [comment]
Same here, I have no problem testing beta versions.

**Comment by gcotnoir** [comment]
> 
> 
> Hello all, seeing the number number of people asking for it, I am planning to spend some time and try to do it starting this week-end.
> Who would accept being a beta-tester? Who would be able to help in reading the code changes and provide comments/suggestions?

I'm available for beta testing. Dans la langue de Molière or Shakespeare's.

I'm also open to help financially anyone who can keep this app updated for the community.

**Comment by tabp0le** [comment]
@nextgen-networks and I have it working. https://github.com/nextgen-networks/rainloop-nextcloud

**Comment by pierre-alain-b** [comment]
Merged in the branch nc14. nc13 branch created to keep the previous version. All precedent releases re-named to mention that they are for nextcloud 10 to 13. A few changes made in nc14 branch. Will make a release just after testing.

**Comment by nextgen-networks** [comment]
@pierre-alain-b - you know where to ring if you need beta testers ;-)

**Comment by pierre-alain-b** [comment]
Ok folks, could you please test the pre-release of 6.0? 
https://github.com/pierre-alain-b/rainloop-nextcloud/releases/download/6.0/rainloop.tar.gz

It is based on the work of @nextgen-networks and @tabp0le that I have merged. Coud you please report any issue in this thread so that we determine if it is good to go to stable and then to be uploaded on the Nextcloud apps store?

Thank you to all!

**Comment by nextgen-networks** [comment]
... atm i face only a minor optical glitch.
An white border on bottom:
![rainloop_6_beta_white_bottom](https://user-images.githubusercontent.com/21206978/45533368-bc5fcc00-b7f7-11e8-8c03-59b7f40d1d40.jpg)

**Comment by feutl** [comment]
Can you also update the base installation from rainloop 1.12.0 to 1.12.1?
https://github.com/RainLoop/rainloop-webmail/releases/tag/v1.12.1

As far as I understood, this was not happening, or did I miss it?

**Comment by pierre-alain-b** [comment]
Rainloop 1.12.1 is already embedded in Rainloop for Nextcloud 6.0-beta-1

**Comment by simonbuehler** [comment]
awesome, you made my day!
running again on 14 with just the white gap but functions do work so far :1st_place_medal:

**Comment by pierre-alain-b** [comment]
@tabp0le and @nextgen-networks, the congratulations are for you.
We have already 3 testimonies of working instance. Let's wait for a few more before shipping stable in Nextcloud apps repository.

**Comment by ghost** [comment]
Hi !
I just push the beta version on our test NC 14 server, everything is ok for now.
Thanks all.

**Comment by nextgen-networks** [comment]
> ... atm i face only a minor optical glitch.
> An white border on bottom:
> ![rainloop_6_beta_white_bottom](https://user-images.githubusercontent.com/21206978/45533368-bc5fcc00-b7f7-11e8-8c03-59b7f40d1d40.jpg)

my assumtion: below border results of removed `<div>` attribute from that change:
_FIx styling for iframe /_ https://github.com/pierre-alain-b/rainloop-nextcloud/commit/cdcd79e2f94b1b720940f54c32c78b4eec296f5f

Some "stylers" out here to fix those last glitch for happy rainloop users? ;-)

**Comment by gymnae** [comment]
Thank you, I can also confirm that the beta works, albeit the visual glitch.

**Comment by pierre-alain-b** [comment]
I confirm this seems to work well.
Regarding the visual glitch, it disappears indeed when we put back the div deleted in cdcd79e. Why was it removed in cdcd79e? @tabp0le any idea?

**Comment by pierre-alain-b** [comment]
I also fixed it by keeping the div deleted but updating buffer to 0 (and not 5, 5 pixels of white) in js/resize.js... will push a new beta with this minor change just to make sure it works for everyone

**Comment by nextgen-networks** [comment]
@pierre-alain-b 
We had an blank window when keeping the div tag.
Only top navigation of nextcloud was displayed.
This occurred only in NC14.

**Comment by pierre-alain-b** [comment]
Was working fine with NC14 and the div, but never mind, it is gone for good now. And no more whitespace with a buffer at 0 in resize.js.

**Comment by tabp0le** [comment]
> Was working fine with NC14 and the div, but never mind, it is gone for good now. And no more whitespace with a buffer at 0 in resize.js.

How weird!? Before deleting the div as @nextgen-networks said, it was all whitespace. lmao. Good job though, glad you fixed it :+1:  Thanks!

**Comment by pierre-alain-b** [comment]
I am publishing the 6.0 version in the Nextcloud apps repository.
Here it is https://github.com/pierre-alain-b/rainloop-nextcloud/releases/download/6.0-stable/rainloop.tar.gz

I will close this thread, do not hesitate to open new threads if you detect bugs!

**Comment by julijane** [comment]
@pierre-alain-b I tried the version you posted two hours ago and it does not work. I enable it and then nextcloud shows it as disabled again. Error from log (shortened):

{"Exception":"Error","Message":"Class 'OCP\\Config' not found"

**Comment by tabp0le** [comment]
> 
> 
> @pierre-alain-b I tried the version you posted two hours ago and it does not work. I enable it and then nextcloud shows it as disabled again. No error in log. Any idea?

On NC 14? How did you install/enable it? Manually or from app store?

**Comment by julijane** [comment]
Sorry, nevermind. Configuration problem, overwrote the "wrong" app. Works now. Thank you.

**Comment by cyrg38** [comment]
last nc14 works for me : hurray !

**Comment by nado** [comment]
Tested with web updater from nc 14, works like a charm, big thanks for the work done!

**Comment by gruessung** [comment]
Yeah! Thanks for your work!
Works great 👍

**Comment by beankylla** [comment]
Merci beaucoup Pierre-Alain!
