### ISSUE TITLE
Not able to active v6.0.0 in Nextcloud v14.0.1 or v14.0.2 RC1

### ISSUE THREAD

**Issue by jnstllng** [pierre-alain-b/rainloop-nextcloud#78]
Today I updgraded my Nextcloud instance to v14 and also updated Rainloop to v6.0.0 in order to be able to use it. Unfortunately, it was not possible to activate it. I went through the file structure and found that the dependencies need to be changed in _/apps/rainloop/appinfo/info.xml_ from nextcloud max-version 14 to 15
```
<dependencies>
<php min-version="5.4" />
		<owncloud min-version="6" max-version="9.2" />
		<nextcloud min-version="14" max-version="15" />
</dependencies>
```
Afterwards, all was fine and I was able to use it.

**Comment by pierre-alain-b** [comment]
Good point, min14 and max14 was certainly good for 14.0.0 only. I will fix this and publish a new version. Thanks for pointing this out!

**Comment by Henk57** [comment]
Fine. I made it 14.9 to avoid new conflicts with release 15.

**Comment by pierre-alain-b** [comment]
6.0.1 was released in the app store with fixed max-version value.

**Comment by jnstllng** [comment]
New version works for me, but max-version is stille set to 15.

**Comment by pierre-alain-b** [comment]
I am not sure to undertstand why 15 is an issue ?

**Comment by jnstllng** [comment]
For me this is no issue. Henk mentioned it was set to 14.9
