### ISSUE TITLE
NC14 + Rainloop 6.0.1 blank page

### ISSUE THREAD

**Issue by peillarot** [pierre-alain-b/rainloop-nextcloud#79]
Hi,
Since a few weeks, rainloop app return blank page on my nextcloud.
I was on NC 13 with up to date rainloop app. I ipdated my NC to 14, and app to 6.0.0 with the same issue.
Actually i have the same problem with version 6.0.1.
On control pannel, all seems to be fine. I can access fine to rainloop using https://mysqdn/index.php/apps/rainloop/app/ but not in nextcloud. No code returned in frame, just a blank page.

On my apache logs, all seems to be fine. I activate rainloop logs, and all looks like to be fine.

I'm running debian 8.11, apache 2.4.10, php 7.0.32 with nginx front-end.

I have forgot something ?

Thanks in advance,
Ludovic

**Comment by pierre-alain-b** [comment]
Hi,
Which browser do you use?
Could you try to open the page with the Developer mode activated (Ctrl+Shift+K in Firefox) and see if you have errors?
PAB

**Comment by peillarot** [comment]
Hi,
After the ost of the issue, i search browser security issues, and solve my
problem.

It was my X-Frame-Options header : he was configured as DENY (nextcloud
recommandation, as fas as i remember) : the problem is resolved.

I'm sorry, it was a simple mistake.

I will close the issue, thank you,

Sincerely

Ludovic

**Comment by bluehood** [comment]
Hi @peillarot and @pierre-alain-b , I have the same issue but I'm running nextcloud's docker container behind an apache reverse proxy.

What configuration should I change to make things work? As far as I can tell I'm not explicitly setting X-Frame-Options to DENY anywhere..?

**Comment by peillarot** [comment]
Hi enrico,
I fixed my issue setting X-Frame-Options to "SAMEORIGIN;" : in my case,
rainloop and nextcloud are on the server.

You probably need to change your X-Frame-Options from the most permissive
to more secure gradually...

Hope i helped,

Sincerely,

Ludovic

Le jeu. 4 juil. 2019 à 14:59, Enrico Guiraud <notifications@github.com> a
écrit :
