### ISSUE TITLE
"Automatically login ..." does not work

### ISSUE THREAD

**Issue by Huster-at-github** [pierre-alain-b/rainloop-nextcloud#8]
![image](https://cloud.githubusercontent.com/assets/3857906/24083004/4170fa98-0ccf-11e7-8d94-4b5dbb71552b.png)

- Configured with admin panel GMX server login addresses etc.
- Access to GMX / login to RainLoop with that account data works
- **Don't want to put in credentials at every startup of RainLoop**
- Set checkbox "Automatically login ..."
- Cannot login to Rainloop without filling in my GMX credentials again.

Would you please explain this configuration point?

**Comment by pierre-alain-b** [comment]
Well... if you tick this box, then your Nextcloud user/email/password will be used to get access to your emails.

If you want to auto-login, go in your personal settings in nextcloud and then in the "rainloop webmail" category. There fill in your username and password for email.

I acknowledge the documentation is much too scarce. Don't hesitate to contribute - I would gladly welcome additions to the doc!

**Comment by Huster-at-github** [comment]
> If you want to auto-login, go in your personal settings in nextcloud and then in the "rainloop webmail" category. There fill in your username and password for email.

There is no RainLoop section in the personal settings page.

**Comment by pierre-alain-b** [comment]
Are you sure? You don't see this?

![image](https://cloud.githubusercontent.com/assets/386857/24094568/94efdf2e-0d59-11e7-86c9-d0f62f0c4d1c.png)

**Comment by Huster-at-github** [comment]
![bildschirmfoto vom 2017-03-20 21-35-15](https://cloud.githubusercontent.com/assets/3857906/24120638/99574e60-0db5-11e7-8a3c-87c5791ff395.png)
----
![bildschirmfoto vom 2017-03-20 21-32-41](https://cloud.githubusercontent.com/assets/3857906/24120639/995f3346-0db5-11e7-816e-290922da5abe.png)
----
![bildschirmfoto vom 2017-03-20 21-31-32](https://cloud.githubusercontent.com/assets/3857906/24120640/99606f90-0db5-11e7-9d31-c64087038306.png)

**Comment by pierre-alain-b** [comment]
Well, this is strange and I don't understand this discrepancy... I assume you already tried to disable and then re-enable the Rainloop app? Just in case...

**Comment by Huster-at-github** [comment]
> I assume you already tried to disable and then re-enable the Rainloop app?

Just tried it .... no RainLoop in Personal .... :(

**Comment by DJCrashdummy** [comment]
@Huster-at-github: deactivate the checkbox "Automatically login **with ownCloud user credentials**" in the admin-settings (like this https://cloud.githubusercontent.com/assets/3857906/24083004/4170fa98-0ccf-11e7-8d94-4b5dbb71552b.png), don't forget to save and the rainloop-section in the personal-settings (like here https://cloud.githubusercontent.com/assets/386857/24094568/94efdf2e-0d59-11e7-86c9-d0f62f0c4d1c.png) will appear.

**Comment by Huster-at-github** [comment]
Aaaaahhhhhh ....... thanks a lot, @DJCrashdummy !    :-)

![image](https://cloud.githubusercontent.com/assets/3857906/24312247/f5b01b0e-10d7-11e7-9ac1-3601c0b78d21.png)

**Comment by DJCrashdummy** [comment]
well... it is not perfect that the login with the cloud-credentials can only be activated globally, and especially if so that they can not be overwritten by special user-credentials...! :-(

**Comment by Huster-at-github** [comment]
In don't understand.

Would please anyone of the App developers explain these settings in the readme.md?

**Comment by pierre-alain-b** [comment]
Thank you @DJCrashdummy, this is really helpful. I didn't know this!
PAB

**Comment by DJCrashdummy** [comment]
@Huster-at-github: well... for complains about the code you have to go to the RainLoop developers (https://github.com/RainLoop); but i doubt you will get any response soon. :-(
PAB is just so kind to modify the app for (easy installing in) nextcloud and shares his work with everyone.

@pierre-alain-b: yes, i also had to fiddle around a bit to completely understand the functions/settings of the rainloop-app...

btw: they are pretty cool if you just use the IMAP-backend for user-authentication, but if you start mixing the user-backends it gets a little bit clumsy. :-/

**Comment by Huster-at-github** [comment]
@pierre-alain-b : Thanks for your work!  👍

**Comment by DJCrashdummy** [comment]
@Huster-at-github you pinged (means he gets a notification) a completely different person with the username pierre (https://github.com/pierre) and not pierre-alain-b (https://github.com/pierre-alain-b)...
you must insert the correct and complete username for pinging! if you start typing the "@" (in the web interface) you get a dropdown list with mostly the right suggestions, simply click on one of them and you are fine. ;-)

@pierre-alain-b: sorry for high-jacking this thread!

**Comment by Huster-at-github** [comment]
@DJCrashdummy 

> @Huster-at-github you pinged (means he gets a notification) a completely different person

I corrected my thanks for @pierre-alain-b 
>  if you start typing the "@" (in the web interface) you get a dropdown list with mostly the right suggestions, simply click on one of them and you are fine. ;-)

I posted this with my mobile and Firefox and there I did not get a dropdown.

**Comment by hanneschu1z** [comment]
On newer Versions the personal RainLoop Settings were moved to "**additional settings**".
