### ISSUE TITLE
v6.0.1 - Server version 13 or lower is required ...

### ISSUE THREAD

**Issue by tm-107** [pierre-alain-b/rainloop-nextcloud#80]
rainloop-nextcloud v6.0.1 can't be activated on Nextcloud 14 because of a false dependency.

**Comment by tm-107** [comment]
hm ... it's working after 3rd reinstall ?!?

**Comment by pierre-alain-b** [comment]
Are you sure it was v6.0.1 and not a previous version?

**Comment by tm-107** [comment]
Yes, i've updated nextcloud from 13 to 14 and also updated rainloop-nextcloud from v5.0.3 to v6.0.1.
Than I just gave it a try and reinstalled it -> same problem. After 3rd reinstall it worked. I don't know why I tried it 3 times ... little bit crazy.

Maybe the problem was an old file in cache or someting like that. I don't know ...

**Comment by pierre-alain-b** [comment]
I will close this issue for now but we will reopen it if someone else reports the same behavior.

**Comment by Areyus** [comment]
I have encountered the same issue. It really looks like an issue with some sort of caching.
First I updated Nextcloud to 14.0.3 from 13.0.X, the updated the Rainloop plugin and got the same error message.
The issue resolved itself after logging out of and back in to Nextcloud.
