### ISSUE TITLE
[202] Data folder permissions error [is_dir] with S3 object storage

### ISSUE THREAD

**Issue by theopen-institute** [pierre-alain-b/rainloop-nextcloud#81]
Hello,

I'm getting an error when accessing either rainloop or the admin panel:

`[202] Data folder permissions error [is_dir]`

Reading through the code a bit, I strongly suspect the issue is related to the fact that I'm using S3 object storage for my primary data directory. I'd love to try to fix it if it's within my skills, but I wanted to check to get a sense of how complicated it might be first.

In any case, thanks for the work on bringing rainloop to nextcloud!

**Comment by pierre-alain-b** [comment]
Even if S3 is used to store the data directory, I assume it should be seen by the filesystem as a directory, no? Are you sure it is not just a question of folder permissions?

**Comment by theopen-institute** [comment]
The data directory is visible to the filesystem, but the structure is a fair bit different I believe. There are no user directories present there, for example.

It might be an actual permissions error, but I don't think so. Right now, my installation has
`drwxrwxr--  2 www-data www-data  4096 Oct 19 12:48 data`

with contents
```
-rw-r--r--  1 www-data www-data        0 Oct 19 12:48 audit.log
-rw-r--r--  1 www-data www-data      324 Oct 19 12:07 .htaccess
-rw-r--r--  1 www-data www-data        0 Oct 19 12:07 index.html
-rw-r-----  1 www-data www-data 39713672 Oct 22 16:49 nextcloud.log
-rw-r--r--  1 www-data www-data        0 Oct 19 12:07 .ocdata
```

Is any of that amiss from rainloop-nextcloud's perspective?

**Comment by pierre-alain-b** [comment]
If you get this error, this means that `!@is_dir(APP_DATA_FOLDER_PATH)` returns true. 

APP_DATA_FOLDER_PATH is defined by:
```
$sCustomDataPath = function_exists('__get_custom_data_full_path') ? rtrim(trim(__get_custom_data_full_path()), '\\/') : $sCustomDataPath;
			define('APP_DATA_FOLDER_PATH', 0 === strlen($sCustomDataPath) ? APP_INDEX_ROOT_PATH.'data/' : $sCustomDataPath.'/');
```
Have you defined the Nextcloud data folder path in a specific way?

**Comment by theopen-institute** [comment]
My apologies...based on your question here, I figured it out. There was a type-o in my `'datadirectory' => ` directive in config.php, but it wasn't apparent because I was using S3 for data. Rainloop works beautifully now.

Thanks for all of your hard work on this. I run a small college in a very poor country, and this is going to improve student access to email tremendously!

**Comment by pierre-alain-b** [comment]
Excellent!
