### ISSUE TITLE
howto delete attachments

### ISSUE THREAD

**Issue by roadrunnerjb** [pierre-alain-b/rainloop-nextcloud#82]
Hi,
not an issue but a feature request...

just find it very good to be able to save an attachment to nextcloud but when I saved it I want to remove it from the mail but I miss the button to do this in UI.

Thx
Joachim

**Comment by pierre-alain-b** [comment]
Hi Joachim,
This should be pushed to the Rainloop developers.
https://rainloop.uservoice.com/forums/223477-ideas-for-rainloop-webmail/suggestions/6335216-ability-to-delete-attachment-from-email
Best
Pierre-Alain
