### ISSUE TITLE
Admin Login (docs vs. UI changed)

### ISSUE THREAD

**Issue by verilucis** [pierre-alain-b/rainloop-nextcloud#83]
First, great job... I greatly appreciate being able to access rainloop w/ in nextcloud.  I have been using rainloop for a few years now, and wonderful to have access in this manner.  Greatjob!  

Next, I do not have the UI link from your documentation for the admin area.  

Please share the link?  

Thanks in advanced!  And, hope all is well!

**Comment by pierre-alain-b** [comment]
Hi,
https://your.path/index.php/apps/rainloop/app/?admin

but on my Nextcloud instance I still see it:
![image](https://user-images.githubusercontent.com/386857/47548387-2ee4c100-d8f9-11e8-9663-470f4494d878.png)

**Comment by verilucis** [comment]
Hi, Pierre.  

Will circle back around soon, investigate, and get back with you  (maybe supply a bit more information after checking versions of my instance).  

Thank you for the link!  

Hope all is well, Pierre!
