### ISSUE TITLE
Welcome text at login deformed

### ISSUE THREAD

**Issue by kees-closed** [pierre-alain-b/rainloop-nextcloud#84]
Hi,

I use Nextcloud 14.0.3 and Rainloop 6.0.1. Since I upgraded to NC14 (yesterday) Rainloop starts up a little deformed. [Here](https://cloud.neobits.nl/s/8LoazB5mrJESimJ) are a few screenshots that visualize the startup sequence. Do other people experience this as well? As you can see, my custom logo (upper left) is also not as it should be, it's big, it suppose to be the same size as my avatar logo. But it's the same size as the upper bar.

**Comment by pierre-alain-b** [comment]
Yes it is "normal", indeed the div is sized small but extended later.
For the logo, it is not a Rainloop question I think.
