### ISSUE TITLE
What about the security issues?

### ISSUE THREAD

**Issue by ohmer1** [pierre-alain-b/rainloop-nextcloud#87]
In the README file you committed last July, you said that the plugin had "some rampant security issues (not confirmed)". Can you say more about theses issues? Is it related to https://github.com/RainLoop/rainloop-webmail/issues/1082 or something else?

**Comment by pierre-alain-b** [comment]
- Yes exactly https://github.com/RainLoop/rainloop-webmail/issues/1082
- There is also https://github.com/pierre-alain-b/rainloop-nextcloud/issues/62 but it seems that there is only the warning message but no real access (no one reported being able to effectively access the data directory).

I am certainly not as worried as I was in July but I have not audited fully the code of Rainloop, we just use the code in the plugin.

**Comment by ohmer1** [comment]
The issue at RainLoop/rainloop-webmail#1082 seem like a big security hole that need to be closed. If someone gain access to the database server he can then decode all users' password from the rainloop-autologin-password parameter, so the attacker could make way more damages by using theses passwords elsewhere. I wonder why the encoded password is not just saved into the session/cookie when the user logon on nextcloud and then retrieved when the plugin need the password to forward to rainloop? Why is there a need to save the password into the database?

**Comment by pierre-alain-b** [comment]
A quick fix for that is to not save the password for the email. The interest of this is to have autologin when the owncloud/nextcloud session is opened. It indeed comes at the price of storing the password on the nextcloud side.

**Comment by ohmer1** [comment]
It's not really a fix. I think this just make the integration useless without using the autologin feature. I'm talking about using automatically the same password as the nextcloud account, not allowing a user to add a custom email account.

I will repeat my suggestion again because I didn't received feedback about it. Why the encoded password is not just saved into the session/cookie when the user logon on nextcloud and then retrieved when the plugin need the password to forward to rainloop? By doing this, you would not need to store the password into the database. Does the nextcloud api allow that? I wonder how the developpers of Nextcloud Mail app deal with this.

**Comment by feutl** [comment]
How much sense does it make to use the same password for rainloop as for nextcloud?
I am using rainloop to access multiple mail servers, and none of them is having the same password as nextcloud nor does any mail server has the same password than the other.
And as far as I understood, you authenticate against your primary mail account and this allows you to use and see the additional accounts.

The only solution I see, with your suggestion, to have some kind of fake nextcloud mail server authentication, which being used but not send to a real mail server, but triggers the rainloop process to provide you the additional mail accounts attached to the primary (fake nextcloud one)

**Comment by ohmer1** [comment]
> How much sense does it make to use the same password for rainloop as for nextcloud?

It makes sense when you are using LDAP for everything.

**Comment by feutl** [comment]
right, but couldn't you use the setting under admin > additional settings and check:
"Automatically login with ownCloud user credentials "
instead of the setting at user > additional settings?

**Comment by ohmer1** [comment]
This is what I do. When this checkbox is enabled, the password is stored into the nextcloud database (table oc_preferences, configkey = 'rainloop-autologin-password') when the user do a nextcloud login. What I say is the password should not be stored into the database, but only in a cookie.

**Comment by ohmer1** [comment]
I think this bug report should be reopened.

Seem like what I propose is what Nextcloud Mail does since about a year. https://github.com/nextcloud/mail/pull/28

**Comment by nkinkade** [comment]
@pierre-alain-b: https://github.com/pierre-alain-b/rainloop-nextcloud/pull/177

I believe that this partially resolves this issue by taking @ohmer1's suggestion of only storing the password in the ephemeral browser session.
