### ISSUE TITLE
[Question] [Config] How do I have to configure sieve?

### ISSUE THREAD

**Issue by captainjoh** [pierre-alain-b/rainloop-nextcloud#89]
I tryied to configure the sieve rule, but it doesn't work with strato.de or gmx.net inbox via imap.
Get the following error: 
stream_socket_client(): unable to connect to ssl://imap.strato.de:4190 (Connection refused)

Could you tell me how I have to configure my nexcloud sersver?

**Comment by pierre-alain-b** [comment]
Hi there,
Are you sure that strato.de and gmx.net offer Sieve as a service? Have you found any doc to set up sieve with these vendors?
Best
PAB

**Comment by captainjoh** [comment]
Hi,
Thanks for your quick response! don't think so that they support sieve. as a service. I wanted to know how can I setup sieve on my local nextcloud server (Ubuntu 18.04 LTS) to run sieve rules with any provider with rainloop. 
Where do I need to store the scripts and which accessright I've to specify?
Best Regards
Joh

**Comment by pierre-alain-b** [comment]
As far as I know, Sieve is supported/executed by IMAP servers. Rainloop will send the Sieve instructions to the IMAP server so that they are executed on the server. If you would like to use Sieve, you will need to use an IMAP service that supports Sieve.

**Comment by captainjoh** [comment]
I've managed it with a cron and imapfilter (https://linux.die.net/man/5/imapfilter_config) but it would be nice for the future to integrate this direct into rainloop or nextcloud.
