### ISSUE TITLE
User / Admin documentation missing

### ISSUE THREAD

**Issue by Huster-at-github** [pierre-alain-b/rainloop-nextcloud#9]
There are only 2 settings available and not really clear:

* 1 for admins
* 1 for users

Please create a small "HowTo" for these settings in the readme.md.

Thanks

**Comment by pierre-alain-b** [comment]
Dear Huster,
Sure there is not enough documentation. I agree on this. Do not hesitate to submit some texts on the points that you think the most misleading, we will all be glad to include them in the repository.
PAB

**Comment by pierre-alain-b** [comment]
I have just added more explanation in the Readme.md. Do not hesitate to submit a pull request with corrections and improvements!

**Comment by Huster-at-github** [comment]
👍
