### ISSUE TITLE
Rainloop stores password in cleartext in logfile

### ISSUE THREAD

**Issue by linuxpete** [pierre-alain-b/rainloop-nextcloud#90]
Today I switched logging of rainloop to investigate issues regarding carddav connection to nextcloud (V15.0.7) In this case it is the password added to the carddav address-link.

The logfile is located in my setup in : /datadirs/nextcloud/rainloop-storage/_data_/_default_/logs

When searching for the logged information I found a username AND a cleartext password, something like : 
`[06:40:48.592][62c03467] POST[DATA]: {"Enable":"1","Url":"https:\/\/nextcloudinstanc.nl\/remote.php\/dav\/addressbooks\/users\/username\/contacts","User":"username","Password":"---somecleartextpassword---","Action":"SaveContactsSyncData","XToken":"04debe9153410ef7755078086a810ccf"}`

My setup : 

Rainloop : v6.0.2
Nextcloud : V15.0.7
OS : Ubuntu 18.04

**Comment by pierre-alain-b** [comment]
Hello,
This is a behavior of rainloop and should presumably be addressed by the Rainloop developers. I recommend that you post the issue here: https://github.com/RainLoop/rainloop-webmail and when Rainloop will be fixed, the new version will be implemented in the Nextcloud plugin.
Best

**Comment by linuxpete** [comment]
Hi Pierre-Alain:

Done so : https://github.com/RainLoop/rainloop-webmail/issues/1872

Thnx, Pieter
