### ISSUE TITLE
Default identity is ignored

### ISSUE THREAD

**Issue by zuglufttier** [pierre-alain-b/rainloop-nextcloud#91]
You are supposed to select a default identity by ordering the accounts in rainloop as explained here: https://github.com/RainLoop/rainloop-webmail/issues/710

However, this does not seem to work with rainloop-nextcloud. The e-mail account associated with the nextcloud account is always selected first instead.

**Comment by pierre-alain-b** [comment]
I do not replicate this one. In my instance, it works just fine.

Identity 1 being default is the one that is chosen by default when opening a new mail.
When I drag&drop the identity 2 to have it first, it is labelled with "default" and then this is well that one that is proposed first when opening a new mail.

Are you referring to identities or accounts?

**Comment by zuglufttier** [comment]
I am referring to accounts - I would like to choose one account that is displayed first when I open rainloop.

**Comment by pierre-alain-b** [comment]
The link you shared only mentions the identities. I don't know if the same behavior is possible for accounts. It is not totally irrelevant to start with the main account...

**Comment by zuglufttier** [comment]
Sorry, looks like I wanted to read something that isn't there ;)

But an option to select a default account would be nice anyway!
