### ISSUE TITLE
Google Document Viewer Issue

### ISSUE THREAD

**Issue by yward** [pierre-alain-b/rainloop-nextcloud#93]
The google document viewer shows the page source of the login page instead of previewing the document as shown here:
https://i.postimg.cc/kXHm3XW3/Screenshot-2019-05-17-https-team-art4m-art.png

This issue only happens in NextCloud as it appears to send the login page to google viewer instead of the actual document.
A rainloop installed outside of NextCloud would work fine, as shown here:
https://i.postimg.cc/HW2MtFX7/Screenshot-2019-05-17-https-email-art4mart-com.png

**Comment by yward** [comment]
@pierre-alain-b @tabp0le Any hint would be much appreciated!

**Comment by pierre-alain-b** [comment]
Hi, and you get there by doing what?
Thanks for your your help to replicate.

**Comment by yward** [comment]
@pierre-alain-b  from the admin settings setup your google API keys.

Then when you receive an office file, a word document for example, click on the icon, not the file name as shown here:
https://i.postimg.cc/d1qhZYKW/desktop.png

**Comment by pierre-alain-b** [comment]
OK I found the option in the Integration section of the Rainloop admin settings. I must admit this is not a feature of Rainloop I use. How can I get a google API key to give it a try and try to replicate?

**Comment by pierre-alain-b** [comment]
closing in the absence of a reply and unable to replicate
