### ISSUE TITLE
Suggestions include all local Nextcloud users

### ISSUE THREAD

**Issue by Nutomic** [pierre-alain-b/rainloop-nextcloud#95]
We are using rainloop-nextcloud on a big instance with 1000+ users. For this case, we do not want users to find out the username/email of other local users. For now we disabled suggestions completely as a workaround

However, we want to use suggestions and contacts, just without local users being suggested. I would be happy to implement this, but I would appreciate a hint where to get started and how to make it configurable.

**Comment by pierre-alain-b** [comment]
Hi there,
Are you referring to the suggestions in this box?
![image](https://user-images.githubusercontent.com/386857/59380525-a288f080-8d59-11e9-9fe4-7ffb25cfd393.png)
if yes, this is a feature of Nextcloud itself and not of the Rainloop plugin.

Or are you thinking of another place?

**Comment by pierre-alain-b** [comment]
If this is what you are looking for, here is where the code seems to be:
https://github.com/nextcloud/server/blob/733515f277c49fd3f6468abd53ce69bfef397670/core/src/OC/contactsmenu.js

**Comment by pierre-alain-b** [comment]
And without being 100% sure, it seems to me that this is the place where both users and contacts are retrieved: https://github.com/nextcloud/server/blob/2e36069e24406455ad3f3998aa25e2a949d1402a/lib/private/Contacts/ContactsMenu/Manager.php#L58

**Comment by pierre-alain-b** [comment]
I am closing because this is not a Nextcloud-rainloop topic but rather a pure nextcloud one. I hope I helped with the above and will be happy to hear about this nice idea.
For smaller instances, it seems to me that users can be isolated in different groups and then they would only see users pertaining to the same groups. But not an option to isolate all of them and have none of them see no other.

**Comment by Nutomic** [comment]
Sorry I should have clarified this better. I am talking about the suggestions in the "To" field when writing an email (these are all local accounts, the address list is empty):
![Screenshot_20190613_110457](https://user-images.githubusercontent.com/1044450/59419500-95501e00-8dba-11e9-917f-c8f2f920df84.png)

We already disabled the contacts search that you mentioned in our Nextcloud config. So maybe it would be a good idea if rainloop-nextcloud could respect that setting as well.

**Comment by pierre-alain-b** [comment]
Ah I see now. The point is valid!

**Comment by pierre-alain-b** [comment]
I assume this is where the suggestions come from.
https://github.com/pierre-alain-b/rainloop-nextcloud/blob/66bdb5a64c4546e60d62352e1c21ba734a4c60ad/rainloop/app/rainloop/v/1.12.1/app/libraries/RainLoop/Providers/Suggestions/OwnCloudSuggestions.php

**Comment by pierre-alain-b** [comment]
And I see this line in the config: https://github.com/pierre-alain-b/rainloop-nextcloud/blob/66bdb5a64c4546e60d62352e1c21ba734a4c60ad/rainloop/app/rainloop/v/1.12.1/app/libraries/RainLoop/Config/Application.php#L437
I don't know if this is it but I am tempted to try to put this value to false.

**Comment by pierre-alain-b** [comment]
I think we got it.
Just change this line in the config:
`owncloud_suggestions = On`
to
`owncloud_suggestions = Off`

And I think this is good!

**Comment by Nutomic** [comment]
Thanks a lot, thats exactly what I was looking for. Sorry I had no idea that there was already an option in rainloop, I thought this was a feature of the plugin.

**Comment by tomastd** [comment]
Thank you Pierre, but I think that it is just part of the solution. A walkaround I will say.

Now no suggestion at all is shown. The expected behaviour (in our case) would be to suggest "My contacts" and not "Nextcloud users". Is it possible?

The path has been little bit changed in Nextcloud18 (there are some underscores):
`/data/rainloop-storage/_data_/_default_/configs/application.ini`

The second line on the file says:
`; Please don't add custom parameters here, those will be overwritten`
Is there a way to make it permanent?

Are more options than On and Off? Can the parameter accept "Users" or "Contacts" as value?
`owncloud_suggestions = Contacts`

If not, can it be considered as a suggestion?

Thank you very much!!!

**Comment by pierre-alain-b** [comment]
Rainloop has a "contacts" feature that can be synchronized with the contacts of Nextcloud but unfortunately this is not configured automatically. You need to manually share your Nextcloud contacts and then activate the sync with that. I hope this helps.

**Comment by tomastd** [comment]
That is a task for each user to do into their email account, isn't it?

**Comment by pierre-alain-b** [comment]
Indeed, this cannot be set centrally by the administrator. I totally agree that this is not optimal. In fact Rainloop is not fully integrated into NC, it is mainly the Rainloop webmail being made available without that many common features. I know the Nextcloud core team is advancing well the official Mail plugin that is not certainly much more integrated.

**Comment by tomastd** [comment]
Thank you very much Pierre. Great support!!!

**Comment by kofaysi** [comment]
> 
> 
> Rainloop has a "contacts" feature that can be synchronized with the contacts of Nextcloud but unfortunately this is not configured automatically. You need to manually share your Nextcloud contacts and then activate the sync with that. I hope this helps.

Dear @pierre-alain-b, please, be more specific. Does that mean a user have to export contacts from NC Contacts, then import them into RainLoop and then there is going to be a sync option to activate? I do not see a link possibility between NC Contacts and RL Contacts. The sync link is to be broken by export-import action of a file.

**Comment by pierre-alain-b** [comment]
No no, I am not referring to import/export but real sync.
I think these options of Rainloop (available in Rainloop admin panel) are self explanatory:
![image](https://user-images.githubusercontent.com/386857/85526533-61811880-b60a-11ea-9d0a-02fcb2a118a2.png)

Then, each user (this is what is not well integrated with this approach) shall set the sync in Rainloop user settings:
![image](https://user-images.githubusercontent.com/386857/85526860-a86f0e00-b60a-11ea-893f-65ac740eebc6.png)

Does this help?
