### ISSUE TITLE
Link to go to admin panel is not visible

### ISSUE THREAD

**Issue by hydrandt** [pierre-alain-b/rainloop-nextcloud#97]
Hi,

Testing Rainloop on latest Nextcloud (16.0.4). After going to Settings -> Additional settings, the link to go to rainloop admin panel is not there, it looks like this:

![image](https://user-images.githubusercontent.com/11388094/61196736-3f490000-a703-11e9-96ae-83f6a6ae2280.png)

Visiting /apps/rainloop/app/?admin works fine - just not easy to find.

**Comment by nextgen-networks** [comment]
... hmm - I think you've made a typo...
Did you mean NC 16.0.3 ?
NC 16.0.4 is not released as far as im imformed ...
(see: https://github.com/nextcloud/server/releases)

But now head over to your "problem".
The Admin Panel link could be found in the "Administration" section (not in "Personal").
If you check the "Automatically login with ownCloud user credentials" the link for personal account management is no more visible in "Personal" / "Additional Seetings". As far as I know this is made by intention.

Hope that helps.

**Comment by hydrandt** [comment]
Right in both, it is 16.0.3, and right, my blindness is unbelievable. Sorry for the noise.
