### ISSUE TITLE
Rainloop 1.13.0 release

### ISSUE THREAD

**Issue by nextgen-networks** [pierre-alain-b/rainloop-nextcloud#98]
Hey @pierre-alain-b,
a fresh version has been released by rainloop devs.
It would be fantastic to have it here as NC app again.

Thanks and have a great start in the week!

raupe

**Comment by pierre-alain-b** [comment]
Thanks for the heads up! Will do soon!

**Comment by ghost** [comment]
Me too, I'm waiting for the new version :)

**Comment by pierre-alain-b** [comment]
Work in progress

**Comment by pierre-alain-b** [comment]
Done and published on Nextcloud apps platform!

**Comment by ghost** [comment]
Thank !!! :)

**Comment by pierre-alain-b** [comment]
See here: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/99
It worked for me, what about you?

**Comment by ghost** [comment]
yes it's ok for me. I Don't have any problem. Congrulation !

Thank you for your work :)

**Comment by pierre-alain-b** [comment]
Which NC version do you have? I am still in 15.x and the issue in #99 is reported in 16.0.3. Just to understand if this is specific to a version of NC...
