### ISSUE TITLE
Appinfo not correct newest Update

### ISSUE THREAD

**Issue by NiclasPe** [pierre-alain-b/rainloop-nextcloud#99]
Rainloop can not be activated because Nextcloud can‘t read the appinfo:

App "rainloop" cannot be installed because appinfo file cannot be read.

**Comment by pierre-alain-b** [comment]
Strange, it worked in my case.
Is it a fresh install or an upgrade?

**Comment by NiclasPe** [comment]
It´s a Upgrade

**Comment by NiclasPe** [comment]
Gut i also canˋt reinstall it.

**Comment by pierre-alain-b** [comment]
Which version of NC?
Where do you see the error message?

**Comment by NiclasPe** [comment]
The newest Version. 

In the internal Appcenter

**Comment by pierre-alain-b** [comment]
And what is the newest version in your case (depends on the NC update channel)?

**Comment by NiclasPe** [comment]
Rainloop 6.0.3

Nextcloud 16.0.3

**Comment by pierre-alain-b** [comment]
Another user reports that it works, investigating further.
https://github.com/pierre-alain-b/rainloop-nextcloud/issues/98

**Comment by NiclasPe** [comment]
Ok i want to traf reinstall it manually

**Comment by nextgen-networks** [comment]
I'm on NC 16.0.3 also and had no problem with the update install from 6.0.2.

**Comment by NiclasPe** [comment]
Yes, i think also, reinstalled it manually and it will work. I think it’s an Nextcloud bugg. 

Thanks for your fast Help. 
You do an great work 
Respect. ✊
